import type { TriviaQuestion } from "../engine";

export const capitalsGuessBank: TriviaQuestion[] = [
  { kind: "text", display: "🇸🇦 السعودية", accepted: ["الرياض"] },
  { kind: "text", display: "🇪🇬 مصر", accepted: ["القاهرة"] },
  { kind: "text", display: "🇦🇪 الامارات", accepted: ["ابوظبي", "أبوظبي"] },
  { kind: "text", display: "🇯🇴 الأردن", accepted: ["عمان"] },
  { kind: "text", display: "🇰🇼 الكويت", accepted: ["الكويت"] },
  { kind: "text", display: "🇶🇦 قطر", accepted: ["الدوحة"] },
  { kind: "text", display: "🇧🇭 البحرين", accepted: ["المنامة"] },
  { kind: "text", display: "🇴🇲 عمان", accepted: ["مسقط"] },
  { kind: "text", display: "🇮🇶 العراق", accepted: ["بغداد"] },
  { kind: "text", display: "🇸🇾 سوريا", accepted: ["دمشق"] },
  { kind: "text", display: "🇱🇧 لبنان", accepted: ["بيروت"] },
  { kind: "text", display: "🇵🇸 فلسطين", accepted: ["القدس"] },
  { kind: "text", display: "🇾🇪 اليمن", accepted: ["صنعاء"] },
  { kind: "text", display: "🇲🇦 المغرب", accepted: ["الرباط"] },
  { kind: "text", display: "🇩🇿 الجزائر", accepted: ["الجزائر"] },
  { kind: "text", display: "🇹🇳 تونس", accepted: ["تونس"] },
  { kind: "text", display: "🇱🇾 ليبيا", accepted: ["طرابلس"] },
  { kind: "text", display: "🇸🇩 السودان", accepted: ["الخرطوم"] },
  { kind: "text", display: "🇲🇷 موريتانيا", accepted: ["نواكشوط"] },
  { kind: "text", display: "🇸🇴 الصومال", accepted: ["مقديشو"] },
  { kind: "text", display: "🇩🇯 جيبوتي", accepted: ["جيبوتي"] },
  { kind: "text", display: "🇰🇲 جزر القمر", accepted: ["موروني"] },
  { kind: "text", display: "🇺🇸 امريكا", accepted: ["واشنطن"] },
  { kind: "text", display: "🇨🇦 كندا", accepted: ["أوتاوا", "اوتاوا"] },
  { kind: "text", display: "🇲🇽 المكسيك", accepted: ["مكسيكو سيتي", "مكسيكو"] },
  { kind: "text", display: "🇧🇷 البرازيل", accepted: ["برازيليا"] },
  { kind: "text", display: "🇦🇷 الأرجنتين", accepted: ["بوينس آيرس", "بوينس ايرس"] },
  { kind: "text", display: "🇨🇱 تشيلي", accepted: ["سانتياغو"] },
  { kind: "text", display: "🇨🇴 كولومبيا", accepted: ["بوغوتا"] },
  { kind: "text", display: "🇵🇪 بيرو", accepted: ["ليما"] },
  { kind: "text", display: "🇻🇪 فنزويلا", accepted: ["كاراكاس"] },
  { kind: "text", display: "🇪🇨 الاكوادور", accepted: ["كيتو"] },
  { kind: "text", display: "🇧🇴 بوليفيا", accepted: ["لاباز", "سوكري"] },
  { kind: "text", display: "🇺🇾 الأوروغواي", accepted: ["مونتيفيديو"] },
  { kind: "text", display: "🇵🇾 باراغواي", accepted: ["أسونسيون", "اسونسيون"] },
  { kind: "text", display: "🇨🇺 كوبا", accepted: ["هافانا"] },
  { kind: "text", display: "🇬🇧 بريطانيا", accepted: ["لندن"] },
  { kind: "text", display: "🇫🇷 فرنسا", accepted: ["باريس"] },
  { kind: "text", display: "🇩🇪 المانيا", accepted: ["برلين"] },
  { kind: "text", display: "🇮🇹 ايطاليا", accepted: ["روما"] },
  { kind: "text", display: "🇪🇸 اسبانيا", accepted: ["مدريد"] },
  { kind: "text", display: "🇵🇹 البرتغال", accepted: ["لشبونة"] },
  { kind: "text", display: "🇳🇱 هولندا", accepted: ["امستردام", "أمستردام"] },
  { kind: "text", display: "🇧🇪 بلجيكا", accepted: ["بروكسل"] },
  { kind: "text", display: "🇨🇭 سويسرا", accepted: ["برن"] },
  { kind: "text", display: "🇦🇹 النمسا", accepted: ["فيينا"] },
  { kind: "text", display: "🇸🇪 السويد", accepted: ["ستوكهولم"] },
  { kind: "text", display: "🇳🇴 النرويج", accepted: ["أوسلو", "اوسلو"] },
  { kind: "text", display: "🇩🇰 الدنمارك", accepted: ["كوبنهاغن"] },
  { kind: "text", display: "🇫🇮 فنلندا", accepted: ["هلسنكي"] },
  { kind: "text", display: "🇮🇸 ايسلندا", accepted: ["ريكيافيك"] },
  { kind: "text", display: "🇮🇪 ايرلندا", accepted: ["دبلن"] },
  { kind: "text", display: "🇬🇷 اليونان", accepted: ["أثينا", "اثينا"] },
  { kind: "text", display: "🇵🇱 بولندا", accepted: ["وارسو"] },
  { kind: "text", display: "🇨🇿 التشيك", accepted: ["براغ"] },
  { kind: "text", display: "🇸🇰 سلوفاكيا", accepted: ["براتيسلافا"] },
  { kind: "text", display: "🇭🇺 المجر", accepted: ["بودابست"] },
  { kind: "text", display: "🇷🇴 رومانيا", accepted: ["بوخارست"] },
  { kind: "text", display: "🇧🇬 بلغاريا", accepted: ["صوفيا"] },
  { kind: "text", display: "🇺🇦 اوكرانيا", accepted: ["كييف"] },
  { kind: "text", display: "🇧🇾 بيلاروسيا", accepted: ["مينسك"] },
  { kind: "text", display: "🇷🇺 روسيا", accepted: ["موسكو"] },
  { kind: "text", display: "🇹🇷 تركيا", accepted: ["أنقرة", "انقرة"] },
  { kind: "text", display: "🇭🇷 كرواتيا", accepted: ["زغرب"] },
  { kind: "text", display: "🇷🇸 صربيا", accepted: ["بلغراد"] },
  { kind: "text", display: "🇸🇮 سلوفينيا", accepted: ["ليوبليانا"] },
  { kind: "text", display: "🇦🇱 البانيا", accepted: ["تيرانا"] },
  { kind: "text", display: "🇲🇰 مقدونيا الشمالية", accepted: ["سكوبيه"] },
  { kind: "text", display: "🇽🇰 كوسوفو", accepted: ["بريشتينا"] },
  { kind: "text", display: "🇧🇦 البوسنة والهرسك", accepted: ["سراييفو"] },
  { kind: "text", display: "🇲🇹 مالطا", accepted: ["فاليتا"] },
  { kind: "text", display: "🇱🇺 لوكسمبورغ", accepted: ["لوكسمبورغ"] },
  { kind: "text", display: "🇱🇹 ليتوانيا", accepted: ["فيلنيوس"] },
  { kind: "text", display: "🇱🇻 لاتفيا", accepted: ["ريغا"] },
  { kind: "text", display: "🇪🇪 استونيا", accepted: ["تالين"] },
  { kind: "text", display: "🇲🇩 مولدوفا", accepted: ["كيشيناو"] },
  { kind: "text", display: "🇬🇪 جورجيا", accepted: ["تبليسي"] },
  { kind: "text", display: "🇦🇲 أرمينيا", accepted: ["يريفان"] },
  { kind: "text", display: "🇦🇿 أذربيجان", accepted: ["باكو"] },
  { kind: "text", display: "🇯🇵 اليابان", accepted: ["طوكيو"] },
  { kind: "text", display: "🇨🇳 الصين", accepted: ["بكين"] },
  { kind: "text", display: "🇰🇷 كوريا الجنوبية", accepted: ["سيول"] },
  { kind: "text", display: "🇰🇵 كوريا الشمالية", accepted: ["بيونغ يانغ"] },
  { kind: "text", display: "🇮🇳 الهند", accepted: ["نيودلهي", "دلهي"] },
  { kind: "text", display: "🇵🇰 باكستان", accepted: ["اسلام آباد", "اسلام اباد"] },
  { kind: "text", display: "🇧🇩 بنغلاديش", accepted: ["دكا"] },
  { kind: "text", display: "🇱🇰 سريلانكا", accepted: ["كولومبو"] },
  { kind: "text", display: "🇳🇵 نيبال", accepted: ["كاتماندو"] },
  { kind: "text", display: "🇦🇫 أفغانستان", accepted: ["كابل"] },
  { kind: "text", display: "🇮🇷 ايران", accepted: ["طهران"] },
  { kind: "text", display: "🇮🇩 اندونيسيا", accepted: ["جاكرتا"] },
  { kind: "text", display: "🇲🇾 ماليزيا", accepted: ["كوالالمبور"] },
  { kind: "text", display: "🇸🇬 سنغافورة", accepted: ["سنغافورة"] },
  { kind: "text", display: "🇹🇭 تايلاند", accepted: ["بانكوك"] },
  { kind: "text", display: "🇻🇳 فيتنام", accepted: ["هانوي"] },
  { kind: "text", display: "🇵🇭 الفلبين", accepted: ["مانيلا"] },
  { kind: "text", display: "🇲🇲 ميانمار", accepted: ["نايبيداو"] },
  { kind: "text", display: "🇰🇭 كمبوديا", accepted: ["بنوم بنه"] },
  { kind: "text", display: "🇱🇦 لاوس", accepted: ["فيينتيان"] },
  { kind: "text", display: "🇲🇳 منغوليا", accepted: ["اولان باتور"] },
  { kind: "text", display: "🇰🇿 كازاخستان", accepted: ["أستانا", "استانا"] },
  { kind: "text", display: "🇺🇿 أوزبكستان", accepted: ["طشقند"] },
  { kind: "text", display: "🇹🇲 تركمانستان", accepted: ["عشق آباد"] },
  { kind: "text", display: "🇰🇬 قيرغيزستان", accepted: ["بيشكيك"] },
  { kind: "text", display: "🇹🇯 طاجيكستان", accepted: ["دوشنبه"] },
  { kind: "text", display: "🇦🇺 استراليا", accepted: ["كانبيرا"] },
  { kind: "text", display: "🇳🇿 نيوزيلندا", accepted: ["ويلينغتون"] },
  { kind: "text", display: "🇫🇯 فيجي", accepted: ["سوفا"] },
  { kind: "text", display: "🇵🇬 بابوا غينيا الجديدة", accepted: ["بورت مورسبي"] },
  { kind: "text", display: "🇿🇦 جنوب افريقيا", accepted: ["بريتوريا"] },
  { kind: "text", display: "🇳🇬 نيجيريا", accepted: ["ابوجا"] },
  { kind: "text", display: "🇰🇪 كينيا", accepted: ["نيروبي"] },
  { kind: "text", display: "🇪🇹 اثيوبيا", accepted: ["أديس أبابا", "اديس ابابا"] },
  { kind: "text", display: "🇬🇭 غانا", accepted: ["أكرا", "اكرا"] },
  { kind: "text", display: "🇹🇿 تنزانيا", accepted: ["دودوما"] },
  { kind: "text", display: "🇺🇬 أوغندا", accepted: ["كمبالا"] },
  { kind: "text", display: "🇸🇳 السنغال", accepted: ["داكار"] },
  { kind: "text", display: "🇨🇮 ساحل العاج", accepted: ["ياموسوكرو"] },
  { kind: "text", display: "🇨🇲 الكاميرون", accepted: ["ياوندي"] },
  { kind: "text", display: "🇿🇼 زيمبابوي", accepted: ["هراري"] },
  { kind: "text", display: "🇿🇲 زامبيا", accepted: ["لوساكا"] },
  { kind: "text", display: "🇦🇴 أنغولا", accepted: ["لواندا"] },
  { kind: "text", display: "🇲🇿 موزمبيق", accepted: ["مابوتو"] },
  { kind: "text", display: "🇳🇦 ناميبيا", accepted: ["ويندهوك"] },
  { kind: "text", display: "🇧🇼 بوتسوانا", accepted: ["غابورون"] },
  { kind: "text", display: "🇷🇼 رواندا", accepted: ["كيغالي"] },
  { kind: "text", display: "🇲🇱 مالي", accepted: ["باماكو"] },
  { kind: "text", display: "🇳🇪 النيجر", accepted: ["نيامي"] },
  { kind: "text", display: "🇹🇩 تشاد", accepted: ["انجمينا"] },
  { kind: "text", display: "🇧🇫 بوركينا فاسو", accepted: ["واغادوغو"] },
  { kind: "text", display: "🇬🇦 الغابون", accepted: ["ليبرفيل"] },
  { kind: "text", display: "🇧🇯 بنين", accepted: ["بورتو نوفو"] },
  { kind: "text", display: "🇹🇬 توغو", accepted: ["لومي"] },
  { kind: "text", display: "🇱🇷 ليبيريا", accepted: ["مونروفيا"] },
  { kind: "text", display: "🇸🇱 سيراليون", accepted: ["فريتاون"] },
  { kind: "text", display: "🇲🇬 مدغشقر", accepted: ["انتاناناريفو"] },
  { kind: "text", display: "🇲🇺 موريشيوس", accepted: ["بورت لويس"] }
];
