import type { TriviaQuestion } from "../engine";

export const emojiGuessBank: TriviaQuestion[] = [
  { kind: "emoji", display: "🍥🦊🥷", meta: { category: "أنمي" }, accepted: ["ناروتو"] },
  { kind: "emoji", display: "🏴‍☠️🍖👒", meta: { category: "أنمي" }, accepted: ["ون بيس", "ونبيس"] },
  { kind: "emoji", display: "⚔️👹🎌", meta: { category: "أنمي" }, accepted: ["قاتل الشياطين", "ديمون سلاير"] },
  { kind: "emoji", display: "🧱🦾👊", meta: { category: "أنمي" }, accepted: ["هجوم العمالقة", "اتاك اون تايتن"] },
  { kind: "emoji", display: "📓💀🍎", meta: { category: "أنمي" }, accepted: ["مذكرة الموت", "ديث نوت"] },
  { kind: "emoji", display: "🥋🐉⭐", meta: { category: "أنمي" }, accepted: ["دراغون بول", "كرات التنين"] },
  { kind: "emoji", display: "👊🦸‍♂️🥚", meta: { category: "أنمي" }, accepted: ["ون بنش مان"] },
  { kind: "emoji", display: "⚗️🦾🧪", meta: { category: "أنمي" }, accepted: ["الخيميائي المعدني", "فول ميتال"] },
  { kind: "emoji", display: "🏐🧡🐦", meta: { category: "أنمي" }, accepted: ["هايكيو"] },
  { kind: "emoji", display: "⚽🥅🔵", meta: { category: "أنمي" }, accepted: ["بلو لوك"] },
  { kind: "emoji", display: "🕵️🍬👦", meta: { category: "أنمي" }, accepted: ["المحقق كونان", "كونان"] },
  { kind: "emoji", display: "⚽🇯🇵🏆", meta: { category: "أنمي" }, accepted: ["كابتن ماجد"] },
  { kind: "emoji", display: "🏐👧🎌", meta: { category: "أنمي" }, accepted: ["عدنان ولينا"] },
  { kind: "emoji", display: "🤖🦾🌸", meta: { category: "أنمي" }, accepted: ["غراندايزر"] },
  { kind: "emoji", display: "🐭⚡🔴", meta: { category: "أنمي" }, accepted: ["بوكيمون"] },
  { kind: "emoji", display: "🃏🐉👁️", meta: { category: "أنمي" }, accepted: ["يوغي", "يوغي يو"] },
  { kind: "emoji", display: "🧙‍♂️🪄🍀", meta: { category: "أنمي" }, accepted: ["بلاك كلوفر"] },
  { kind: "emoji", display: "👻🗡️🏫", meta: { category: "أنمي" }, accepted: ["جوجوتسو كايسن"] },
  { kind: "emoji", display: "🎭🧛☕", meta: { category: "أنمي" }, accepted: ["طوكيو غول"] },
  { kind: "emoji", display: "🗡️🎮🌐", meta: { category: "أنمي" }, accepted: ["سورد آرت اونلاين"] },
  { kind: "emoji", display: "🚬🚀🤠", meta: { category: "أنمي" }, accepted: ["كاوبوي بيبوب"] },
  { kind: "emoji", display: "🐺🌲🏹", meta: { category: "أنمي" }, accepted: ["الأميرة مونونوكي"] },
  { kind: "emoji", display: "🐷🛁👧", meta: { category: "أنمي" }, accepted: ["المخطوفة", "سبيريتد اواي"] },
  { kind: "emoji", display: "🦸‍♂️🔥🏫", meta: { category: "أنمي" }, accepted: ["اكاديميتي للابطال", "ماي هيرو اكاديميا"] },
  { kind: "emoji", display: "⚓🔥🐒", meta: { category: "أنمي" }, accepted: ["لوفي"] },
  { kind: "emoji", display: "🗡️🍶🎋", meta: { category: "أنمي" }, accepted: ["زورو"] },
  { kind: "emoji", display: "👁️🔴🥷", meta: { category: "أنمي" }, accepted: ["ساسكي"] },
  { kind: "emoji", display: "🦇👁️🥷", meta: { category: "أنمي" }, accepted: ["إيتاتشي"] },
  { kind: "emoji", display: "📖🥷🐸", meta: { category: "أنمي" }, accepted: ["كاكاشي"] },
  { kind: "emoji", display: "👦🍜🥢", meta: { category: "أنمي" }, accepted: ["ميدوريا", "ديكو"] },
  { kind: "emoji", display: "⚡🟡🎌", meta: { category: "أنمي" }, accepted: ["زينيتسو"] },
  { kind: "emoji", display: "🐗🐽⚔️", meta: { category: "أنمي" }, accepted: ["اينوسكي"] },
  { kind: "emoji", display: "💧⚔️👦", meta: { category: "أنمي" }, accepted: ["تانجيرو"] },
  { kind: "emoji", display: "🎋👧🎍", meta: { category: "أنمي" }, accepted: ["نيزوكو"] },
  { kind: "emoji", display: "⛏️🏔️🎌", meta: { category: "أنمي" }, accepted: ["دكتور ستون"] },
  { kind: "emoji", display: "🍳🏨🍽️", meta: { category: "أنمي" }, accepted: ["شوكوغيكي", "معركة الطبخ"] },
  { kind: "emoji", display: "🎹🎻🌸", meta: { category: "أنمي" }, accepted: ["كذبتك في ابريل"] },
  { kind: "emoji", display: "🌦️👧🗼", meta: { category: "أنمي" }, accepted: ["طقس معك"] },
  { kind: "emoji", display: "☄️🔁👫", meta: { category: "أنمي" }, accepted: ["اسمك", "يور نيم"] },
  { kind: "emoji", display: "🏰🚶🔥", meta: { category: "أنمي" }, accepted: ["قلعة هاول المتحركة"] },
  { kind: "emoji", display: "🌳🐈☂️", meta: { category: "أنمي" }, accepted: ["جاري توتورو", "توتورو"] },
  { kind: "emoji", display: "🧹🐈📦", meta: { category: "أنمي" }, accepted: ["خدمة توصيل كيكي"] },
  { kind: "emoji", display: "🐟👧🌊", meta: { category: "أنمي" }, accepted: ["بونيو"] },
  { kind: "emoji", display: "⚔️🩸🌙", meta: { category: "أنمي" }, accepted: ["بيرسيرك"] },
  { kind: "emoji", display: "🏹🐺🎌", meta: { category: "أنمي" }, accepted: ["فينلاند ساغا"] },
  { kind: "emoji", display: "🤖🧬🔬", meta: { category: "أنمي" }, accepted: ["شتاينز غيت"] },
  { kind: "emoji", display: "🎲🃏😈", meta: { category: "أنمي" }, accepted: ["كاكيغوروي"] },
  { kind: "emoji", display: "🐰🕳️🎩", meta: { category: "أنمي" }, accepted: ["أليس في بلاد العجائب"] },
  { kind: "emoji", display: "👨‍🍳🍜🎌", meta: { category: "أنمي" }, accepted: ["ميستر اجيكو"] },
  { kind: "emoji", display: "🏀🟠🎌", meta: { category: "أنمي" }, accepted: ["سلام دانك"] },
  { kind: "emoji", display: "🏀🌈👦", meta: { category: "أنمي" }, accepted: ["كوروكو"] },
  { kind: "emoji", display: "🎾🎌🟢", meta: { category: "أنمي" }, accepted: ["امير التنس"] },
  { kind: "emoji", display: "🥊🥇🎌", meta: { category: "أنمي" }, accepted: ["هاجيمي نو ايبو"] },
  { kind: "emoji", display: "🏎️💨🏁", meta: { category: "أنمي" }, accepted: ["اينشيال دي"] },
  { kind: "emoji", display: "🚴⛰️🎌", meta: { category: "أنمي" }, accepted: ["يوري على الجليد"] },
  { kind: "emoji", display: "🤺🥋👧", meta: { category: "أنمي" }, accepted: ["ليدي ليدي"] },
  { kind: "emoji", display: "🐝🌼👦", meta: { category: "أنمي" }, accepted: ["مغامرات عدنان", "النحلة مايا"] },
  { kind: "emoji", display: "🐕👦🏔️", meta: { category: "أنمي" }, accepted: ["بابل", "هايدي"] },
  { kind: "emoji", display: "🏔️👧🐐", meta: { category: "أنمي" }, accepted: ["هايدي"] },
  { kind: "emoji", display: "🐒☁️🥢", meta: { category: "أنمي" }, accepted: ["سنبل", "ساكو"] },
  { kind: "emoji", display: "🚂🌌🎫", meta: { category: "أنمي" }, accepted: ["قطار المجرة"] },
  { kind: "emoji", display: "🦁👑🎌", meta: { category: "أنمي" }, accepted: ["كيمبا"] },
  { kind: "emoji", display: "🤖👦❤️", meta: { category: "أنمي" }, accepted: ["أسترو بوي"] },
  { kind: "emoji", display: "🚀⚔️🌌", meta: { category: "أنمي" }, accepted: ["فارس الفضاء", "غانمو"] },
  { kind: "emoji", display: "🎴🀄👧", meta: { category: "أنمي" }, accepted: ["شيغاتسو", "تشيهايافورو"] },
  { kind: "emoji", display: "🧛🌹🏰", meta: { category: "أنمي" }, accepted: ["فامباير نايت"] },
  { kind: "emoji", display: "🌹👑⚔️", meta: { category: "أنمي" }, accepted: ["ليدي أوسكار"] },
  { kind: "emoji", display: "🕵️🎩💎", meta: { category: "أنمي" }, accepted: ["لوبين الثالث", "لوبان"] },
  { kind: "emoji", display: "🐉🥋🔵", meta: { category: "أنمي" }, accepted: ["غوكو"] },
  { kind: "emoji", display: "👑🥋💥", meta: { category: "أنمي" }, accepted: ["فيجيتا"] },
  { kind: "emoji", display: "🌀🐟🎌", meta: { category: "أنمي" }, accepted: ["بليتش"] },
  { kind: "emoji", display: "🗝️👻🏚️", meta: { category: "أنمي" }, accepted: ["أنوشا", "أنو هانا"] },
  { kind: "emoji", display: "📦🐉🎮", meta: { category: "أنمي" }, accepted: ["أوفرلورد"] },
  { kind: "emoji", display: "⚔️🛡️🎮", meta: { category: "أنمي" }, accepted: ["نهوض بطل الدرع"] },
  { kind: "emoji", display: "🧊🔮🎌", meta: { category: "أنمي" }, accepted: ["فيري تيل"] },
  { kind: "emoji", display: "🐍🧪🥷", meta: { category: "أنمي" }, accepted: ["أوروتشيمارو"] },
  { kind: "emoji", display: "🌪️🥷👦", meta: { category: "أنمي" }, accepted: ["بوروتو"] },
  { kind: "emoji", display: "🌸👊👧", meta: { category: "أنمي" }, accepted: ["ساكورا"] },
  { kind: "emoji", display: "🍶🐌🥷", meta: { category: "أنمي" }, accepted: ["تسونادي"] },
  { kind: "emoji", display: "🎤🎀🌟", meta: { category: "أنمي" }, accepted: ["لاف لايف"] },
  { kind: "emoji", display: "🍰🏰👗", meta: { category: "أنمي" }, accepted: ["نادي المضيفين"] },
  { kind: "emoji", display: "🔪👘🌸", meta: { category: "أنمي" }, accepted: ["روروني كينشين", "الساموراي المتجول"] },
  { kind: "emoji", display: "🥋🐯🎌", meta: { category: "أنمي" }, accepted: ["بايبلوس"] },
  { kind: "emoji", display: "🎩🕵️🎌", meta: { category: "أنمي" }, accepted: ["المفتش كونان", "كيد اللص"] },
  { kind: "emoji", display: "🔫🕶️🎌", meta: { category: "أنمي" }, accepted: ["بلاك لاغون"] },
  { kind: "emoji", display: "🚬🍸🎷", meta: { category: "أنمي" }, accepted: ["بكانو"] },
  { kind: "emoji", display: "🎃👻🏫", meta: { category: "أنمي" }, accepted: ["أساسينيشن كلاسروم", "الفصل القاتل"] },
  { kind: "emoji", display: "🧟🏫🎌", meta: { category: "أنمي" }, accepted: ["مدرسة الموتى"] },
  { kind: "emoji", display: "🐈👦🏫", meta: { category: "أنمي" }, accepted: ["فروتس باسكت"] },
  { kind: "emoji", display: "🌌🚀👨‍🚀", meta: { category: "أنمي" }, accepted: ["بلانيتيس"] },
  { kind: "emoji", display: "🍛🐈🎌", meta: { category: "أنمي" }, accepted: ["غينتاما"] },
  { kind: "emoji", display: "🔥👊👨", meta: { category: "أنمي" }, accepted: ["آيس", "إيس"] },
  { kind: "emoji", display: "💰🎩🃏", meta: { category: "أنمي" }, accepted: ["كايجي"] },
  { kind: "emoji", display: "🚪🔑🗝️", meta: { category: "أنمي" }, accepted: ["سوزومي"] },
  { kind: "emoji", display: "🕷️🎣🃏", meta: { category: "أنمي" }, accepted: ["هنتر هنتر"] },
  { kind: "emoji", display: "🎣👦🏝️", meta: { category: "أنمي" }, accepted: ["غون"] },
  { kind: "emoji", display: "🃏🪡🖤", meta: { category: "أنمي" }, accepted: ["هيسوكا"] },
  { kind: "emoji", display: "🐕⚔️🌙", meta: { category: "أنمي" }, accepted: ["إنوياشا"] },
  { kind: "emoji", display: "🌙👗💫", meta: { category: "أنمي" }, accepted: ["سيلور مون"] },
  { kind: "emoji", display: "⚽👦🥅", meta: { category: "أنمي" }, accepted: ["انقضاض الشياطين", "اينازوما"] },
  { kind: "emoji", display: "🧽🍔🌊", meta: { category: "كرتون" }, accepted: ["سبونج بوب"] },
  { kind: "emoji", display: "🦁👑🌍", meta: { category: "كرتون" }, accepted: ["الأسد الملك"] },
  { kind: "emoji", display: "❄️👸⛄", meta: { category: "كرتون" }, accepted: ["ملكة الثلج", "فروزن"] },
  { kind: "emoji", display: "🐠🔍🌊", meta: { category: "كرتون" }, accepted: ["البحث عن نيمو", "نيمو"] },
  { kind: "emoji", display: "🐭🎩🎀", meta: { category: "كرتون" }, accepted: ["ميكي ماوس"] },
  { kind: "emoji", display: "🦆😡🎩", meta: { category: "كرتون" }, accepted: ["دونالد داك"] },
  { kind: "emoji", display: "🐱🐭🏠", meta: { category: "كرتون" }, accepted: ["توم وجيري"] },
  { kind: "emoji", display: "👨‍👩‍👧‍👦🟡🍩", meta: { category: "كرتون" }, accepted: ["سيمبسون", "ذا سيمبسونز"] },
  { kind: "emoji", display: "🚗⚡🏁", meta: { category: "كرتون" }, accepted: ["سيارات", "كارز"] },
  { kind: "emoji", display: "🤖🗑️🌌", meta: { category: "كرتون" }, accepted: ["وول-إي", "والي"] },
  { kind: "emoji", display: "🧸🤠🚀", meta: { category: "كرتون" }, accepted: ["حكاية لعبة", "توي ستوري"] },
  { kind: "emoji", display: "🐼🥋🍜", meta: { category: "كرتون" }, accepted: ["كونغ فو باندا"] },
  { kind: "emoji", display: "🦣🧊🐿️", meta: { category: "كرتون" }, accepted: ["العصر الجليدي"] },
  { kind: "emoji", display: "🐘👂🎪", meta: { category: "كرتون" }, accepted: ["دامبو"] },
  { kind: "emoji", display: "🧞🪔🐒", meta: { category: "كرتون" }, accepted: ["علاء الدين"] },
  { kind: "emoji", display: "🧜‍♀️🐟🔱", meta: { category: "كرتون" }, accepted: ["حورية البحر", "الحورية الصغيرة"] },
  { kind: "emoji", display: "🌹🦁🏰", meta: { category: "كرتون" }, accepted: ["الجميلة والوحش"] },
  { kind: "emoji", display: "👟🕛👸", meta: { category: "كرتون" }, accepted: ["سندريلا"] },
  { kind: "emoji", display: "🍎😴7️⃣", meta: { category: "كرتون" }, accepted: ["سنو وايت", "بياض الثلج"] },
  { kind: "emoji", display: "🦸‍♂️👨‍👩‍👧‍👦🦸‍♀️", meta: { category: "كرتون" }, accepted: ["الأبطال الخارقون"] },
  { kind: "emoji", display: "🐍🐻👦", meta: { category: "كرتون" }, accepted: ["كتاب الأدغال", "ماوكلي"] },
  { kind: "emoji", display: "🐴🌾🏜️", meta: { category: "كرتون" }, accepted: ["سبيريت"] },
  { kind: "emoji", display: "🐦💛😴", meta: { category: "كرتون" }, accepted: ["تويتي"] },
  { kind: "emoji", display: "🐰🥕🎯", meta: { category: "كرتون" }, accepted: ["باغز باني", "بقس"] },
  { kind: "emoji", display: "🦆💰🎩", meta: { category: "كرتون" }, accepted: ["العم دهب", "بطوط"] },
  { kind: "emoji", display: "🐶🕵️🔦", meta: { category: "كرتون" }, accepted: ["سكوبي دو"] },
  { kind: "emoji", display: "👨🐶🏠", meta: { category: "كرتون" }, accepted: ["شون الخروف"] },
  { kind: "emoji", display: "🐑🌾🐕", meta: { category: "كرتون" }, accepted: ["الخروف شون"] },
  { kind: "emoji", display: "🧀🐭🧠", meta: { category: "كرتون" }, accepted: ["بينكي والدماغ"] },
  { kind: "emoji", display: "🦇🌃🧑", meta: { category: "كرتون" }, accepted: ["باتمان الكرتوني"] },
  { kind: "emoji", display: "🧪👧👧👧", meta: { category: "كرتون" }, accepted: ["فتيات القوة"] },
  { kind: "emoji", display: "🧪🐶👦", meta: { category: "كرتون" }, accepted: ["ديكستر"] },
  { kind: "emoji", display: "🐿️🐿️🎵", meta: { category: "كرتون" }, accepted: ["السناجب", "الفين والسناجب"] },
  { kind: "emoji", display: "🐼🎋🐧", meta: { category: "كرتون" }, accepted: ["بندق", "بنات مدرسة"] },
  { kind: "emoji", display: "🚙🗣️🏁", meta: { category: "كرتون" }, accepted: ["البرق ماكوين"] },
  { kind: "emoji", display: "🧌🫏🏰", meta: { category: "كرتون" }, accepted: ["شريك"] },
  { kind: "emoji", display: "🐉👦🛡️", meta: { category: "كرتون" }, accepted: ["كيف تروض تنينك"] },
  { kind: "emoji", display: "🥋🐉🐒", meta: { category: "كرتون" }, accepted: ["كونغ فو باندا 2"] },
  { kind: "emoji", display: "🎈🏠👴", meta: { category: "كرتون" }, accepted: ["أب", "المنزل الطائر"] },
  { kind: "emoji", display: "🧠😊😢", meta: { category: "كرتون" }, accepted: ["قلبا وقالبا", "انسايد اوت"] },
  { kind: "emoji", display: "🐭👨‍🍳🍲", meta: { category: "كرتون" }, accepted: ["الفأر الطباخ", "راتاتوي"] },
  { kind: "emoji", display: "👹🚪👧", meta: { category: "كرتون" }, accepted: ["شركة المرعبين", "مونسترز"] },
  { kind: "emoji", display: "🎸💀🇲🇽", meta: { category: "كرتون" }, accepted: ["كوكو"] },
  { kind: "emoji", display: "🌊🛶🌺", meta: { category: "كرتون" }, accepted: ["موانا"] },
  { kind: "emoji", display: "🏹🐻🏴", meta: { category: "كرتون" }, accepted: ["بريف", "الشجاعة"] },
  { kind: "emoji", display: "🌸⚔️🇨🇳", meta: { category: "كرتون" }, accepted: ["مولان"] },
  { kind: "emoji", display: "🦌🌲🍂", meta: { category: "كرتون" }, accepted: ["بامبي"] },
  { kind: "emoji", display: "🐕🍝🕯️", meta: { category: "كرتون" }, accepted: ["القطة والكلب", "الشقية والشريد"] },
  { kind: "emoji", display: "🐕🐕1️⃣0️⃣1️⃣", meta: { category: "كرتون" }, accepted: ["101 كلب"] },
  { kind: "emoji", display: "🧚👦⏰", meta: { category: "كرتون" }, accepted: ["بيتر بان"] },
  { kind: "emoji", display: "🪵👃🐋", meta: { category: "كرتون" }, accepted: ["بينوكيو"] },
  { kind: "emoji", display: "🐸👸💋", meta: { category: "كرتون" }, accepted: ["الأميرة والضفدع"] },
  { kind: "emoji", display: "💇‍♀️🏰🏮", meta: { category: "كرتون" }, accepted: ["ربانزل", "تانغلد"] },
  { kind: "emoji", display: "🕵️🐕🤖", meta: { category: "كرتون" }, accepted: ["المفتش غادجيت"] },
  { kind: "emoji", display: "🧀🐭🐱", meta: { category: "كرتون" }, accepted: ["إيتشي وسكراتشي"] },
  { kind: "emoji", display: "🟦🧒🏫", meta: { category: "كرتون" }, accepted: ["شين شان"] },
  { kind: "emoji", display: "🤖🐱🚪", meta: { category: "كرتون" }, accepted: ["عبقور", "دورايمون"] },
  { kind: "emoji", display: "🍕🐢🥷", meta: { category: "كرتون" }, accepted: ["سلاحف النينجا"] },
  { kind: "emoji", display: "💪🥬⚓", meta: { category: "كرتون" }, accepted: ["باباي"] },
  { kind: "emoji", display: "🦸‍♂️🟥🔵", meta: { category: "كرتون" }, accepted: ["سوبرمان الكرتوني"] },
  { kind: "emoji", display: "🕷️🧑🎬", meta: { category: "كرتون" }, accepted: ["سبايدرمان الكرتوني"] },
  { kind: "emoji", display: "🚗🤖🔧", meta: { category: "كرتون" }, accepted: ["المتحولون", "ترانسفورمرز"] },
  { kind: "emoji", display: "🦖🚗👨", meta: { category: "كرتون" }, accepted: ["فلينستون", "عائلة فلينستون"] },
  { kind: "emoji", display: "🚀🤖👨‍👩‍👧", meta: { category: "كرتون" }, accepted: ["جيتسونز"] },
  { kind: "emoji", display: "🐻🧺🌲", meta: { category: "كرتون" }, accepted: ["الدب يوغي"] },
  { kind: "emoji", display: "🐶🎈🏠", meta: { category: "كرتون" }, accepted: ["سنوبي"] },
  { kind: "emoji", display: "🐥🐤🌽", meta: { category: "كرتون" }, accepted: ["كرتون المزرعة", "الدجاجة الصغيرة"] },
  { kind: "emoji", display: "👦🐕🌳", meta: { category: "كرتون" }, accepted: ["تان تان", "تان تان ومغامراته"] },
  { kind: "emoji", display: "👦🏝️🐒", meta: { category: "كرتون" }, accepted: ["طرزان"] },
  { kind: "emoji", display: "🌳🐒🍌", meta: { category: "كرتون" }, accepted: ["جورج فضولي"] },
  { kind: "emoji", display: "🐰🥚🎨", meta: { category: "كرتون" }, accepted: ["بيتر الأرنب"] },
  { kind: "emoji", display: "🚒👨‍🚒🐈", meta: { category: "كرتون" }, accepted: ["سام رجل الإطفاء"] },
  { kind: "emoji", display: "🚂🚃😄", meta: { category: "كرتون" }, accepted: ["توماس القطار"] },
  { kind: "emoji", display: "🐷👨‍👩‍👧🌧️", meta: { category: "كرتون" }, accepted: ["بيبا بيغ"] },
  { kind: "emoji", display: "🧱🟨🏗️", meta: { category: "كرتون" }, accepted: ["بوب البنّاء"] },
  { kind: "emoji", display: "🐶🚁🎒", meta: { category: "كرتون" }, accepted: ["باو باترول"] },
  { kind: "emoji", display: "👶🍼🕵️", meta: { category: "كرتون" }, accepted: ["الطفل الزعيم", "بيبي بوس"] },
  { kind: "emoji", display: "🐻👧🌲", meta: { category: "كرتون" }, accepted: ["ماشا والدب"] },
  { kind: "emoji", display: "🐸🎩🎭", meta: { category: "كرتون" }, accepted: ["المابت", "العرائس"] },
  { kind: "emoji", display: "👺⚔️🐉", meta: { category: "كرتون" }, accepted: ["أفاتار آخر مسخر للهواء"] },
  { kind: "emoji", display: "🌊🌪️🔥", meta: { category: "كرتون" }, accepted: ["آنغ", "أفاتار"] },
  { kind: "emoji", display: "🧊🐧☃️", meta: { category: "كرتون" }, accepted: ["بينغو", "البطريق"] },
  { kind: "emoji", display: "🐧🐧🎩", meta: { category: "كرتون" }, accepted: ["بطاريق مدغشقر"] },
  { kind: "emoji", display: "🦓🦁🌴", meta: { category: "كرتون" }, accepted: ["مدغشقر"] },
  { kind: "emoji", display: "🐝🎬🍯", meta: { category: "كرتون" }, accepted: ["فيلم النحلة"] },
  { kind: "emoji", display: "🐜🌿🐛", meta: { category: "كرتون" }, accepted: ["حياة حشرة", "باغز لايف"] },
  { kind: "emoji", display: "🐰👮🦊", meta: { category: "كرتون" }, accepted: ["زوتوبيا"] },
  { kind: "emoji", display: "🎤🐨🎶", meta: { category: "كرتون" }, accepted: ["سينغ"] },
  { kind: "emoji", display: "🌻🤖🏥", meta: { category: "كرتون" }, accepted: ["بيغ هيرو 6"] },
  { kind: "emoji", display: "🕶️🍌🟡", meta: { category: "كرتون" }, accepted: ["المينيونز"] },
  { kind: "emoji", display: "🌙🚀🧑‍🦲", meta: { category: "كرتون" }, accepted: ["أنا الحقير", "ديسبكبل مي"] },
  { kind: "emoji", display: "🦸🟦🟥", meta: { category: "كرتون" }, accepted: ["الرجل الوطواط الصغير"] },
  { kind: "emoji", display: "🐺🐑🌾", meta: { category: "كرتون" }, accepted: ["الذئب والخراف"] },
  { kind: "emoji", display: "🦊🐔🌾", meta: { category: "كرتون" }, accepted: ["كليلة ودمنة"] },
  { kind: "emoji", display: "🕌📖👦", meta: { category: "كرتون" }, accepted: ["افتح يا سمسم"] },
  { kind: "emoji", display: "🧒🏫🎒", meta: { category: "كرتون" }, accepted: ["مدرسة الحافلة السحرية"] },
  { kind: "emoji", display: "🐶🐱🏙️", meta: { category: "كرتون" }, accepted: ["الحياة السرية للحيوانات الأليفة"] },
  { kind: "emoji", display: "🦕👦🌋", meta: { category: "كرتون" }, accepted: ["الديناصور الطيب"] },
  { kind: "emoji", display: "🟢👹🏰", meta: { category: "كرتون" }, accepted: ["شريك 2"] },
  { kind: "emoji", display: "🐈👢⚔️", meta: { category: "كرتون" }, accepted: ["القط ذو الحذاء"] },
  { kind: "emoji", display: "🩺💊🏥", meta: { category: "مهنة" }, accepted: ["طبيب"] },
  { kind: "emoji", display: "📐🏗️👷", meta: { category: "مهنة" }, accepted: ["مهندس"] },
  { kind: "emoji", display: "📚🧑‍🏫🏫", meta: { category: "مهنة" }, accepted: ["معلم", "مدرس"] },
  { kind: "emoji", display: "🚓🚨👮", meta: { category: "مهنة" }, accepted: ["شرطي"] },
  { kind: "emoji", display: "🔥🚒💦", meta: { category: "مهنة" }, accepted: ["رجل إطفاء", "إطفائي"] },
  { kind: "emoji", display: "🍳👨‍🍳🥘", meta: { category: "مهنة" }, accepted: ["طباخ", "شيف"] },
  { kind: "emoji", display: "✈️🧑‍✈️🛫", meta: { category: "مهنة" }, accepted: ["طيار"] },
  { kind: "emoji", display: "💻⌨️🐞", meta: { category: "مهنة" }, accepted: ["مبرمج"] },
  { kind: "emoji", display: "⚖️📜👔", meta: { category: "مهنة" }, accepted: ["محامي"] },
  { kind: "emoji", display: "💉🏥👩‍⚕️", meta: { category: "مهنة" }, accepted: ["ممرضة", "ممرض"] },
  { kind: "emoji", display: "✂️💇🪒", meta: { category: "مهنة" }, accepted: ["حلاق"] },
  { kind: "emoji", display: "🪚🪵🔨", meta: { category: "مهنة" }, accepted: ["نجار"] },
  { kind: "emoji", display: "🔧🚿💧", meta: { category: "مهنة" }, accepted: ["سباك"] },
  { kind: "emoji", display: "💡⚡🔌", meta: { category: "مهنة" }, accepted: ["كهربائي"] },
  { kind: "emoji", display: "🌾🚜🐄", meta: { category: "مهنة" }, accepted: ["مزارع", "فلاح"] },
  { kind: "emoji", display: "📸🖼️📷", meta: { category: "مهنة" }, accepted: ["مصور"] },
  { kind: "emoji", display: "🎤📺🗞️", meta: { category: "مهنة" }, accepted: ["مذيع"] },
  { kind: "emoji", display: "💰🧮📊", meta: { category: "مهنة" }, accepted: ["محاسب"] },
  { kind: "emoji", display: "🐟🎣⛵", meta: { category: "مهنة" }, accepted: ["صياد"] },
  { kind: "emoji", display: "🚕🛣️🧑", meta: { category: "مهنة" }, accepted: ["سائق تاكسي", "سائق"] },
  { kind: "emoji", display: "💊🏪🧑‍⚕️", meta: { category: "مهنة" }, accepted: ["صيدلي"] },
  { kind: "emoji", display: "🎨🖌️🖼️", meta: { category: "مهنة" }, accepted: ["رسام"] },
  { kind: "emoji", display: "🧵👗✂️", meta: { category: "مهنة" }, accepted: ["خياط"] },
  { kind: "emoji", display: "🚀🌌🧑‍🚀", meta: { category: "مهنة" }, accepted: ["رائد فضاء"] },
  { kind: "emoji", display: "🦷🪥🪑", meta: { category: "مهنة" }, accepted: ["طبيب أسنان"] },
  { kind: "emoji", display: "👁️👓🔬", meta: { category: "مهنة" }, accepted: ["طبيب عيون"] },
  { kind: "emoji", display: "🐕🐈🩺", meta: { category: "مهنة" }, accepted: ["طبيب بيطري", "بيطري"] },
  { kind: "emoji", display: "🧠🛋️🗣️", meta: { category: "مهنة" }, accepted: ["طبيب نفسي"] },
  { kind: "emoji", display: "🚑🚨🩹", meta: { category: "مهنة" }, accepted: ["مسعف"] },
  { kind: "emoji", display: "🔬🧪🥼", meta: { category: "مهنة" }, accepted: ["عالم", "باحث"] },
  { kind: "emoji", display: "📖🗣️🌍", meta: { category: "مهنة" }, accepted: ["مترجم"] },
  { kind: "emoji", display: "📰🖊️🗞️", meta: { category: "مهنة" }, accepted: ["صحفي"] },
  { kind: "emoji", display: "📕📗🏛️", meta: { category: "مهنة" }, accepted: ["أمين مكتبة"] },
  { kind: "emoji", display: "🏛️⚖️🔨", meta: { category: "مهنة" }, accepted: ["قاضي"] },
  { kind: "emoji", display: "🕌🎙️🕋", meta: { category: "مهنة" }, accepted: ["إمام", "مؤذن"] },
  { kind: "emoji", display: "🥖🔥👨‍🍳", meta: { category: "مهنة" }, accepted: ["خباز"] },
  { kind: "emoji", display: "🥩🔪🧊", meta: { category: "مهنة" }, accepted: ["جزار", "لحام"] },
  { kind: "emoji", display: "☕🥛🧑‍🍳", meta: { category: "مهنة" }, accepted: ["باريستا"] },
  { kind: "emoji", display: "🍽️🧾🏃", meta: { category: "مهنة" }, accepted: ["نادل"] },
  { kind: "emoji", display: "🏨🔑🛎️", meta: { category: "مهنة" }, accepted: ["موظف استقبال"] },
  { kind: "emoji", display: "🧹🧽🪣", meta: { category: "مهنة" }, accepted: ["عامل نظافة"] },
  { kind: "emoji", display: "🚚📦🏃", meta: { category: "مهنة" }, accepted: ["عامل توصيل", "دليفري"] },
  { kind: "emoji", display: "✉️📮🚲", meta: { category: "مهنة" }, accepted: ["ساعي البريد"] },
  { kind: "emoji", display: "🏦💵🧾", meta: { category: "مهنة" }, accepted: ["موظف بنك", "صراف"] },
  { kind: "emoji", display: "📈💹💼", meta: { category: "مهنة" }, accepted: ["محلل مالي"] },
  { kind: "emoji", display: "🏠🔑📝", meta: { category: "مهنة" }, accepted: ["وسيط عقاري"] },
  { kind: "emoji", display: "🛒🏷️🧾", meta: { category: "مهنة" }, accepted: ["بائع", "كاشير"] },
  { kind: "emoji", display: "🚗🔧🛠️", meta: { category: "مهنة" }, accepted: ["ميكانيكي"] },
  { kind: "emoji", display: "🚌🛣️🧑", meta: { category: "مهنة" }, accepted: ["سائق حافلة"] },
  { kind: "emoji", display: "🚆🛤️🎫", meta: { category: "مهنة" }, accepted: ["سائق قطار"] },
  { kind: "emoji", display: "🚢⚓🧭", meta: { category: "مهنة" }, accepted: ["ربان سفينة", "بحار"] },
  { kind: "emoji", display: "🛡️👮📹", meta: { category: "مهنة" }, accepted: ["حارس أمن"] },
  { kind: "emoji", display: "🪖🔫🎖️", meta: { category: "مهنة" }, accepted: ["جندي", "عسكري"] },
  { kind: "emoji", display: "🕵️🔍🧩", meta: { category: "مهنة" }, accepted: ["محقق"] },
  { kind: "emoji", display: "⚽🥅🏆", meta: { category: "مهنة" }, accepted: ["لاعب كرة قدم"] },
  { kind: "emoji", display: "🏋️💪📋", meta: { category: "مهنة" }, accepted: ["مدرب رياضي"] },
  { kind: "emoji", display: "🎬🎥📢", meta: { category: "مهنة" }, accepted: ["مخرج"] },
  { kind: "emoji", display: "🎭🎤🌟", meta: { category: "مهنة" }, accepted: ["ممثل"] },
  { kind: "emoji", display: "🎵🎸🎤", meta: { category: "مهنة" }, accepted: ["مغني", "موسيقي"] },
  { kind: "emoji", display: "✍️📖💭", meta: { category: "مهنة" }, accepted: ["كاتب", "مؤلف"] },
  { kind: "emoji", display: "📝🌙🪶", meta: { category: "مهنة" }, accepted: ["شاعر"] },
  { kind: "emoji", display: "🖥️🎨🖱️", meta: { category: "مهنة" }, accepted: ["مصمم جرافيك"] },
  { kind: "emoji", display: "🏢📐✏️", meta: { category: "مهنة" }, accepted: ["مهندس معماري"] },
  { kind: "emoji", display: "🗿🔨🪨", meta: { category: "مهنة" }, accepted: ["نحات"] },
  { kind: "emoji", display: "🖋️📜🕌", meta: { category: "مهنة" }, accepted: ["خطاط"] },
  { kind: "emoji", display: "💅💄💇‍♀️", meta: { category: "مهنة" }, accepted: ["خبيرة تجميل"] },
  { kind: "emoji", display: "👗📏🧷", meta: { category: "مهنة" }, accepted: ["مصمم أزياء"] },
  { kind: "emoji", display: "🌱🌸✂️", meta: { category: "مهنة" }, accepted: ["بستاني"] },
  { kind: "emoji", display: "🐝🍯🧤", meta: { category: "مهنة" }, accepted: ["نحّال"] },
  { kind: "emoji", display: "🐑🌾🦯", meta: { category: "مهنة" }, accepted: ["راعي"] },
  { kind: "emoji", display: "⛏️🪨🔦", meta: { category: "مهنة" }, accepted: ["عامل منجم"] },
  { kind: "emoji", display: "🛢️🔥🏗️", meta: { category: "مهنة" }, accepted: ["عامل نفط"] },
  { kind: "emoji", display: "🧱🏗️👷", meta: { category: "مهنة" }, accepted: ["عامل بناء", "بنّاء"] },
  { kind: "emoji", display: "🔥⚒️🧲", meta: { category: "مهنة" }, accepted: ["حداد"] },
  { kind: "emoji", display: "🪟🧽🏢", meta: { category: "مهنة" }, accepted: ["منظف واجهات"] },
  { kind: "emoji", display: "🛗🔧🏢", meta: { category: "مهنة" }, accepted: ["فني مصاعد"] },
  { kind: "emoji", display: "❄️🔧🌬️", meta: { category: "مهنة" }, accepted: ["فني تكييف"] },
  { kind: "emoji", display: "📡🛠️📶", meta: { category: "مهنة" }, accepted: ["فني اتصالات"] },
  { kind: "emoji", display: "🖨️📄🖥️", meta: { category: "مهنة" }, accepted: ["فني طباعة"] },
  { kind: "emoji", display: "🧾📦🏭", meta: { category: "مهنة" }, accepted: ["أمين مستودع"] },
  { kind: "emoji", display: "🚦🛣️👷", meta: { category: "مهنة" }, accepted: ["شرطي مرور"] },
  { kind: "emoji", display: "🛂🛃🧳", meta: { category: "مهنة" }, accepted: ["موظف جوازات"] },
  { kind: "emoji", display: "🧳✈️😊", meta: { category: "مهنة" }, accepted: ["مضيف طيران"] },
  { kind: "emoji", display: "🗺️🚌📢", meta: { category: "مهنة" }, accepted: ["مرشد سياحي"] },
  { kind: "emoji", display: "🎪🤹🎈", meta: { category: "مهنة" }, accepted: ["مهرج"] },
  { kind: "emoji", display: "🎻🎼🎩", meta: { category: "مهنة" }, accepted: ["عازف"] },
  { kind: "emoji", display: "🕺🎶💃", meta: { category: "مهنة" }, accepted: ["راقص"] },
  { kind: "emoji", display: "🧗⛰️🪢", meta: { category: "مهنة" }, accepted: ["مرشد جبلي"] },
  { kind: "emoji", display: "🏊🛟👀", meta: { category: "مهنة" }, accepted: ["منقذ سباحة"] },
  { kind: "emoji", display: "🚁🌊🆘", meta: { category: "مهنة" }, accepted: ["رجل إنقاذ"] },
  { kind: "emoji", display: "🧑‍⚖️🖊️📑", meta: { category: "مهنة" }, accepted: ["كاتب عدل"] },
  { kind: "emoji", display: "👶🍼🧸", meta: { category: "مهنة" }, accepted: ["مربية أطفال"] },
  { kind: "emoji", display: "🧓🦯🤝", meta: { category: "مهنة" }, accepted: ["مقدم رعاية"] },
  { kind: "emoji", display: "🧪💊🏭", meta: { category: "مهنة" }, accepted: ["مهندس كيميائي"] },
  { kind: "emoji", display: "🌍🪨🔨", meta: { category: "مهنة" }, accepted: ["جيولوجي"] },
  { kind: "emoji", display: "🌦️📡🗺️", meta: { category: "مهنة" }, accepted: ["خبير أرصاد"] },
  { kind: "emoji", display: "🔭🌌📝", meta: { category: "مهنة" }, accepted: ["فلكي"] },
  { kind: "emoji", display: "🧬🔬🧫", meta: { category: "مهنة" }, accepted: ["عالم أحياء"] },
  { kind: "emoji", display: "🖥️🔒🛡️", meta: { category: "مهنة" }, accepted: ["خبير أمن سيبراني"] },
  { kind: "emoji", display: "📱💡🚀", meta: { category: "مهنة" }, accepted: ["رائد أعمال"] },
  { kind: "emoji", display: "🕷️🧑🕸️", meta: { category: "فيلم" }, accepted: ["الرجل العنكبوت", "سبايدرمان"] },
  { kind: "emoji", display: "🦇🌃🖤", meta: { category: "فيلم" }, accepted: ["باتمان", "رجل الوطواط"] },
  { kind: "emoji", display: "🔴🧲🪖", meta: { category: "فيلم" }, accepted: ["ايرون مان", "الرجل الحديدي"] },
  { kind: "emoji", display: "🏴‍☠️🦜⚓", meta: { category: "فيلم" }, accepted: ["قراصنة الكاريبي"] },
  { kind: "emoji", display: "🚢🧊💔", meta: { category: "فيلم" }, accepted: ["تايتانيك"] },
  { kind: "emoji", display: "🦖🏝️🧬", meta: { category: "فيلم" }, accepted: ["الحديقة الجوراسية", "جوراسيك بارك"] },
  { kind: "emoji", display: "👻🚫🔫", meta: { category: "فيلم" }, accepted: ["مصيدة الأشباح", "غوستباسترز"] },
  { kind: "emoji", display: "🧙‍♂️💍🌋", meta: { category: "فيلم" }, accepted: ["سيد الخواتم"] },
  { kind: "emoji", display: "⚡🧙🏰", meta: { category: "فيلم" }, accepted: ["هاري بوتر"] },
  { kind: "emoji", display: "🟦👽🌴", meta: { category: "فيلم" }, accepted: ["أفاتار"] },
  { kind: "emoji", display: "🚗💨👨‍👨‍👦", meta: { category: "فيلم" }, accepted: ["فاست اند فيوريس", "السرعة والغضب"] },
  { kind: "emoji", display: "🤖🔫🕶️", meta: { category: "فيلم" }, accepted: ["ترمينيتور", "المدمر"] },
  { kind: "emoji", display: "🕶️💊💻", meta: { category: "فيلم" }, accepted: ["ماتريكس"] },
  { kind: "emoji", display: "⭐⚔️🌌", meta: { category: "فيلم" }, accepted: ["حرب النجوم", "ستار وورز"] },
  { kind: "emoji", display: "🦈🌊🩸", meta: { category: "فيلم" }, accepted: ["الفك المفترس"] },
  { kind: "emoji", display: "🦍🏙️✈️", meta: { category: "فيلم" }, accepted: ["كينغ كونغ"] },
  { kind: "emoji", display: "🧟🚄🇰🇷", meta: { category: "فيلم" }, accepted: ["قطار إلى بوسان"] },
  { kind: "emoji", display: "🌽🌌⏳", meta: { category: "فيلم" }, accepted: ["إنترستيلر"] },
  { kind: "emoji", display: "🎭🃏🤡", meta: { category: "فيلم" }, accepted: ["جوكر"] },
  { kind: "emoji", display: "💤🌀🏙️", meta: { category: "فيلم" }, accepted: ["إنسبشن"] },
  { kind: "emoji", display: "🥊🇺🇸🏆", meta: { category: "فيلم" }, accepted: ["روكي"] },
  { kind: "emoji", display: "🐜🦸‍♂️🔬", meta: { category: "فيلم" }, accepted: ["الرجل النملة"] },
  { kind: "emoji", display: "🧤💎🫰", meta: { category: "فيلم" }, accepted: ["أفنجرز", "المنتقمون"] },
  { kind: "emoji", display: "🛡️⭐🇺🇸", meta: { category: "فيلم" }, accepted: ["كابتن أمريكا"] },
  { kind: "emoji", display: "🔨⚡🇳🇴", meta: { category: "فيلم" }, accepted: ["ثور"] },
  { kind: "emoji", display: "💚😡💪", meta: { category: "فيلم" }, accepted: ["هالك"] },
  { kind: "emoji", display: "🐆🖤🌍", meta: { category: "فيلم" }, accepted: ["بلاك بانثر"] },
  { kind: "emoji", display: "🕶️👽🔫", meta: { category: "فيلم" }, accepted: ["رجال بالأسود", "مين إن بلاك"] },
  { kind: "emoji", display: "🦸‍♂️🟥🦸", meta: { category: "فيلم" }, accepted: ["سوبرمان"] },
  { kind: "emoji", display: "🦇🃏🌆", meta: { category: "فيلم" }, accepted: ["الفارس الأسود"] },
  { kind: "emoji", display: "🧜‍♀️🎬🌊", meta: { category: "فيلم" }, accepted: ["أكوامان"] },
  { kind: "emoji", display: "👸⚔️🪢", meta: { category: "فيلم" }, accepted: ["وندر وومن"] },
  { kind: "emoji", display: "🐭🎩🎥", meta: { category: "فيلم" }, accepted: ["ديزني", "والت ديزني"] },
  { kind: "emoji", display: "🎩🍫🏭", meta: { category: "فيلم" }, accepted: ["تشارلي ومصنع الشوكولاتة"] },
  { kind: "emoji", display: "🏠👦🦹", meta: { category: "فيلم" }, accepted: ["وحدي في المنزل", "هوم الون"] },
  { kind: "emoji", display: "🎁🎅🦌", meta: { category: "فيلم" }, accepted: ["الرحلة القطبية"] },
  { kind: "emoji", display: "🐷🕷️🌾", meta: { category: "فيلم" }, accepted: ["شبكة شارلوت"] },
  { kind: "emoji", display: "🕰️🚗⚡", meta: { category: "فيلم" }, accepted: ["العودة إلى المستقبل"] },
  { kind: "emoji", display: "👽🚲🌕", meta: { category: "فيلم" }, accepted: ["إي تي"] },
  { kind: "emoji", display: "🤠👽🏜️", meta: { category: "فيلم" }, accepted: ["كاوبويز وأليينز"] },
  { kind: "emoji", display: "🏜️🐛🌌", meta: { category: "فيلم" }, accepted: ["ديون", "كثيب"] },
  { kind: "emoji", display: "🚀🌕👨‍🚀", meta: { category: "فيلم" }, accepted: ["أبولو 13"] },
  { kind: "emoji", display: "🪐🥔🧑‍🚀", meta: { category: "فيلم" }, accepted: ["المريخي", "ذا مارشن"] },
  { kind: "emoji", display: "🌌🛰️😵", meta: { category: "فيلم" }, accepted: ["غرافيتي", "الجاذبية"] },
  { kind: "emoji", display: "🦇🧛🏰", meta: { category: "فيلم" }, accepted: ["دراكولا"] },
  { kind: "emoji", display: "⚡🧟🧪", meta: { category: "فيلم" }, accepted: ["فرانكشتاين"] },
  { kind: "emoji", display: "🪦🔔😱", meta: { category: "فيلم" }, accepted: ["المومياء"] },
  { kind: "emoji", display: "🚪🔴🎈", meta: { category: "فيلم" }, accepted: ["إت", "المهرج"] },
  { kind: "emoji", display: "🔪🎭😱", meta: { category: "فيلم" }, accepted: ["سكريم"] },
  { kind: "emoji", display: "🧩🔪🎥", meta: { category: "فيلم" }, accepted: ["سو", "المنشار"] },
  { kind: "emoji", display: "👧🕯️🌀", meta: { category: "فيلم" }, accepted: ["الشعوذة", "ذا كونجيورينغ"] },
  { kind: "emoji", display: "👵🏚️🚪", meta: { category: "فيلم" }, accepted: ["الحس السادس"] },
  { kind: "emoji", display: "🌊🏄🦈", meta: { category: "فيلم" }, accepted: ["المد الأزرق"] },
  { kind: "emoji", display: "🌪️🐄🚜", meta: { category: "فيلم" }, accepted: ["تويستر", "الإعصار"] },
  { kind: "emoji", display: "🌋🔥🏘️", meta: { category: "فيلم" }, accepted: ["دانتيز بيك", "البركان"] },
  { kind: "emoji", display: "🧊🗽❄️", meta: { category: "فيلم" }, accepted: ["اليوم التالي بعد الغد"] },
  { kind: "emoji", display: "🏝️⚽🧔", meta: { category: "فيلم" }, accepted: ["منبوذ", "كاست أواي"] },
  { kind: "emoji", display: "🍫🏃🪶", meta: { category: "فيلم" }, accepted: ["فورست غامب"] },
  { kind: "emoji", display: "🪖🇺🇸🏖️", meta: { category: "فيلم" }, accepted: ["إنقاذ الجندي رايان"] },
  { kind: "emoji", display: "🎹🎻🚢", meta: { category: "فيلم" }, accepted: ["عازف البيانو"] },
  { kind: "emoji", display: "💍⚔️👑", meta: { category: "فيلم" }, accepted: ["الملك آرثر"] },
  { kind: "emoji", display: "🏹🌲💚", meta: { category: "فيلم" }, accepted: ["روبن هود"] },
  { kind: "emoji", display: "🏛️⚔️🦁", meta: { category: "فيلم" }, accepted: ["غلادييتر", "المصارع"] },
  { kind: "emoji", display: "🛡️🏛️3️⃣0️⃣0️⃣", meta: { category: "فيلم" }, accepted: ["300"] },
  { kind: "emoji", display: "🐴🏛️⚔️", meta: { category: "فيلم" }, accepted: ["طروادة"] },
  { kind: "emoji", display: "🏜️🐫🗡️", meta: { category: "فيلم" }, accepted: ["لورنس العرب"] },
  { kind: "emoji", display: "🎥🇪🇬🧕", meta: { category: "فيلم" }, accepted: ["الرسالة"] },
  { kind: "emoji", display: "🦁🏜️⚔️", meta: { category: "فيلم" }, accepted: ["أسد الصحراء", "عمر المختار"] },
  { kind: "emoji", display: "🚕🌃🇪🇬", meta: { category: "فيلم" }, accepted: ["تاكسي"] },
  { kind: "emoji", display: "🎬😂🇪🇬", meta: { category: "فيلم" }, accepted: ["الناظر"] },
  { kind: "emoji", display: "🕶️😂🍿", meta: { category: "فيلم" }, accepted: ["الليمبي"] },
  { kind: "emoji", display: "🏫😂👨‍🏫", meta: { category: "فيلم" }, accepted: ["مدرسة المشاغبين"] },
  { kind: "emoji", display: "🎢🎭😂", meta: { category: "فيلم" }, accepted: ["الكيف"] },
  { kind: "emoji", display: "🎤🎵🎬", meta: { category: "فيلم" }, accepted: ["بوهيميان رابسودي"] },
  { kind: "emoji", display: "🎪🎩🐘", meta: { category: "فيلم" }, accepted: ["الاستعراضي", "غريتست شومان"] },
  { kind: "emoji", display: "💃🎷🌃", meta: { category: "فيلم" }, accepted: ["لا لا لاند"] },
  { kind: "emoji", display: "🥁🩸🎶", meta: { category: "فيلم" }, accepted: ["ويبلاش"] },
  { kind: "emoji", display: "🎻🚢🎹", meta: { category: "فيلم" }, accepted: ["أسطورة 1900"] },
  { kind: "emoji", display: "🐶🚪⌛", meta: { category: "فيلم" }, accepted: ["هاتشي"] },
  { kind: "emoji", display: "🐕🏔️🐺", meta: { category: "فيلم" }, accepted: ["نداء البرية"] },
  { kind: "emoji", display: "🐴🏇🏆", meta: { category: "فيلم" }, accepted: ["سي بيسكيت"] },
  { kind: "emoji", display: "🐒🌉🧬", meta: { category: "فيلم" }, accepted: ["كوكب القردة"] },
  { kind: "emoji", display: "🐺🌕🩸", meta: { category: "فيلم" }, accepted: ["الرجل الذئب"] },
  { kind: "emoji", display: "🧛🌑💘", meta: { category: "فيلم" }, accepted: ["توايلايت"] },
  { kind: "emoji", display: "🏹🔥🎯", meta: { category: "فيلم" }, accepted: ["مباريات الجوع", "هانغر غيمز"] },
  { kind: "emoji", display: "🧱🏃🚪", meta: { category: "فيلم" }, accepted: ["ذا ميز رنر"] },
  { kind: "emoji", display: "🕳️🚀🌀", meta: { category: "فيلم" }, accepted: ["تينيت"] },
  { kind: "emoji", display: "🥷🌆🔫", meta: { category: "فيلم" }, accepted: ["جون ويك"] },
  { kind: "emoji", display: "🎯🕶️🔫", meta: { category: "فيلم" }, accepted: ["جيمس بوند"] },
  { kind: "emoji", display: "🕵️🎭🧨", meta: { category: "فيلم" }, accepted: ["المهمة المستحيلة"] },
  { kind: "emoji", display: "💼🥋🇺🇸", meta: { category: "فيلم" }, accepted: ["بورن", "ذا بورن آيدنتتي"] },
  { kind: "emoji", display: "👶🍼😂", meta: { category: "فيلم" }, accepted: ["بيبي بوس الفيلم"] },
  { kind: "emoji", display: "🚙🐒🎪", meta: { category: "فيلم" }, accepted: ["ليل ومدغشقر"] },
  { kind: "emoji", display: "🍕🐢🥷", meta: { category: "فيلم" }, accepted: ["سلاحف النينجا الفيلم"] },
  { kind: "emoji", display: "⛏️🟩🎮", meta: { category: "فيلم" }, accepted: ["ماين كرافت الفيلم"] },
  { kind: "emoji", display: "🍄👨‍🔧🐢", meta: { category: "فيلم" }, accepted: ["سوبر ماريو"] },
  { kind: "emoji", display: "🦔💨💍", meta: { category: "فيلم" }, accepted: ["سونيك"] },
  { kind: "emoji", display: "⚡🐭🕵️", meta: { category: "فيلم" }, accepted: ["بوكيمون ديتكتيف بيكاتشو"] },
  { kind: "emoji", display: "👑🦁🎬", meta: { category: "فيلم" }, accepted: ["الأسد الملك الواقعي"] },
  { kind: "emoji", display: "🧞💙🪔", meta: { category: "فيلم" }, accepted: ["علاء الدين الواقعي"] },
  { kind: "emoji", display: "🐉❄️👑", meta: { category: "مسلسل" }, accepted: ["صراع العروش"] },
  { kind: "emoji", display: "🧪🎩💊", meta: { category: "مسلسل" }, accepted: ["بريكنغ باد"] },
  { kind: "emoji", display: "🦑🔴🟢", meta: { category: "مسلسل" }, accepted: ["لعبة الحبار"] },
  { kind: "emoji", display: "🎭🏦🇪🇸", meta: { category: "مسلسل" }, accepted: ["بيت الورق", "لا كاسا دي بابيل"] },
  { kind: "emoji", display: "🧟🔫🚶", meta: { category: "مسلسل" }, accepted: ["الموتى السائرون"] },
  { kind: "emoji", display: "👽🚲🔦", meta: { category: "مسلسل" }, accepted: ["أشياء غريبة", "سترينجر ثينغز"] },
  { kind: "emoji", display: "👑🇬🇧🏰", meta: { category: "مسلسل" }, accepted: ["ذا كراون"] },
  { kind: "emoji", display: "🎩🔪🏭", meta: { category: "مسلسل" }, accepted: ["بيكي بلايندرز"] },
  { kind: "emoji", display: "🏥🩺❤️", meta: { category: "مسلسل" }, accepted: ["غريز أناتومي"] },
  { kind: "emoji", display: "☕6️⃣🛋️", meta: { category: "مسلسل" }, accepted: ["فريندز", "الأصدقاء"] },
  { kind: "emoji", display: "🧠🤓🔬", meta: { category: "مسلسل" }, accepted: ["نظرية الانفجار العظيم"] },
  { kind: "emoji", display: "🕵️🇬🇧🎻", meta: { category: "مسلسل" }, accepted: ["شرلوك"] },
  { kind: "emoji", display: "⚔️🇹🇷🐺", meta: { category: "مسلسل" }, accepted: ["قيامة أرطغرل"] },
  { kind: "emoji", display: "🏜️🐪⚔️", meta: { category: "مسلسل" }, accepted: ["عمر"] },
  { kind: "emoji", display: "🏠😂🇰🇼", meta: { category: "مسلسل" }, accepted: ["درب الزلق"] },
  { kind: "emoji", display: "🕌🏘️🎬", meta: { category: "مسلسل" }, accepted: ["باب الحارة"] },
  { kind: "emoji", display: "🕶️🤵⚖️", meta: { category: "مسلسل" }, accepted: ["سوتس"] },
  { kind: "emoji", display: "💰🚤🏦", meta: { category: "مسلسل" }, accepted: ["أوزارك"] },
  { kind: "emoji", display: "🎮🍄🧟", meta: { category: "مسلسل" }, accepted: ["ذا لاست أوف أس"] },
  { kind: "emoji", display: "⚽😄🇺🇸", meta: { category: "مسلسل" }, accepted: ["تيد لاسو"] },
  { kind: "emoji", display: "🏝️✈️🔢", meta: { category: "مسلسل" }, accepted: ["لوست", "التائهون"] },
  { kind: "emoji", display: "🚬📺👔", meta: { category: "مسلسل" }, accepted: ["ماد مان"] },
  { kind: "emoji", display: "👨‍🍳🔪😰", meta: { category: "مسلسل" }, accepted: ["ذا بير"] },
  { kind: "emoji", display: "🧛🌑💘", meta: { category: "مسلسل" }, accepted: ["يوميات مصاص الدماء"] },
  { kind: "emoji", display: "⚖️🚗📞", meta: { category: "مسلسل" }, accepted: ["بيتر كول سول"] },
  { kind: "emoji", display: "👨‍👩‍👧🏝️💸", meta: { category: "مسلسل" }, accepted: ["الوريث", "سكسشن"] },
  { kind: "emoji", display: "👮🇺🇸🎥", meta: { category: "مسلسل" }, accepted: ["ذا واير"] },
  { kind: "emoji", display: "🖥️🕶️💻", meta: { category: "مسلسل" }, accepted: ["مستر روبوت"] },
  { kind: "emoji", display: "🖤🪞📱", meta: { category: "مسلسل" }, accepted: ["مرآة سوداء", "بلاك ميرور"] },
  { kind: "emoji", display: "🤖🤠🎡", meta: { category: "مسلسل" }, accepted: ["ويست وورلد"] },
  { kind: "emoji", display: "☢️🏭🇺🇦", meta: { category: "مسلسل" }, accepted: ["تشيرنوبل"] },
  { kind: "emoji", display: "🏛️🐎⚔️", meta: { category: "مسلسل" }, accepted: ["روما"] },
  { kind: "emoji", display: "⚓🐉👑", meta: { category: "مسلسل" }, accepted: ["بيت التنين"] },
  { kind: "emoji", display: "🧙💍🌋", meta: { category: "مسلسل" }, accepted: ["خواتم القوة"] },
  { kind: "emoji", display: "🗡️🐺🧙‍♂️", meta: { category: "مسلسل" }, accepted: ["ذا ويتشر"] },
  { kind: "emoji", display: "🛡️🪓⛵", meta: { category: "مسلسل" }, accepted: ["الفايكنج"] },
  { kind: "emoji", display: "🎓🔬👨‍🏫", meta: { category: "مسلسل" }, accepted: ["يونغ شيلدون"] },
  { kind: "emoji", display: "🏢📎😂", meta: { category: "مسلسل" }, accepted: ["ذا أوفيس"] },
  { kind: "emoji", display: "🌳🏛️😄", meta: { category: "مسلسل" }, accepted: ["باركس آند ريكرييشن"] },
  { kind: "emoji", display: "🍺🍕😂", meta: { category: "مسلسل" }, accepted: ["هاو آي ميت يور مذر"] },
  { kind: "emoji", display: "👩‍🍳🏠😂", meta: { category: "مسلسل" }, accepted: ["مودرن فاميلي"] },
  { kind: "emoji", display: "🧁👩🍽️", meta: { category: "مسلسل" }, accepted: ["تو بروك غيرلز"] },
  { kind: "emoji", display: "🚔😂🚨", meta: { category: "مسلسل" }, accepted: ["بروكلين ناين ناين"] },
  { kind: "emoji", display: "🎤🎶🏫", meta: { category: "مسلسل" }, accepted: ["غلي"] },
  { kind: "emoji", display: "🩰🎭🏫", meta: { category: "مسلسل" }, accepted: ["إيليت"] },
  { kind: "emoji", display: "🏫🖤📓", meta: { category: "مسلسل" }, accepted: ["غوسيب غيرل"] },
  { kind: "emoji", display: "🕵️🧬🔬", meta: { category: "مسلسل" }, accepted: ["سي إس آي"] },
  { kind: "emoji", display: "🧠🔎🕵️", meta: { category: "مسلسل" }, accepted: ["مايندهنتر"] },
  { kind: "emoji", display: "🚑🏥🚨", meta: { category: "مسلسل" }, accepted: ["إي آر", "غرفة الطوارئ"] },
  { kind: "emoji", display: "💊🩺🦯", meta: { category: "مسلسل" }, accepted: ["هاوس"] },
  { kind: "emoji", display: "👨‍⚖️🏛️📚", meta: { category: "مسلسل" }, accepted: ["بويستون ليغال"] },
  { kind: "emoji", display: "🕌📿🎬", meta: { category: "مسلسل" }, accepted: ["عمر بن عبد العزيز"] },
  { kind: "emoji", display: "🐪🏜️🎬", meta: { category: "مسلسل" }, accepted: ["الزير سالم"] },
  { kind: "emoji", display: "🏰🇸🇾⚔️", meta: { category: "مسلسل" }, accepted: ["صلاح الدين الأيوبي"] },
  { kind: "emoji", display: "🎬🇰🇼👨‍👩‍👧", meta: { category: "مسلسل" }, accepted: ["بيت بيوت"] },
  { kind: "emoji", display: "😂🇸🇦☕", meta: { category: "مسلسل" }, accepted: ["طاش ما طاش"] },
  { kind: "emoji", display: "🏠🇸🇦🎬", meta: { category: "مسلسل" }, accepted: ["العاصوف"] },
  { kind: "emoji", display: "👨‍👩‍👧🇪🇬🎬", meta: { category: "مسلسل" }, accepted: ["ليالي الحلمية"] },
  { kind: "emoji", display: "🏙️🇪🇬🎭", meta: { category: "مسلسل" }, accepted: ["رأفت الهجان"] },
  { kind: "emoji", display: "🏛️🇪🇬📚", meta: { category: "مسلسل" }, accepted: ["الجماعة"] },
  { kind: "emoji", display: "🕌🐪📖", meta: { category: "مسلسل" }, accepted: ["الحسن والحسين"] },
  { kind: "emoji", display: "🇹🇷🏰👑", meta: { category: "مسلسل" }, accepted: ["حريم السلطان"] },
  { kind: "emoji", display: "🇹🇷⚔️🐺", meta: { category: "مسلسل" }, accepted: ["المؤسس عثمان"] },
  { kind: "emoji", display: "🇹🇷💔🏙️", meta: { category: "مسلسل" }, accepted: ["العشق الممنوع"] },
  { kind: "emoji", display: "🇰🇷💘🪖", meta: { category: "مسلسل" }, accepted: ["هبوط اضطراري على الحب"] },
  { kind: "emoji", display: "🇰🇷👻🏫", meta: { category: "مسلسل" }, accepted: ["كل ما نحن"] },
  { kind: "emoji", display: "🇰🇷👑🏰", meta: { category: "مسلسل" }, accepted: ["مستر كوين"] },
  { kind: "emoji", display: "🇮🇳💃🎶", meta: { category: "مسلسل" }, accepted: ["مسلسل هندي"] },
  { kind: "emoji", display: "🧩🏫🖤", meta: { category: "مسلسل" }, accepted: ["وينزداي"] },
  { kind: "emoji", display: "🦇🍸🌃", meta: { category: "مسلسل" }, accepted: ["غوثام"] },
  { kind: "emoji", display: "⚡🏃🟥", meta: { category: "مسلسل" }, accepted: ["ذا فلاش"] },
  { kind: "emoji", display: "🏹🟩🎯", meta: { category: "مسلسل" }, accepted: ["آرو"] },
  { kind: "emoji", display: "🦸🟦🚀", meta: { category: "مسلسل" }, accepted: ["ذا بويز"] },
  { kind: "emoji", display: "🌌🚀🛸", meta: { category: "مسلسل" }, accepted: ["ذا إكسبانس"] },
  { kind: "emoji", display: "🖖🚀🌌", meta: { category: "مسلسل" }, accepted: ["ستار تريك"] },
  { kind: "emoji", display: "🤠⭐🪐", meta: { category: "مسلسل" }, accepted: ["ماندلوريان"] },
  { kind: "emoji", display: "🕰️🌀🚪", meta: { category: "مسلسل" }, accepted: ["لوكي"] },
  { kind: "emoji", display: "📺🏡🦸", meta: { category: "مسلسل" }, accepted: ["وانداVision", "واندا فيجن"] },
  { kind: "emoji", display: "🏹🎄🎯", meta: { category: "مسلسل" }, accepted: ["هوك آي"] },
  { kind: "emoji", display: "🐉🔥🏰", meta: { category: "مسلسل" }, accepted: ["ميرلين"] },
  { kind: "emoji", display: "🏴🍀⚔️", meta: { category: "مسلسل" }, accepted: ["أوتلاندر"] },
  { kind: "emoji", display: "👗💌🇬🇧", meta: { category: "مسلسل" }, accepted: ["بريدجرتون"] },
  { kind: "emoji", display: "🏡🇬🇧🫖", meta: { category: "مسلسل" }, accepted: ["داونتون آبي"] },
  { kind: "emoji", display: "🚓🔍🌫️", meta: { category: "مسلسل" }, accepted: ["ترو ديتكتيف"] },
  { kind: "emoji", display: "🪓🩸🏔️", meta: { category: "مسلسل" }, accepted: ["فارغو"] },
  { kind: "emoji", display: "📻🚬🎩", meta: { category: "مسلسل" }, accepted: ["بوردووك إمباير"] },
  { kind: "emoji", display: "🏈🏫🇺🇸", meta: { category: "مسلسل" }, accepted: ["فرايداي نايت لايتس"] },
  { kind: "emoji", display: "🎾🏆📺", meta: { category: "مسلسل" }, accepted: ["بريك بوينت"] },
  { kind: "emoji", display: "🏎️🏁📺", meta: { category: "مسلسل" }, accepted: ["درايف تو سرفايف"] },
  { kind: "emoji", display: "🍳🔥🏆", meta: { category: "مسلسل" }, accepted: ["ماستر شيف"] },
  { kind: "emoji", display: "🎤🪑🔄", meta: { category: "مسلسل" }, accepted: ["ذا فويس"] },
  { kind: "emoji", display: "⭐🎤🏆", meta: { category: "مسلسل" }, accepted: ["آراب آيدول"] },
  { kind: "emoji", display: "🎭😂🇱🇧", meta: { category: "مسلسل" }, accepted: ["كتير كبير"] },
  { kind: "emoji", display: "🏠👨‍👩‍👧🇱🇧", meta: { category: "مسلسل" }, accepted: ["الهيبة"] },
  { kind: "emoji", display: "🎬🕵️🇸🇾", meta: { category: "مسلسل" }, accepted: ["الولادة من الخاصرة"] },
  { kind: "emoji", display: "👨‍👩‍👧‍👦🏠😂", meta: { category: "مسلسل" }, accepted: ["فوق مستوى الشبهات"] },
  { kind: "emoji", display: "🚖🎬🇪🇬", meta: { category: "مسلسل" }, accepted: ["الاختيار"] },
  { kind: "emoji", display: "🧕🏡🎬", meta: { category: "مسلسل" }, accepted: ["بين السرايا"] },
  { kind: "emoji", display: "🎮🕹️📺", meta: { category: "مسلسل" }, accepted: ["أركين"] },
  { kind: "emoji", display: "🐰🕳️🌀", meta: { category: "مسلسل" }, accepted: ["دارك"] },
  { kind: "emoji", display: "🍎🌳🧠", meta: { category: "شخصية" }, accepted: ["نيوتن"] },
  { kind: "emoji", display: "👨‍🔬➗👅", meta: { category: "شخصية" }, accepted: ["أينشتاين"] },
  { kind: "emoji", display: "🍏📱🖤", meta: { category: "شخصية" }, accepted: ["ستيف جوبز"] },
  { kind: "emoji", display: "🚀🚗🐦", meta: { category: "شخصية" }, accepted: ["إيلون ماسك"] },
  { kind: "emoji", display: "⚽🇦🇷🐐", meta: { category: "شخصية" }, accepted: ["ميسي"] },
  { kind: "emoji", display: "⚽🇵🇹🤸", meta: { category: "شخصية" }, accepted: ["كريستيانو رونالدو", "رونالدو"] },
  { kind: "emoji", display: "🥊🦋🐝", meta: { category: "شخصية" }, accepted: ["محمد علي كلاي"] },
  { kind: "emoji", display: "🏀2️⃣3️⃣🐂", meta: { category: "شخصية" }, accepted: ["مايكل جوردن"] },
  { kind: "emoji", display: "🎨😊🖼️", meta: { category: "شخصية" }, accepted: ["ليوناردو دافنشي"] },
  { kind: "emoji", display: "👂🌻🎨", meta: { category: "شخصية" }, accepted: ["فان غوخ"] },
  { kind: "emoji", display: "🇮🇳🕊️👓", meta: { category: "شخصية" }, accepted: ["غاندي"] },
  { kind: "emoji", display: "🇿🇦⛓️🕊️", meta: { category: "شخصية" }, accepted: ["نيلسون مانديلا"] },
  { kind: "emoji", display: "👑🇫🇷⚔️", meta: { category: "شخصية" }, accepted: ["نابليون"] },
  { kind: "emoji", display: "🧭🌊🚢", meta: { category: "شخصية" }, accepted: ["كولومبوس"] },
  { kind: "emoji", display: "📖🧮➗", meta: { category: "شخصية" }, accepted: ["الخوارزمي"] },
  { kind: "emoji", display: "🩺📚🕌", meta: { category: "شخصية" }, accepted: ["ابن سينا"] },
  { kind: "emoji", display: "🐪⚔️🏜️", meta: { category: "شخصية" }, accepted: ["خالد بن الوليد"] },
  { kind: "emoji", display: "💡🔦⚡", meta: { category: "شخصية" }, accepted: ["إديسون"] },
  { kind: "emoji", display: "📞🗣️🔔", meta: { category: "شخصية" }, accepted: ["غراهام بيل"] },
  { kind: "emoji", display: "🧪☢️👩‍🔬", meta: { category: "شخصية" }, accepted: ["ماري كوري"] },
  { kind: "emoji", display: "🎤👑🌹", meta: { category: "شخصية" }, accepted: ["أم كلثوم"] },
  { kind: "emoji", display: "⚽🇪🇬🔴", meta: { category: "شخصية" }, accepted: ["محمد صلاح"] },
  { kind: "emoji", display: "🖥️🪟💰", meta: { category: "شخصية" }, accepted: ["بيل غيتس"] },
  { kind: "emoji", display: "📦🛒🚀", meta: { category: "شخصية" }, accepted: ["جيف بيزوس"] },
  { kind: "emoji", display: "👍💙👨‍💻", meta: { category: "شخصية" }, accepted: ["مارك زوكربيرغ"] },
  { kind: "emoji", display: "🔍🌐🔵", meta: { category: "شخصية" }, accepted: ["لاري بيج"] },
  { kind: "emoji", display: "📱🐦💬", meta: { category: "شخصية" }, accepted: ["جاك دورسي"] },
  { kind: "emoji", display: "🧲⚡🗼", meta: { category: "شخصية" }, accepted: ["نيكولا تسلا"] },
  { kind: "emoji", display: "🍄🧫💊", meta: { category: "شخصية" }, accepted: ["ألكسندر فلمنغ"] },
  { kind: "emoji", display: "🧬🐒📕", meta: { category: "شخصية" }, accepted: ["داروين"] },
  { kind: "emoji", display: "🔭🌍☀️", meta: { category: "شخصية" }, accepted: ["غاليليو"] },
  { kind: "emoji", display: "🌍🔄☀️", meta: { category: "شخصية" }, accepted: ["كوبرنيكوس"] },
  { kind: "emoji", display: "♿🌌🕳️", meta: { category: "شخصية" }, accepted: ["ستيفن هوكينغ"] },
  { kind: "emoji", display: "📐🛁💧", meta: { category: "شخصية" }, accepted: ["أرخميدس"] },
  { kind: "emoji", display: "📐📏➖", meta: { category: "شخصية" }, accepted: ["فيثاغورس"] },
  { kind: "emoji", display: "🏛️💭☠️", meta: { category: "شخصية" }, accepted: ["سقراط"] },
  { kind: "emoji", display: "🏛️📜💡", meta: { category: "شخصية" }, accepted: ["أفلاطون"] },
  { kind: "emoji", display: "📚🧠🏛️", meta: { category: "شخصية" }, accepted: ["أرسطو"] },
  { kind: "emoji", display: "🗺️🧳🐫", meta: { category: "شخصية" }, accepted: ["ابن بطوطة"] },
  { kind: "emoji", display: "🗺️🧭📜", meta: { category: "شخصية" }, accepted: ["الإدريسي"] },
  { kind: "emoji", display: "📚🏛️🕌", meta: { category: "شخصية" }, accepted: ["ابن خلدون"] },
  { kind: "emoji", display: "👁️🔦📐", meta: { category: "شخصية" }, accepted: ["ابن الهيثم"] },
  { kind: "emoji", display: "⚗️🧪🕌", meta: { category: "شخصية" }, accepted: ["جابر بن حيان"] },
  { kind: "emoji", display: "🩺🧫📕", meta: { category: "شخصية" }, accepted: ["الرازي"] },
  { kind: "emoji", display: "🕊️📜🇺🇸", meta: { category: "شخصية" }, accepted: ["أبراهام لنكولن"] },
  { kind: "emoji", display: "🇺🇸🪓🍒", meta: { category: "شخصية" }, accepted: ["جورج واشنطن"] },
  { kind: "emoji", display: "✊🎙️🕊️", meta: { category: "شخصية" }, accepted: ["مارتن لوثر كينغ"] },
  { kind: "emoji", display: "🇬🇧🎩✌️", meta: { category: "شخصية" }, accepted: ["ونستون تشرشل"] },
  { kind: "emoji", display: "👑🇬🇧👜", meta: { category: "شخصية" }, accepted: ["الملكة إليزابيث"] },
  { kind: "emoji", display: "🌹👑🇬🇧", meta: { category: "شخصية" }, accepted: ["الأميرة ديانا"] },
  { kind: "emoji", display: "🏜️🇸🇦🕋", meta: { category: "شخصية" }, accepted: ["الملك عبدالعزيز"] },
  { kind: "emoji", display: "📖🖋️🇪🇬", meta: { category: "شخصية" }, accepted: ["نجيب محفوظ"] },
  { kind: "emoji", display: "🖋️🌊🇱🇧", meta: { category: "شخصية" }, accepted: ["جبران خليل جبران"] },
  { kind: "emoji", display: "🖋️🇸🇾🌹", meta: { category: "شخصية" }, accepted: ["نزار قباني"] },
  { kind: "emoji", display: "🖋️🇵🇸🕊️", meta: { category: "شخصية" }, accepted: ["محمود درويش"] },
  { kind: "emoji", display: "🎤🎵🇱🇧", meta: { category: "شخصية" }, accepted: ["فيروز"] },
  { kind: "emoji", display: "🎶🎻🇪🇬", meta: { category: "شخصية" }, accepted: ["عبدالحليم حافظ"] },
  { kind: "emoji", display: "🎸🎤🇪🇬", meta: { category: "شخصية" }, accepted: ["عمرو دياب"] },
  { kind: "emoji", display: "🎤🇸🇦🎵", meta: { category: "شخصية" }, accepted: ["محمد عبده"] },
  { kind: "emoji", display: "🎼🎤🇸🇦", meta: { category: "شخصية" }, accepted: ["طلال مداح"] },
  { kind: "emoji", display: "🎬😂🇪🇬", meta: { category: "شخصية" }, accepted: ["عادل إمام"] },
  { kind: "emoji", display: "🎭🎬🇪🇬", meta: { category: "شخصية" }, accepted: ["أحمد زكي"] },
  { kind: "emoji", display: "🎬🕶️🇪🇬", meta: { category: "شخصية" }, accepted: ["عمر الشريف"] },
  { kind: "emoji", display: "⚽🇧🇷👑", meta: { category: "شخصية" }, accepted: ["بيليه"] },
  { kind: "emoji", display: "⚽🇦🇷✋", meta: { category: "شخصية" }, accepted: ["مارادونا"] },
  { kind: "emoji", display: "⚽🇫🇷🪖", meta: { category: "شخصية" }, accepted: ["زيدان"] },
  { kind: "emoji", display: "⚽🇧🇷🦷", meta: { category: "شخصية" }, accepted: ["رونالدينهو"] },
  { kind: "emoji", display: "⚽🇫🇷⚡", meta: { category: "شخصية" }, accepted: ["مبابي"] },
  { kind: "emoji", display: "⚽🇳🇴🤖", meta: { category: "شخصية" }, accepted: ["هالاند"] },
  { kind: "emoji", display: "⚽🇸🇳🦁", meta: { category: "شخصية" }, accepted: ["ساديو ماني"] },
  { kind: "emoji", display: "⚽🇩🇿🇩🇿", meta: { category: "شخصية" }, accepted: ["رياض محرز"] },
  { kind: "emoji", display: "🏀👑🇺🇸", meta: { category: "شخصية" }, accepted: ["ليبرون جيمس"] },
  { kind: "emoji", display: "🏀🐍2️⃣4️⃣", meta: { category: "شخصية" }, accepted: ["كوبي براينت"] },
  { kind: "emoji", display: "🎾🇷🇸🏆", meta: { category: "شخصية" }, accepted: ["ديوكوفيتش"] },
  { kind: "emoji", display: "🎾🇨🇭🎩", meta: { category: "شخصية" }, accepted: ["فيدرر"] },
  { kind: "emoji", display: "🎾🇪🇸💪", meta: { category: "شخصية" }, accepted: ["نادال"] },
  { kind: "emoji", display: "🏊🥇🇺🇸", meta: { category: "شخصية" }, accepted: ["مايكل فيلبس"] },
  { kind: "emoji", display: "🏃⚡🇯🇲", meta: { category: "شخصية" }, accepted: ["يوسين بولت"] },
  { kind: "emoji", display: "🥊🇺🇸🐻", meta: { category: "شخصية" }, accepted: ["مايك تايسون"] },
  { kind: "emoji", display: "🥋🇷🇺🦅", meta: { category: "شخصية" }, accepted: ["خابيب"] },
  { kind: "emoji", display: "🎬💪🇦🇹", meta: { category: "شخصية" }, accepted: ["أرنولد شوارزنيغر"] },
  { kind: "emoji", display: "🥋🐉👊", meta: { category: "شخصية" }, accepted: ["بروس لي"] },
  { kind: "emoji", display: "🥋😂🎬", meta: { category: "شخصية" }, accepted: ["جاكي شان"] },
  { kind: "emoji", display: "🎩🖤🎬", meta: { category: "شخصية" }, accepted: ["شارلي شابلن"] },
  { kind: "emoji", display: "🎬🦈🚲", meta: { category: "شخصية" }, accepted: ["ستيفن سبيلبرغ"] },
  { kind: "emoji", display: "🎬🌀🦇", meta: { category: "شخصية" }, accepted: ["كريستوفر نولان"] },
  { kind: "emoji", display: "👗💋🎬", meta: { category: "شخصية" }, accepted: ["مارلين مونرو"] },
  { kind: "emoji", display: "🎤👑🌍", meta: { category: "شخصية" }, accepted: ["مايكل جاكسون"] },
  { kind: "emoji", display: "🎸🐞🇬🇧", meta: { category: "شخصية" }, accepted: ["البيتلز"] },
  { kind: "emoji", display: "🎤🇺🇸🐍", meta: { category: "شخصية" }, accepted: ["تايلور سويفت"] },
  { kind: "emoji", display: "🧕📚🎖️", meta: { category: "شخصية" }, accepted: ["ملالا"] },
  { kind: "emoji", display: "🕊️🧕💉", meta: { category: "شخصية" }, accepted: ["الأم تيريزا"] },
  { kind: "emoji", display: "👩‍🚀🌌🇺🇸", meta: { category: "شخصية" }, accepted: ["نيل أرمسترونغ"] },
  { kind: "emoji", display: "🚀🌍🇷🇺", meta: { category: "شخصية" }, accepted: ["يوري غاغارين"] },
  { kind: "emoji", display: "🛞🏭🚗", meta: { category: "شخصية" }, accepted: ["هنري فورد"] },
  { kind: "emoji", display: "🍔🤡🍟", meta: { category: "شخصية" }, accepted: ["رونالد ماكدونالد"] },
  { kind: "emoji", display: "📚⚡🧙‍♀️", meta: { category: "شخصية" }, accepted: ["جي كي رولينغ"] },
  { kind: "emoji", display: "📖🧝💍", meta: { category: "شخصية" }, accepted: ["تولكين"] },
  { kind: "emoji", display: "📖🕵️🇬🇧", meta: { category: "شخصية" }, accepted: ["أجاثا كريستي"] },
  { kind: "emoji", display: "🖋️🎭🇬🇧", meta: { category: "شخصية" }, accepted: ["شكسبير"] },
  { kind: "emoji", display: "🌙🌹🎶", meta: { category: "أغنية" }, accepted: ["إنت عمري"] },
  { kind: "emoji", display: "👶🎤🎉", meta: { category: "أغنية" }, accepted: ["الليلة"] },
  { kind: "emoji", display: "💃🇪🇸🎵", meta: { category: "أغنية" }, accepted: ["ديسباسيتو"] },
  { kind: "emoji", display: "🇧🇷⚽🥁", meta: { category: "أغنية" }, accepted: ["وكا وكا"] },
  { kind: "emoji", display: "🦈👶🎶", meta: { category: "أغنية" }, accepted: ["بيبي شارك"] },
  { kind: "emoji", display: "🎂🎉🎵", meta: { category: "أغنية" }, accepted: ["سنة حلوة يا جميل"] },
  { kind: "emoji", display: "💍👰🎶", meta: { category: "أغنية" }, accepted: ["ألف مبروك"] },
  { kind: "emoji", display: "🌙🕌🎵", meta: { category: "أغنية" }, accepted: ["رمضان جانا"] },
  { kind: "emoji", display: "👋📞🎤", meta: { category: "أغنية" }, accepted: ["هيلو"] },
  { kind: "emoji", display: "☔🎤💔", meta: { category: "أغنية" }, accepted: ["أمبريلا"] },
  { kind: "emoji", display: "🌟✨🎶", meta: { category: "أغنية" }, accepted: ["شاين"] },
  { kind: "emoji", display: "🇱🇧🌲🎶", meta: { category: "أغنية" }, accepted: ["بحبك يا لبنان"] },
  { kind: "emoji", display: "☕☀️🎵", meta: { category: "أغنية" }, accepted: ["صباح ومسا"] },
  { kind: "emoji", display: "🌊🚢🎶", meta: { category: "أغنية" }, accepted: ["سواح"] },
  { kind: "emoji", display: "🌹🌹🎤", meta: { category: "أغنية" }, accepted: ["وردة"] },
  { kind: "emoji", display: "👑🎤🇪🇬", meta: { category: "أغنية" }, accepted: ["أمير الغرام"] },
  { kind: "emoji", display: "👁️🖤🎵", meta: { category: "أغنية" }, accepted: ["عيون القلب"] },
  { kind: "emoji", display: "🌛🎶🇱🇧", meta: { category: "أغنية" }, accepted: ["قمر"] },
  { kind: "emoji", display: "💔🎵😢", meta: { category: "أغنية" }, accepted: ["كلمني"] },
  { kind: "emoji", display: "🚗🛣️🎶", meta: { category: "أغنية" }, accepted: ["على الطريق"] },
  { kind: "emoji", display: "🕰️⏳🎵", meta: { category: "أغنية" }, accepted: ["الوقت"] },
  { kind: "emoji", display: "🌧️☔🎶", meta: { category: "أغنية" }, accepted: ["يا مطر"] },
  { kind: "emoji", display: "🔥❤️🎤", meta: { category: "أغنية" }, accepted: ["نار"] },
  { kind: "emoji", display: "🌍🕊️🎵", meta: { category: "أغنية" }, accepted: ["هيل ذا وورلد"] },
  { kind: "emoji", display: "🌛🚶🎤", meta: { category: "أغنية" }, accepted: ["بيلي جين"] },
  { kind: "emoji", display: "🧟🌕🎶", meta: { category: "أغنية" }, accepted: ["ثريلر"] },
  { kind: "emoji", display: "🎩🕺🎵", meta: { category: "أغنية" }, accepted: ["سموث كريمنال"] },
  { kind: "emoji", display: "👑🎸🇬🇧", meta: { category: "أغنية" }, accepted: ["وي ويل روك يو"] },
  { kind: "emoji", display: "🏆🎤👑", meta: { category: "أغنية" }, accepted: ["وي آر ذا تشامبيونز"] },
  { kind: "emoji", display: "🚢💙🎻", meta: { category: "أغنية" }, accepted: ["قلبي سيستمر", "ماي هارت ويل غو أون"] },
  { kind: "emoji", display: "🌌⭐🎵", meta: { category: "أغنية" }, accepted: ["كاونتينغ ستارز"] },
  { kind: "emoji", display: "🕺😄🎶", meta: { category: "أغنية" }, accepted: ["هابي"] },
  { kind: "emoji", display: "🎩💃🎵", meta: { category: "أغنية" }, accepted: ["أبتاون فانك"] },
  { kind: "emoji", display: "🟨🌊🎶", meta: { category: "أغنية" }, accepted: ["يلو سبمارين"] },
  { kind: "emoji", display: "✌️🌍🎤", meta: { category: "أغنية" }, accepted: ["إيماجين"] },
  { kind: "emoji", display: "🎸🏨🌵", meta: { category: "أغنية" }, accepted: ["هوتيل كاليفورنيا"] },
  { kind: "emoji", display: "🌧️💜🎸", meta: { category: "أغنية" }, accepted: ["بيربل رين"] },
  { kind: "emoji", display: "👧🔥🎤", meta: { category: "أغنية" }, accepted: ["غيرل أون فاير"] },
  { kind: "emoji", display: "💪🎤🦋", meta: { category: "أغنية" }, accepted: ["ستروغر"] },
  { kind: "emoji", display: "🎧🕶️🎵", meta: { category: "أغنية" }, accepted: ["بلايندنغ لايتس"] },
  { kind: "emoji", display: "🌵🎶🌊", meta: { category: "أغنية" }, accepted: ["سينوريتا"] },
  { kind: "emoji", display: "🇨🇴💃🎵", meta: { category: "أغنية" }, accepted: ["هيبس دونت لاي"] },
  { kind: "emoji", display: "🥁🔥🎤", meta: { category: "أغنية" }, accepted: ["دراغوستيا دين تي"] },
  { kind: "emoji", display: "🎺🎉🇨🇺", meta: { category: "أغنية" }, accepted: ["بامبوليو"] },
  { kind: "emoji", display: "🌴🌞🎶", meta: { category: "أغنية" }, accepted: ["سمر"] },
  { kind: "emoji", display: "🚙🌄🎵", meta: { category: "أغنية" }, accepted: ["كنتري رودز"] },
  { kind: "emoji", display: "🕊️🎸🎶", meta: { category: "أغنية" }, accepted: ["نوذينغ إلس ماترز"] },
  { kind: "emoji", display: "🔔🎄🎶", meta: { category: "أغنية" }, accepted: ["جينغل بيلز"] },
  { kind: "emoji", display: "🎅🎁🎵", meta: { category: "أغنية" }, accepted: ["لاست كريسماس"] },
  { kind: "emoji", display: "👑💰🎤", meta: { category: "أغنية" }, accepted: ["ماني ماني"] },
  { kind: "emoji", display: "💃🪩🎶", meta: { category: "أغنية" }, accepted: ["دانسينغ كوين"] },
  { kind: "emoji", display: "🎤😭💔", meta: { category: "أغنية" }, accepted: ["سومون لايك يو"] },
  { kind: "emoji", display: "📞🔥🎵", meta: { category: "أغنية" }, accepted: ["رولينغ إن ذا ديب"] },
  { kind: "emoji", display: "🌊⛵🎶", meta: { category: "أغنية" }, accepted: ["سيلينغ"] },
  { kind: "emoji", display: "🚶🌙🎵", meta: { category: "أغنية" }, accepted: ["ووك أون"] },
  { kind: "emoji", display: "⚽🏆🎶", meta: { category: "أغنية" }, accepted: ["أغنية كأس العالم"] },
  { kind: "emoji", display: "🇩🇿🎶🥁", meta: { category: "أغنية" }, accepted: ["راي"] },
  { kind: "emoji", display: "🇲🇦🎵🥁", meta: { category: "أغنية" }, accepted: ["حبيبي يا نور العين"] },
  { kind: "emoji", display: "👳🐪🎶", meta: { category: "أغنية" }, accepted: ["البدوي"] },
  { kind: "emoji", display: "🇰🇼🎤🎵", meta: { category: "أغنية" }, accepted: ["أبعاد"] },
  { kind: "emoji", display: "💌✉️🎶", meta: { category: "أغنية" }, accepted: ["رسالة حب"] },
  { kind: "emoji", display: "🕊️🤍🎵", meta: { category: "أغنية" }, accepted: ["سلام"] },
  { kind: "emoji", display: "🌅🎶🌄", meta: { category: "أغنية" }, accepted: ["صباح الخير"] },
  { kind: "emoji", display: "🎓🎉🎵", meta: { category: "أغنية" }, accepted: ["أغنية التخرج"] },
  { kind: "emoji", display: "🇸🇦🏳️🎶", meta: { category: "أغنية" }, accepted: ["النشيد الوطني"] },
  { kind: "emoji", display: "👩❤️🎤", meta: { category: "أغنية" }, accepted: ["ست الحبايب"] },
  { kind: "emoji", display: "👨❤️🎵", meta: { category: "أغنية" }, accepted: ["أبويا"] },
  { kind: "emoji", display: "🏡🌾🎶", meta: { category: "أغنية" }, accepted: ["يا بلادي"] },
  { kind: "emoji", display: "🎒🏫🎵", meta: { category: "أغنية" }, accepted: ["أغنية المدرسة"] },
  { kind: "emoji", display: "🎤🌊🎵", meta: { category: "أغنية" }, accepted: ["موجة"] },
  { kind: "emoji", display: "🌕🌴🕌", meta: { category: "أنشودة" }, accepted: ["طلع البدر علينا"] },
  { kind: "emoji", display: "🕋🤲📣", meta: { category: "أنشودة" }, accepted: ["الله أكبر"] },
  { kind: "emoji", display: "💚🕌🏙️", meta: { category: "أنشودة" }, accepted: ["طيبة"] },
  { kind: "emoji", display: "🌙🏮🍽️", meta: { category: "أنشودة" }, accepted: ["أهلا رمضان"] },
  { kind: "emoji", display: "👶👩❤️", meta: { category: "أنشودة" }, accepted: ["أمي"] },
  { kind: "emoji", display: "📖✨🕌", meta: { category: "أنشودة" }, accepted: ["نور القرآن"] },
  { kind: "emoji", display: "🕊️☮️🌍", meta: { category: "أنشودة" }, accepted: ["أنشودة السلام"] },
  { kind: "emoji", display: "👨‍👩‍👧🏠❤️", meta: { category: "أنشودة" }, accepted: ["بيتنا", "الأسرة"] },
  { kind: "emoji", display: "🌸🌱☀️", meta: { category: "أنشودة" }, accepted: ["الربيع"] },
  { kind: "emoji", display: "🤲💧🌧️", meta: { category: "أنشودة" }, accepted: ["دعاء المطر"] },
  { kind: "emoji", display: "🕌🧎⏰", meta: { category: "أنشودة" }, accepted: ["حي على الصلاة"] },
  { kind: "emoji", display: "🇵🇸🕌🕊️", meta: { category: "أنشودة" }, accepted: ["القدس"] },
  { kind: "emoji", display: "📚✏️🏫", meta: { category: "أنشودة" }, accepted: ["أنشودة العلم"] },
  { kind: "emoji", display: "🌟🌙😴", meta: { category: "أنشودة" }, accepted: ["أنشودة النوم"] },
  { kind: "emoji", display: "🐦🌳🎵", meta: { category: "أنشودة" }, accepted: ["العصفور"] },
  { kind: "emoji", display: "💧🚿🌿", meta: { category: "أنشودة" }, accepted: ["نعمة الماء"] },
  { kind: "emoji", display: "👳📖❤️", meta: { category: "أنشودة" }, accepted: ["محمد نبينا"] },
  { kind: "emoji", display: "🕋🐫🤍", meta: { category: "أنشودة" }, accepted: ["لبيك اللهم لبيك"] },
  { kind: "emoji", display: "🌙🎉🍬", meta: { category: "أنشودة" }, accepted: ["العيد"] },
  { kind: "emoji", display: "🕌🌍🤝", meta: { category: "أنشودة" }, accepted: ["أمة الإسلام"] },
  { kind: "emoji", display: "👶🍼😴", meta: { category: "أنشودة" }, accepted: ["أنشودة الطفل"] },
  { kind: "emoji", display: "🌳🍎🌿", meta: { category: "أنشودة" }, accepted: ["الشجرة"] },
  { kind: "emoji", display: "☀️🌤️🌍", meta: { category: "أنشودة" }, accepted: ["الشمس"] },
  { kind: "emoji", display: "🐝🍯🌸", meta: { category: "أنشودة" }, accepted: ["النحلة"] },
  { kind: "emoji", display: "🧹🧼✨", meta: { category: "أنشودة" }, accepted: ["النظافة"] },
  { kind: "emoji", display: "🤝😊🫂", meta: { category: "أنشودة" }, accepted: ["الصداقة"] },
  { kind: "emoji", display: "🇩🇿🏳️❤️", meta: { category: "أنشودة" }, accepted: ["أنشودة الوطن"] },
  { kind: "emoji", display: "🧕📿🤍", meta: { category: "أنشودة" }, accepted: ["الحجاب"] },
  { kind: "emoji", display: "🤲🌙🕌", meta: { category: "أنشودة" }, accepted: ["دعاء"] },
  { kind: "emoji", display: "🐪🏜️🕌", meta: { category: "أنشودة" }, accepted: ["الهجرة"] }
];
