import type { TriviaQuestion } from "../engine";

export const fastestWordBank: TriviaQuestion[] = [
  { kind: "text", display: "اكتب: قهوة", accepted: ["قهوة"] },
  { kind: "text", display: "اكتب: برتقال", accepted: ["برتقال"] },
  { kind: "text", display: "اكتب: حاسوب", accepted: ["حاسوب"] },
  { kind: "text", display: "اكتب: سيارة", accepted: ["سيارة"] },
  { kind: "text", display: "اكتب: مدرسة", accepted: ["مدرسة"] },
  { kind: "text", display: "اكتب: شمس", accepted: ["شمس"] },
  { kind: "text", display: "اكتب: قمر", accepted: ["قمر"] },
  { kind: "text", display: "اكتب: بحر", accepted: ["بحر"] },
  { kind: "text", display: "اكتب: جبل", accepted: ["جبل"] },
  { kind: "text", display: "اكتب: نافذة", accepted: ["نافذة"] },
  { kind: "text", display: "اكتب: مفتاح", accepted: ["مفتاح"] },
  { kind: "text", display: "اكتب: ساعة", accepted: ["ساعة"] },
  { kind: "text", display: "اكتب: كتاب", accepted: ["كتاب"] },
  { kind: "text", display: "اكتب: طائرة", accepted: ["طائرة"] },
  { kind: "text", display: "اكتب: مطبخ", accepted: ["مطبخ"] },
  { kind: "text", display: "اكتب: حديقة", accepted: ["حديقة"] },
  { kind: "text", display: "اكتب: هاتف", accepted: ["هاتف"] },
  { kind: "text", display: "اكتب: كرسي", accepted: ["كرسي"] },
  { kind: "text", display: "اكتب: مصباح", accepted: ["مصباح"] },
  { kind: "text", display: "اكتب: ثلاجة", accepted: ["ثلاجة"] },
  { kind: "text", display: "اكتب: خيمة", accepted: ["خيمة"] },
  { kind: "text", display: "اكتب: سلحفاة", accepted: ["سلحفاة"] },
  { kind: "text", display: "اكتب: فراشة", accepted: ["فراشة"] },
  { kind: "text", display: "اكتب: بطيخ", accepted: ["بطيخ"] },
  { kind: "text", display: "اكتب: دراجة", accepted: ["دراجة"] },
  { kind: "text", display: "اكتب: مظلة", accepted: ["مظلة"] },
  { kind: "text", display: "اكتب: قلم", accepted: ["قلم"] },
  { kind: "text", display: "اكتب: شجرة", accepted: ["شجرة"] },
  { kind: "text", display: "اكتب: نجمة", accepted: ["نجمة"] },
  { kind: "text", display: "اكتب: غيمة", accepted: ["غيمة"] },
  { kind: "text", display: "اكتب: تفاح", accepted: ["تفاح"] },
  { kind: "text", display: "اكتب: موز", accepted: ["موز"] },
  { kind: "text", display: "اكتب: عنب", accepted: ["عنب"] },
  { kind: "text", display: "اكتب: فراولة", accepted: ["فراولة"] },
  { kind: "text", display: "اكتب: أناناس", accepted: ["أناناس"] },
  { kind: "text", display: "اكتب: برتقالة", accepted: ["برتقالة"] },
  { kind: "text", display: "اكتب: ليمون", accepted: ["ليمون"] },
  { kind: "text", display: "اكتب: مانجو", accepted: ["مانجو"] },
  { kind: "text", display: "اكتب: خوخ", accepted: ["خوخ"] },
  { kind: "text", display: "اكتب: كمثرى", accepted: ["كمثرى"] },
  { kind: "text", display: "اكتب: طماطم", accepted: ["طماطم"] },
  { kind: "text", display: "اكتب: خيار", accepted: ["خيار"] },
  { kind: "text", display: "اكتب: بصل", accepted: ["بصل"] },
  { kind: "text", display: "اكتب: ثوم", accepted: ["ثوم"] },
  { kind: "text", display: "اكتب: جزر", accepted: ["جزر"] },
  { kind: "text", display: "اكتب: بطاطا", accepted: ["بطاطا"] },
  { kind: "text", display: "اكتب: فلفل", accepted: ["فلفل"] },
  { kind: "text", display: "اكتب: باذنجان", accepted: ["باذنجان"] },
  { kind: "text", display: "اكتب: خس", accepted: ["خس"] },
  { kind: "text", display: "اكتب: فطر", accepted: ["فطر"] },
  { kind: "text", display: "اكتب: أسد", accepted: ["أسد"] },
  { kind: "text", display: "اكتب: نمر", accepted: ["نمر"] },
  { kind: "text", display: "اكتب: فيل", accepted: ["فيل"] },
  { kind: "text", display: "اكتب: زرافة", accepted: ["زرافة"] },
  { kind: "text", display: "اكتب: حصان", accepted: ["حصان"] },
  { kind: "text", display: "اكتب: بقرة", accepted: ["بقرة"] },
  { kind: "text", display: "اكتب: خروف", accepted: ["خروف"] },
  { kind: "text", display: "اكتب: ماعز", accepted: ["ماعز"] },
  { kind: "text", display: "اكتب: أرنب", accepted: ["أرنب"] },
  { kind: "text", display: "اكتب: قرد", accepted: ["قرد"] },
  { kind: "text", display: "اكتب: دب", accepted: ["دب"] },
  { kind: "text", display: "اكتب: ذئب", accepted: ["ذئب"] },
  { kind: "text", display: "اكتب: ثعلب", accepted: ["ثعلب"] },
  { kind: "text", display: "اكتب: نسر", accepted: ["نسر"] },
  { kind: "text", display: "اكتب: بومة", accepted: ["بومة"] },
  { kind: "text", display: "اكتب: بطة", accepted: ["بطة"] },
  { kind: "text", display: "اكتب: دجاجة", accepted: ["دجاجة"] },
  { kind: "text", display: "اكتب: ديك", accepted: ["ديك"] },
  { kind: "text", display: "اكتب: حمامة", accepted: ["حمامة"] },
  { kind: "text", display: "اكتب: عصفور", accepted: ["عصفور"] },
  { kind: "text", display: "اكتب: مسطرة", accepted: ["مسطرة"] },
  { kind: "text", display: "اكتب: ممحاة", accepted: ["ممحاة"] },
  { kind: "text", display: "اكتب: براد", accepted: ["براد"] },
  { kind: "text", display: "اكتب: مقص", accepted: ["مقص"] },
  { kind: "text", display: "اكتب: خزانة", accepted: ["خزانة"] },
  { kind: "text", display: "اكتب: طاولة", accepted: ["طاولة"] },
  { kind: "text", display: "اكتب: سرير", accepted: ["سرير"] },
  { kind: "text", display: "اكتب: وسادة", accepted: ["وسادة"] },
  { kind: "text", display: "اكتب: بطانية", accepted: ["بطانية"] },
  { kind: "text", display: "اكتب: مرآة", accepted: ["مرآة"] },
  { kind: "text", display: "اكتب: فرشاة", accepted: ["فرشاة"] },
  { kind: "text", display: "اكتب: صابون", accepted: ["صابون"] },
  { kind: "text", display: "اكتب: منشفة", accepted: ["منشفة"] },
  { kind: "text", display: "اكتب: مغسلة", accepted: ["مغسلة"] },
  { kind: "text", display: "اكتب: مروحة", accepted: ["مروحة"] },
  { kind: "text", display: "اكتب: مكنسة", accepted: ["مكنسة"] },
  { kind: "text", display: "اكتب: سلة", accepted: ["سلة"] },
  { kind: "text", display: "اكتب: صندوق", accepted: ["صندوق"] },
  { kind: "text", display: "اكتب: حبل", accepted: ["حبل"] },
  { kind: "text", display: "اكتب: ابرة", accepted: ["ابرة"] },
  { kind: "text", display: "اكتب: مدفأة", accepted: ["مدفأة"] },
  { kind: "text", display: "اكتب: شمعة", accepted: ["شمعة"] },
  { kind: "text", display: "اكتب: فانوس", accepted: ["فانوس"] },
  { kind: "text", display: "اكتب: بوصلة", accepted: ["بوصلة"] },
  { kind: "text", display: "اكتب: خريطة", accepted: ["خريطة"] },
  { kind: "text", display: "اكتب: مجهر", accepted: ["مجهر"] },
  { kind: "text", display: "اكتب: منظار", accepted: ["منظار"] },
  { kind: "text", display: "اكتب: مسدس", accepted: ["مسدس"] },
  { kind: "text", display: "اكتب: سيف", accepted: ["سيف"] },
  { kind: "text", display: "اكتب: درع", accepted: ["درع"] },
  { kind: "text", display: "اكتب: تاج", accepted: ["تاج"] },
  { kind: "text", display: "اكتب: خاتم", accepted: ["خاتم"] },
  { kind: "text", display: "اكتب: قلادة", accepted: ["قلادة"] },
  { kind: "text", display: "اكتب: ساعة يد", accepted: ["ساعة يد"] },
  { kind: "text", display: "اكتب: نظارة", accepted: ["نظارة"] },
  { kind: "text", display: "اكتب: قبعة", accepted: ["قبعة"] },
  { kind: "text", display: "اكتب: حذاء", accepted: ["حذاء"] },
  { kind: "text", display: "اكتب: جورب", accepted: ["جورب"] },
  { kind: "text", display: "اكتب: قميص", accepted: ["قميص"] },
  { kind: "text", display: "اكتب: بنطلون", accepted: ["بنطلون"] },
  { kind: "text", display: "اكتب: شتاء", accepted: ["شتاء"] },
  { kind: "text", display: "اكتب: صيف", accepted: ["صيف"] },
  { kind: "text", display: "اكتب: ربيع", accepted: ["ربيع"] },
  { kind: "text", display: "اكتب: خريف", accepted: ["خريف"] },
  { kind: "text", display: "اكتب: مطر", accepted: ["مطر"] },
  { kind: "text", display: "اكتب: ثلج", accepted: ["ثلج"] },
  { kind: "text", display: "اكتب: رياح", accepted: ["رياح"] },
  { kind: "text", display: "اكتب: برق", accepted: ["برق"] },
  { kind: "text", display: "اكتب: رعد", accepted: ["رعد"] },
  { kind: "text", display: "اكتب: ضباب", accepted: ["ضباب"] },
  { kind: "text", display: "اكتب: قوس قزح", accepted: ["قوس قزح"] },
  { kind: "text", display: "اكتب: بركان", accepted: ["بركان"] },
  { kind: "text", display: "اكتب: زلزال", accepted: ["زلزال"] },
  { kind: "text", display: "اكتب: فيضان", accepted: ["فيضان"] },
  { kind: "text", display: "اكتب: صحراء", accepted: ["صحراء"] },
  { kind: "text", display: "اكتب: غابة", accepted: ["غابة"] },
  { kind: "text", display: "اكتب: واحة", accepted: ["واحة"] },
  { kind: "text", display: "اكتب: شلال", accepted: ["شلال"] },
  { kind: "text", display: "اكتب: بحيرة", accepted: ["بحيرة"] },
  { kind: "text", display: "اكتب: نهر", accepted: ["نهر"] },
  { kind: "text", display: "اكتب: طبيب", accepted: ["طبيب"] },
  { kind: "text", display: "اكتب: مهندس", accepted: ["مهندس"] },
  { kind: "text", display: "اكتب: معلم", accepted: ["معلم"] },
  { kind: "text", display: "اكتب: شرطي", accepted: ["شرطي"] },
  { kind: "text", display: "اكتب: طباخ", accepted: ["طباخ"] },
  { kind: "text", display: "اكتب: نجار", accepted: ["نجار"] },
  { kind: "text", display: "اكتب: حداد", accepted: ["حداد"] },
  { kind: "text", display: "اكتب: سائق", accepted: ["سائق"] },
  { kind: "text", display: "اكتب: طيار", accepted: ["طيار"] },
  { kind: "text", display: "اكتب: ممرضة", accepted: ["ممرضة"] },
  { kind: "text", display: "اكتب: محامي", accepted: ["محامي"] },
  { kind: "text", display: "اكتب: قاضي", accepted: ["قاضي"] },
  { kind: "text", display: "اكتب: صياد", accepted: ["صياد"] },
  { kind: "text", display: "اكتب: فلاح", accepted: ["فلاح"] },
  { kind: "text", display: "اكتب: خباز", accepted: ["خباز"] },
  { kind: "text", display: "اكتب: نحات", accepted: ["نحات"] },
  { kind: "text", display: "اكتب: رسام", accepted: ["رسام"] },
  { kind: "text", display: "اكتب: مصور", accepted: ["مصور"] },
  { kind: "text", display: "اكتب: موسيقي", accepted: ["موسيقي"] },
  { kind: "text", display: "اكتب: ممثل", accepted: ["ممثل"] },
  { kind: "text", display: "اكتب: مذيع", accepted: ["مذيع"] },
  { kind: "text", display: "اكتب: كاتب", accepted: ["كاتب"] },
  { kind: "text", display: "اكتب: شاعر", accepted: ["شاعر"] },
  { kind: "text", display: "اكتب: عالم", accepted: ["عالم"] },
  { kind: "text", display: "اكتب: باحث", accepted: ["باحث"] },
  { kind: "text", display: "اكتب: مترجم", accepted: ["مترجم"] },
  { kind: "text", display: "اكتب: حلاق", accepted: ["حلاق"] },
  { kind: "text", display: "اكتب: خياط", accepted: ["خياط"] },
  { kind: "text", display: "اكتب: بناء", accepted: ["بناء"] },
  { kind: "text", display: "اكتب: كهربائي", accepted: ["كهربائي"] },
  { kind: "text", display: "اكتب: سباك", accepted: ["سباك"] },
  { kind: "text", display: "اكتب: السعودية", accepted: ["السعودية"] },
  { kind: "text", display: "اكتب: مصر", accepted: ["مصر"] },
  { kind: "text", display: "اكتب: الإمارات", accepted: ["الإمارات"] },
  { kind: "text", display: "اكتب: الكويت", accepted: ["الكويت"] },
  { kind: "text", display: "اكتب: الأردن", accepted: ["الأردن"] },
  { kind: "text", display: "اكتب: المغرب", accepted: ["المغرب"] },
  { kind: "text", display: "اكتب: الجزائر", accepted: ["الجزائر"] },
  { kind: "text", display: "اكتب: قطر", accepted: ["قطر"] },
  { kind: "text", display: "اكتب: البحرين", accepted: ["البحرين"] },
  { kind: "text", display: "اكتب: لبنان", accepted: ["لبنان"] },
  { kind: "text", display: "اكتب: تونس", accepted: ["تونس"] },
  { kind: "text", display: "اكتب: العراق", accepted: ["العراق"] },
  { kind: "text", display: "اكتب: اليمن", accepted: ["اليمن"] },
  { kind: "text", display: "اكتب: سوريا", accepted: ["سوريا"] },
  { kind: "text", display: "اكتب: ليبيا", accepted: ["ليبيا"] },
  { kind: "text", display: "اكتب: السودان", accepted: ["السودان"] },
  { kind: "text", display: "اكتب: عمان", accepted: ["عمان"] },
  { kind: "text", display: "اكتب: فلسطين", accepted: ["فلسطين"] },
  { kind: "text", display: "اكتب: موريتانيا", accepted: ["موريتانيا"] },
  { kind: "text", display: "اكتب: الصومال", accepted: ["الصومال"] },
  { kind: "text", display: "اكتب: جيبوتي", accepted: ["جيبوتي"] },
  { kind: "text", display: "اكتب: فرنسا", accepted: ["فرنسا"] },
  { kind: "text", display: "اكتب: ألمانيا", accepted: ["ألمانيا"] },
  { kind: "text", display: "اكتب: إيطاليا", accepted: ["إيطاليا"] },
  { kind: "text", display: "اكتب: إسبانيا", accepted: ["إسبانيا"] },
  { kind: "text", display: "اكتب: اليابان", accepted: ["اليابان"] },
  { kind: "text", display: "اكتب: الصين", accepted: ["الصين"] },
  { kind: "text", display: "اكتب: الهند", accepted: ["الهند"] },
  { kind: "text", display: "اكتب: روسيا", accepted: ["روسيا"] },
  { kind: "text", display: "اكتب: كندا", accepted: ["كندا"] },
  { kind: "text", display: "اكتب: البرازيل", accepted: ["البرازيل"] },
  { kind: "text", display: "اكتب: تركيا", accepted: ["تركيا"] },
  { kind: "text", display: "اكتب: اليونان", accepted: ["اليونان"] },
  { kind: "text", display: "اكتب: بريطانيا", accepted: ["بريطانيا"] },
  { kind: "text", display: "اكتب: أمريكا", accepted: ["أمريكا"] },
  { kind: "text", display: "اكتب: كوريا", accepted: ["كوريا"] },
  { kind: "text", display: "اكتب: إندونيسيا", accepted: ["إندونيسيا"] },
  { kind: "text", display: "اكتب: نيجيريا", accepted: ["نيجيريا"] },
  { kind: "text", display: "اكتب: كينيا", accepted: ["كينيا"] },
  { kind: "text", display: "اكتب: أستراليا", accepted: ["أستراليا"] },
  { kind: "text", display: "اكتب: مكة", accepted: ["مكة"] },
  { kind: "text", display: "اكتب: المدينة", accepted: ["المدينة"] },
  { kind: "text", display: "اكتب: القاهرة", accepted: ["القاهرة"] },
  { kind: "text", display: "اكتب: دبي", accepted: ["دبي"] },
  { kind: "text", display: "اكتب: الرياض", accepted: ["الرياض"] },
  { kind: "text", display: "اكتب: بيروت", accepted: ["بيروت"] },
  { kind: "text", display: "اكتب: بغداد", accepted: ["بغداد"] },
  { kind: "text", display: "اكتب: دمشق", accepted: ["دمشق"] },
  { kind: "text", display: "اكتب: طنجة", accepted: ["طنجة"] },
  { kind: "text", display: "اكتب: اسطنبول", accepted: ["اسطنبول"] },
  { kind: "text", display: "اكتب: لندن", accepted: ["لندن"] },
  { kind: "text", display: "اكتب: باريس", accepted: ["باريس"] },
  { kind: "text", display: "اكتب: روما", accepted: ["روما"] },
  { kind: "text", display: "اكتب: برلين", accepted: ["برلين"] },
  { kind: "text", display: "اكتب: طوكيو", accepted: ["طوكيو"] },
  { kind: "text", display: "اكتب: أحمر", accepted: ["أحمر"] },
  { kind: "text", display: "اكتب: أزرق", accepted: ["أزرق"] },
  { kind: "text", display: "اكتب: أخضر", accepted: ["أخضر"] },
  { kind: "text", display: "اكتب: أصفر", accepted: ["أصفر"] },
  { kind: "text", display: "اكتب: أسود", accepted: ["أسود"] },
  { kind: "text", display: "اكتب: أبيض", accepted: ["أبيض"] },
  { kind: "text", display: "اكتب: بنفسجي", accepted: ["بنفسجي"] },
  { kind: "text", display: "اكتب: برتقالي", accepted: ["برتقالي"] },
  { kind: "text", display: "اكتب: وردي", accepted: ["وردي"] },
  { kind: "text", display: "اكتب: رمادي", accepted: ["رمادي"] },
  { kind: "text", display: "اكتب: بني", accepted: ["بني"] },
  { kind: "text", display: "اكتب: ذهبي", accepted: ["ذهبي"] },
  { kind: "text", display: "اكتب: فضي", accepted: ["فضي"] },
  { kind: "text", display: "اكتب: رأس", accepted: ["رأس"] },
  { kind: "text", display: "اكتب: عين", accepted: ["عين"] },
  { kind: "text", display: "اكتب: أذن", accepted: ["أذن"] },
  { kind: "text", display: "اكتب: أنف", accepted: ["أنف"] },
  { kind: "text", display: "اكتب: فم", accepted: ["فم"] },
  { kind: "text", display: "اكتب: يد", accepted: ["يد"] },
  { kind: "text", display: "اكتب: رجل", accepted: ["رجل"] },
  { kind: "text", display: "اكتب: إصبع", accepted: ["إصبع"] },
  { kind: "text", display: "اكتب: ركبة", accepted: ["ركبة"] },
  { kind: "text", display: "اكتب: كتف", accepted: ["كتف"] },
  { kind: "text", display: "اكتب: ظهر", accepted: ["ظهر"] },
  { kind: "text", display: "اكتب: بطن", accepted: ["بطن"] },
  { kind: "text", display: "اكتب: قلب", accepted: ["قلب"] },
  { kind: "text", display: "اكتب: رئة", accepted: ["رئة"] },
  { kind: "text", display: "اكتب: كبد", accepted: ["كبد"] },
  { kind: "text", display: "اكتب: معدة", accepted: ["معدة"] },
  { kind: "text", display: "اكتب: شعر", accepted: ["شعر"] },
  { kind: "text", display: "اكتب: لسان", accepted: ["لسان"] },
  { kind: "text", display: "اكتب: طباشير", accepted: ["طباشير"] },
  { kind: "text", display: "اكتب: سبورة", accepted: ["سبورة"] },
  { kind: "text", display: "اكتب: لوح", accepted: ["لوح"] },
  { kind: "text", display: "اكتب: مقلمة", accepted: ["مقلمة"] },
  { kind: "text", display: "اكتب: لاصق", accepted: ["لاصق"] },
  { kind: "text", display: "اكتب: دباسة", accepted: ["دباسة"] },
  { kind: "text", display: "اكتب: دفتر", accepted: ["دفتر"] },
  { kind: "text", display: "اكتب: حقيبة", accepted: ["حقيبة"] },
  { kind: "text", display: "اكتب: ملاكمة", accepted: ["ملاكمة"] },
  { kind: "text", display: "اكتب: مصارعة", accepted: ["مصارعة"] },
  { kind: "text", display: "اكتب: سباحة", accepted: ["سباحة"] },
  { kind: "text", display: "اكتب: جري", accepted: ["جري"] },
  { kind: "text", display: "اكتب: قفز", accepted: ["قفز"] },
  { kind: "text", display: "اكتب: تزلج", accepted: ["تزلج"] },
  { kind: "text", display: "اكتب: غطس", accepted: ["غطس"] },
  { kind: "text", display: "اكتب: تنس", accepted: ["تنس"] },
  { kind: "text", display: "اكتب: اسكواش", accepted: ["اسكواش"] },
  { kind: "text", display: "اكتب: سعادة", accepted: ["سعادة"] },
  { kind: "text", display: "اكتب: حزن", accepted: ["حزن"] },
  { kind: "text", display: "اكتب: غضب", accepted: ["غضب"] },
  { kind: "text", display: "اكتب: خوف", accepted: ["خوف"] },
  { kind: "text", display: "اكتب: قلق", accepted: ["قلق"] },
  { kind: "text", display: "اكتب: فرح", accepted: ["فرح"] },
  { kind: "text", display: "اكتب: حب", accepted: ["حب"] },
  { kind: "text", display: "اكتب: كره", accepted: ["كره"] },
  { kind: "text", display: "اكتب: دهشة", accepted: ["دهشة"] },
  { kind: "text", display: "اكتب: ملل", accepted: ["ملل"] },
  { kind: "text", display: "اكتب: حماس", accepted: ["حماس"] },
  { kind: "text", display: "اكتب: فخر", accepted: ["فخر"] },
  { kind: "text", display: "اكتب: خجل", accepted: ["خجل"] },
  { kind: "text", display: "اكتب: فستان", accepted: ["فستان"] },
  { kind: "text", display: "اكتب: جاكيت", accepted: ["جاكيت"] },
  { kind: "text", display: "اكتب: بدلة", accepted: ["بدلة"] },
  { kind: "text", display: "اكتب: معطف", accepted: ["معطف"] },
  { kind: "text", display: "اكتب: شال", accepted: ["شال"] },
  { kind: "text", display: "اكتب: حجاب", accepted: ["حجاب"] },
  { kind: "text", display: "اكتب: طرحة", accepted: ["طرحة"] },
  { kind: "text", display: "اكتب: صندل", accepted: ["صندل"] },
  { kind: "text", display: "اكتب: قطار", accepted: ["قطار"] },
  { kind: "text", display: "اكتب: باص", accepted: ["باص"] },
  { kind: "text", display: "اكتب: سفينة", accepted: ["سفينة"] },
  { kind: "text", display: "اكتب: يخت", accepted: ["يخت"] },
  { kind: "text", display: "اكتب: مترو", accepted: ["مترو"] },
  { kind: "text", display: "اكتب: تاكسي", accepted: ["تاكسي"] },
  { kind: "text", display: "اكتب: شاحنة", accepted: ["شاحنة"] },
  { kind: "text", display: "اكتب: عود", accepted: ["عود"] },
  { kind: "text", display: "اكتب: طبلة", accepted: ["طبلة"] },
  { kind: "text", display: "اكتب: كمان", accepted: ["كمان"] },
  { kind: "text", display: "اكتب: بيانو", accepted: ["بيانو"] },
  { kind: "text", display: "اكتب: غيتار", accepted: ["غيتار"] },
  { kind: "text", display: "اكتب: ناي", accepted: ["ناي"] },
  { kind: "text", display: "اكتب: مزمار", accepted: ["مزمار"] },
  { kind: "text", display: "اكتب: طبل", accepted: ["طبل"] },
  { kind: "text", display: "اكتب: دف", accepted: ["دف"] },
  { kind: "text", display: "اكتب: مذنب", accepted: ["مذنب"] },
  { kind: "text", display: "اكتب: مجرة", accepted: ["مجرة"] },
  { kind: "text", display: "اكتب: المريخ", accepted: ["المريخ"] },
  { kind: "text", display: "اكتب: زحل", accepted: ["زحل"] },
  { kind: "text", display: "اكتب: المشتري", accepted: ["المشتري"] },
  { kind: "text", display: "اكتب: أورانوس", accepted: ["أورانوس"] },
  { kind: "text", display: "اكتب: نبتون", accepted: ["نبتون"] },
  { kind: "text", display: "اكتب: بلوتو", accepted: ["بلوتو"] },
  { kind: "text", display: "اكتب: دائرة", accepted: ["دائرة"] },
  { kind: "text", display: "اكتب: مربع", accepted: ["مربع"] },
  { kind: "text", display: "اكتب: مثلث", accepted: ["مثلث"] },
  { kind: "text", display: "اكتب: مستطيل", accepted: ["مستطيل"] },
  { kind: "text", display: "اكتب: معين", accepted: ["معين"] },
  { kind: "text", display: "اكتب: أب", accepted: ["أب"] },
  { kind: "text", display: "اكتب: أم", accepted: ["أم"] },
  { kind: "text", display: "اكتب: أخ", accepted: ["أخ"] },
  { kind: "text", display: "اكتب: أخت", accepted: ["أخت"] },
  { kind: "text", display: "اكتب: جد", accepted: ["جد"] },
  { kind: "text", display: "اكتب: جدة", accepted: ["جدة"] },
  { kind: "text", display: "اكتب: عم", accepted: ["عم"] },
  { kind: "text", display: "اكتب: عمة", accepted: ["عمة"] },
  { kind: "text", display: "اكتب: خال", accepted: ["خال"] },
  { kind: "text", display: "اكتب: خالة", accepted: ["خالة"] },
  { kind: "text", display: "اكتب: زوج", accepted: ["زوج"] },
  { kind: "text", display: "اكتب: زوجة", accepted: ["زوجة"] },
  { kind: "text", display: "اكتب: كبسة", accepted: ["كبسة"] },
  { kind: "text", display: "اكتب: مندي", accepted: ["مندي"] },
  { kind: "text", display: "اكتب: برياني", accepted: ["برياني"] },
  { kind: "text", display: "اكتب: شاورما", accepted: ["شاورما"] },
  { kind: "text", display: "اكتب: فلافل", accepted: ["فلافل"] },
  { kind: "text", display: "اكتب: حمص", accepted: ["حمص"] },
  { kind: "text", display: "اكتب: متبل", accepted: ["متبل"] },
  { kind: "text", display: "اكتب: كنافة", accepted: ["كنافة"] },
  { kind: "text", display: "اكتب: بقلاوة", accepted: ["بقلاوة"] },
  { kind: "text", display: "اكتب: معمول", accepted: ["معمول"] },
  { kind: "text", display: "اكتب: تمر", accepted: ["تمر"] },
  { kind: "text", display: "اكتب: خبز", accepted: ["خبز"] },
  { kind: "text", display: "اكتب: رز", accepted: ["رز"] },
  { kind: "text", display: "اكتب: مكرونة", accepted: ["مكرونة"] },
  { kind: "text", display: "اكتب: بيتزا", accepted: ["بيتزا"] },
  { kind: "text", display: "اكتب: برغر", accepted: ["برغر"] },
  { kind: "text", display: "اكتب: سلطة", accepted: ["سلطة"] },
  { kind: "text", display: "اكتب: شوربة", accepted: ["شوربة"] },
  { kind: "text", display: "اكتب: شاي", accepted: ["شاي"] },
  { kind: "text", display: "اكتب: عصير", accepted: ["عصير"] },
  { kind: "text", display: "اكتب: حليب", accepted: ["حليب"] },
  { kind: "text", display: "اكتب: كركديه", accepted: ["كركديه"] },
  { kind: "text", display: "اكتب: سحلب", accepted: ["سحلب"] },
  { kind: "text", display: "اكتب: تلفاز", accepted: ["تلفاز"] },
  { kind: "text", display: "اكتب: لابتوب", accepted: ["لابتوب"] },
  { kind: "text", display: "اكتب: جوال", accepted: ["جوال"] },
  { kind: "text", display: "اكتب: سماعة", accepted: ["سماعة"] },
  { kind: "text", display: "اكتب: كاميرا", accepted: ["كاميرا"] },
  { kind: "text", display: "اكتب: مايكروفون", accepted: ["مايكروفون"] },
  { kind: "text", display: "اكتب: طابعة", accepted: ["طابعة"] },
  { kind: "text", display: "اكتب: راوتر", accepted: ["راوتر"] },
  { kind: "text", display: "اكتب: ريموت", accepted: ["ريموت"] },
  { kind: "text", display: "اكتب: نملة", accepted: ["نملة"] },
  { kind: "text", display: "اكتب: نحلة", accepted: ["نحلة"] },
  { kind: "text", display: "اكتب: عنكبوت", accepted: ["عنكبوت"] },
  { kind: "text", display: "اكتب: صرصور", accepted: ["صرصور"] },
  { kind: "text", display: "اكتب: يعسوب", accepted: ["يعسوب"] },
  { kind: "text", display: "اكتب: جراد", accepted: ["جراد"] },
  { kind: "text", display: "اكتب: بعوضة", accepted: ["بعوضة"] },
  { kind: "text", display: "اكتب: فراش", accepted: ["فراش"] },
  { kind: "text", display: "اكتب: دعسوقة", accepted: ["دعسوقة"] },
  { kind: "text", display: "اكتب: سرطان", accepted: ["سرطان"] },
  { kind: "text", display: "اكتب: قرش", accepted: ["قرش"] },
  { kind: "text", display: "اكتب: دولفين", accepted: ["دولفين"] },
  { kind: "text", display: "اكتب: حوت", accepted: ["حوت"] },
  { kind: "text", display: "اكتب: نجم البحر", accepted: ["نجم البحر"] },
  { kind: "text", display: "اكتب: قنديل البحر", accepted: ["قنديل البحر"] },
  { kind: "text", display: "اكتب: محار", accepted: ["محار"] },
  { kind: "text", display: "اكتب: سلطعون", accepted: ["سلطعون"] },
  { kind: "text", display: "اكتب: أخطبوط بحري", accepted: ["أخطبوط بحري"] },
  { kind: "text", display: "اكتب: حبار", accepted: ["حبار"] },
  { kind: "text", display: "اكتب: سمك", accepted: ["سمك"] },
  { kind: "text", display: "اكتب: ملعقة", accepted: ["ملعقة"] },
  { kind: "text", display: "اكتب: شوكة", accepted: ["شوكة"] },
  { kind: "text", display: "اكتب: سكين", accepted: ["سكين"] },
  { kind: "text", display: "اكتب: طبق", accepted: ["طبق"] },
  { kind: "text", display: "اكتب: كوب", accepted: ["كوب"] },
  { kind: "text", display: "اكتب: إبريق", accepted: ["إبريق"] },
  { kind: "text", display: "اكتب: مقلاة", accepted: ["مقلاة"] },
  { kind: "text", display: "اكتب: فرن", accepted: ["فرن"] },
  { kind: "text", display: "اكتب: ميكروويف", accepted: ["ميكروويف"] },
  { kind: "text", display: "اكتب: خلاط", accepted: ["خلاط"] },
  { kind: "text", display: "اكتب: أريكة", accepted: ["أريكة"] },
  { kind: "text", display: "اكتب: رف", accepted: ["رف"] },
  { kind: "text", display: "اكتب: درج", accepted: ["درج"] },
  { kind: "text", display: "اكتب: خزنة", accepted: ["خزنة"] },
  { kind: "text", display: "اكتب: سلم", accepted: ["سلم"] },
  { kind: "text", display: "اكتب: قصر", accepted: ["قصر"] },
  { kind: "text", display: "اكتب: كوخ", accepted: ["كوخ"] },
  { kind: "text", display: "اكتب: ناطحة سحاب", accepted: ["ناطحة سحاب"] },
  { kind: "text", display: "اكتب: جسر", accepted: ["جسر"] },
  { kind: "text", display: "اكتب: نفق", accepted: ["نفق"] },
  { kind: "text", display: "اكتب: مصنع", accepted: ["مصنع"] },
  { kind: "text", display: "اكتب: مستشفى", accepted: ["مستشفى"] },
  { kind: "text", display: "اكتب: مكتبة", accepted: ["مكتبة"] },
  { kind: "text", display: "اكتب: متحف", accepted: ["متحف"] },
  { kind: "text", display: "اكتب: مسجد", accepted: ["مسجد"] },
  { kind: "text", display: "اكتب: كنيسة", accepted: ["كنيسة"] },
  { kind: "text", display: "اكتب: محطة", accepted: ["محطة"] },
  { kind: "text", display: "اكتب: مطار", accepted: ["مطار"] },
  { kind: "text", display: "اكتب: ميناء", accepted: ["ميناء"] },
  { kind: "text", display: "اكتب: كويكب", accepted: ["كويكب"] },
  { kind: "text", display: "اكتب: نيزك", accepted: ["نيزك"] },
  { kind: "text", display: "اكتب: ثقب أسود", accepted: ["ثقب أسود"] },
  { kind: "text", display: "اكتب: مذنب صغير", accepted: ["مذنب صغير"] },
  { kind: "text", display: "اكتب: شاشة", accepted: ["شاشة"] },
  { kind: "text", display: "اكتب: لوحة مفاتيح", accepted: ["لوحة مفاتيح"] },
  { kind: "text", display: "اكتب: فأرة الحاسوب", accepted: ["فأرة الحاسوب"] },
  { kind: "text", display: "اكتب: سماعات", accepted: ["سماعات"] },
  { kind: "text", display: "اكتب: شاحن", accepted: ["شاحن"] },
  { kind: "text", display: "اكتب: بطارية", accepted: ["بطارية"] },
  { kind: "text", display: "اكتب: قرص صلب", accepted: ["قرص صلب"] },
  { kind: "text", display: "اكتب: مضرب", accepted: ["مضرب"] },
  { kind: "text", display: "اكتب: شبكة", accepted: ["شبكة"] },
  { kind: "text", display: "اكتب: خوذة", accepted: ["خوذة"] },
  { kind: "text", display: "اكتب: قفازات", accepted: ["قفازات"] },
  { kind: "text", display: "اكتب: كرة قدم", accepted: ["كرة قدم"] },
  { kind: "text", display: "اكتب: غيرة", accepted: ["غيرة"] },
  { kind: "text", display: "اكتب: ندم", accepted: ["ندم"] },
  { kind: "text", display: "اكتب: امتنان", accepted: ["امتنان"] },
  { kind: "text", display: "اكتب: حيرة", accepted: ["حيرة"] },
  { kind: "text", display: "اكتب: توتر", accepted: ["توتر"] },
  { kind: "text", display: "اكتب: راحة", accepted: ["راحة"] },
  { kind: "text", display: "اكتب: ثقة", accepted: ["ثقة"] },
  { kind: "text", display: "اكتب: يأس", accepted: ["يأس"] },
  { kind: "text", display: "اكتب: صيدلي", accepted: ["صيدلي"] },
  { kind: "text", display: "اكتب: محاسب", accepted: ["محاسب"] },
  { kind: "text", display: "اكتب: مبرمج", accepted: ["مبرمج"] },
  { kind: "text", display: "اكتب: مصمم", accepted: ["مصمم"] },
  { kind: "text", display: "اكتب: حاجب", accepted: ["حاجب"] },
  { kind: "text", display: "اكتب: رمش", accepted: ["رمش"] },
  { kind: "text", display: "اكتب: خد", accepted: ["خد"] },
  { kind: "text", display: "اكتب: ذقن", accepted: ["ذقن"] },
  { kind: "text", display: "اكتب: رقبة", accepted: ["رقبة"] },
  { kind: "text", display: "اكتب: صدر", accepted: ["صدر"] },
  { kind: "text", display: "اكتب: ساعد", accepted: ["ساعد"] },
  { kind: "text", display: "اكتب: معصم", accepted: ["معصم"] },
  { kind: "text", display: "اكتب: كاحل", accepted: ["كاحل"] },
  { kind: "text", display: "اكتب: هضبة", accepted: ["هضبة"] },
  { kind: "text", display: "اكتب: سهل", accepted: ["سهل"] },
  { kind: "text", display: "اكتب: وادي", accepted: ["وادي"] },
  { kind: "text", display: "اكتب: جزيرة", accepted: ["جزيرة"] },
  { kind: "text", display: "اكتب: شبه جزيرة", accepted: ["شبه جزيرة"] },
  { kind: "text", display: "اكتب: برزخ", accepted: ["برزخ"] },
  { kind: "text", display: "اكتب: دراجة نارية", accepted: ["دراجة نارية"] },
  { kind: "text", display: "اكتب: غواصة", accepted: ["غواصة"] },
  { kind: "text", display: "اكتب: منطاد", accepted: ["منطاد"] },
  { kind: "text", display: "اكتب: مظلي", accepted: ["مظلي"] },
  { kind: "text", display: "اكتب: مطرقة", accepted: ["مطرقة"] },
  { kind: "text", display: "اكتب: مفك", accepted: ["مفك"] },
  { kind: "text", display: "اكتب: منشار", accepted: ["منشار"] },
  { kind: "text", display: "اكتب: كماشة", accepted: ["كماشة"] },
  { kind: "text", display: "اكتب: بطريق", accepted: ["بطريق"] },
  { kind: "text", display: "اكتب: كنغر", accepted: ["كنغر"] },
  { kind: "text", display: "اكتب: كوالا", accepted: ["كوالا"] },
  { kind: "text", display: "اكتب: تمساح", accepted: ["تمساح"] },
  { kind: "text", display: "اكتب: سحلية", accepted: ["سحلية"] },
  { kind: "text", display: "اكتب: ضفدع", accepted: ["ضفدع"] },
  { kind: "text", display: "اكتب: حرباء", accepted: ["حرباء"] },
  { kind: "text", display: "اكتب: خفاش", accepted: ["خفاش"] },
  { kind: "text", display: "اكتب: قنفذ", accepted: ["قنفذ"] },
  { kind: "text", display: "اكتب: سنجاب", accepted: ["سنجاب"] },
  { kind: "text", display: "اكتب: غزال", accepted: ["غزال"] },
  { kind: "text", display: "اكتب: وعل", accepted: ["وعل"] },
  { kind: "text", display: "اكتب: جاموس", accepted: ["جاموس"] },
  { kind: "text", display: "اكتب: فرس النهر", accepted: ["فرس النهر"] },
  { kind: "text", display: "اكتب: وحيد القرن", accepted: ["وحيد القرن"] },
  { kind: "text", display: "اكتب: بجعة", accepted: ["بجعة"] },
  { kind: "text", display: "اكتب: نعامة", accepted: ["نعامة"] },
  { kind: "text", display: "اكتب: طاووس", accepted: ["طاووس"] },
  { kind: "text", display: "اكتب: ببغاء", accepted: ["ببغاء"] },
  { kind: "text", display: "اكتب: صقر", accepted: ["صقر"] },
  { kind: "text", display: "اكتب: مرجان", accepted: ["مرجان"] },
  { kind: "text", display: "اكتب: إسفنج بحري", accepted: ["إسفنج بحري"] },
  { kind: "text", display: "اكتب: حورية البحر", accepted: ["حورية البحر"] },
  { kind: "text", display: "اكتب: سمك القرش", accepted: ["سمك القرش"] },
  { kind: "text", display: "اكتب: سمك أبو سيف", accepted: ["سمك أبو سيف"] },
  { kind: "text", display: "اكتب: فلين", accepted: ["فلين"] },
  { kind: "text", display: "اكتب: زجاج", accepted: ["زجاج"] },
  { kind: "text", display: "اكتب: خشب", accepted: ["خشب"] },
  { kind: "text", display: "اكتب: معدن", accepted: ["معدن"] },
  { kind: "text", display: "اكتب: بلاستيك", accepted: ["بلاستيك"] },
  { kind: "text", display: "اكتب: قماش", accepted: ["قماش"] },
  { kind: "text", display: "اكتب: جلد", accepted: ["جلد"] },
  { kind: "text", display: "اكتب: حرير", accepted: ["حرير"] },
  { kind: "text", display: "اكتب: صوف", accepted: ["صوف"] },
  { kind: "text", display: "اكتب: قطن", accepted: ["قطن"] },
  { kind: "text", display: "اكتب: مصباح يدوي", accepted: ["مصباح يدوي"] },
  { kind: "text", display: "اكتب: بطارية شحن", accepted: ["بطارية شحن"] },
  { kind: "text", display: "اكتب: كابل", accepted: ["كابل"] },
  { kind: "text", display: "اكتب: محول كهرباء", accepted: ["محول كهرباء"] },
  { kind: "text", display: "اكتب: مفتاح كهرباء", accepted: ["مفتاح كهرباء"] },
  { kind: "text", display: "اكتب: سجادة", accepted: ["سجادة"] },
  { kind: "text", display: "اكتب: ستارة", accepted: ["ستارة"] },
  { kind: "text", display: "اكتب: لوحة فنية", accepted: ["لوحة فنية"] },
  { kind: "text", display: "اكتب: تحفة", accepted: ["تحفة"] },
  { kind: "text", display: "اكتب: مزهرية", accepted: ["مزهرية"] },
  { kind: "text", display: "اكتب: برج مراقبة", accepted: ["برج مراقبة"] },
  { kind: "text", display: "اكتب: فندق", accepted: ["فندق"] },
  { kind: "text", display: "اكتب: مبنى", accepted: ["مبنى"] },
  { kind: "text", display: "اكتب: محل", accepted: ["محل"] },
  { kind: "text", display: "اكتب: سوق", accepted: ["سوق"] },
  { kind: "text", display: "اكتب: مقهى", accepted: ["مقهى"] },
  { kind: "text", display: "اكتب: مطعم", accepted: ["مطعم"] },
  { kind: "text", display: "اكتب: صيدلية", accepted: ["صيدلية"] },
  { kind: "text", display: "اكتب: بنك", accepted: ["بنك"] },
  { kind: "text", display: "اكتب: بريد", accepted: ["بريد"] },
  { kind: "text", display: "اكتب: مزرعة", accepted: ["مزرعة"] },
  { kind: "text", display: "اكتب: بستان", accepted: ["بستان"] },
  { kind: "text", display: "اكتب: حقل", accepted: ["حقل"] },
  { kind: "text", display: "اكتب: كرم", accepted: ["كرم"] },
  { kind: "text", display: "اكتب: مشتل", accepted: ["مشتل"] },
  { kind: "text", display: "اكتب: شراع", accepted: ["شراع"] },
  { kind: "text", display: "اكتب: مرساة", accepted: ["مرساة"] },
  { kind: "text", display: "اكتب: رافعة", accepted: ["رافعة"] },
  { kind: "text", display: "اكتب: حفارة", accepted: ["حفارة"] },
  { kind: "text", display: "اكتب: جرافة", accepted: ["جرافة"] },
  { kind: "text", display: "اكتب: شاحنة نقل", accepted: ["شاحنة نقل"] },
  { kind: "text", display: "اكتب: عربة", accepted: ["عربة"] },
  { kind: "text", display: "اكتب: زلاجة", accepted: ["زلاجة"] },
  { kind: "text", display: "اكتب: مايوه", accepted: ["مايوه"] },
  { kind: "text", display: "اكتب: نظارة سباحة", accepted: ["نظارة سباحة"] },
  { kind: "text", display: "اكتب: زعانف", accepted: ["زعانف"] },
  { kind: "text", display: "اكتب: طوق نجاة", accepted: ["طوق نجاة"] },
  { kind: "text", display: "اكتب: حقيبة ظهر", accepted: ["حقيبة ظهر"] },
  { kind: "text", display: "اكتب: محفظة نقود", accepted: ["محفظة نقود"] },
  { kind: "text", display: "اكتب: مظلة شمسية", accepted: ["مظلة شمسية"] },
  { kind: "text", display: "اكتب: كوب حراري", accepted: ["كوب حراري"] },
  { kind: "text", display: "اكتب: ألغاز", accepted: ["ألغاز"] },
  { kind: "text", display: "اكتب: لعبة ورق", accepted: ["لعبة ورق"] },
  { kind: "text", display: "اكتب: دومينو", accepted: ["دومينو"] },
  { kind: "text", display: "اكتب: بازل", accepted: ["بازل"] },
  { kind: "text", display: "اكتب: لغز", accepted: ["لغز"] },
  { kind: "text", display: "اكتب: صاروخ", accepted: ["صاروخ"] },
  { kind: "text", display: "اكتب: قمر صناعي", accepted: ["قمر صناعي"] },
  { kind: "text", display: "اكتب: محطة فضائية", accepted: ["محطة فضائية"] },
  { kind: "text", display: "اكتب: رائد فضاء", accepted: ["رائد فضاء"] },
  { kind: "text", display: "اكتب: بدلة فضاء", accepted: ["بدلة فضاء"] },
  { kind: "text", display: "اكتب: وثيقة", accepted: ["وثيقة"] },
  { kind: "text", display: "اكتب: جواز سفر", accepted: ["جواز سفر"] },
  { kind: "text", display: "اكتب: بطاقة هوية", accepted: ["بطاقة هوية"] },
  { kind: "text", display: "اكتب: ختم", accepted: ["ختم"] },
  { kind: "text", display: "اكتب: توقيع", accepted: ["توقيع"] },
  { kind: "text", display: "اكتب: مصفاة", accepted: ["مصفاة"] },
  { kind: "text", display: "اكتب: خط أنابيب", accepted: ["خط أنابيب"] },
  { kind: "text", display: "اكتب: بئر نفط", accepted: ["بئر نفط"] },
  { kind: "text", display: "اكتب: منجم", accepted: ["منجم"] },
  { kind: "text", display: "اكتب: محجر", accepted: ["محجر"] },
  { kind: "text", display: "اكتب: جرس", accepted: ["جرس"] },
  { kind: "text", display: "اكتب: بوق", accepted: ["بوق"] },
  { kind: "text", display: "اكتب: صافرة", accepted: ["صافرة"] },
  { kind: "text", display: "اكتب: طبل كبير", accepted: ["طبل كبير"] },
  { kind: "text", display: "اكتب: دباسة ورق", accepted: ["دباسة ورق"] },
  { kind: "text", display: "اكتب: مشبك ورق", accepted: ["مشبك ورق"] },
  { kind: "text", display: "اكتب: لاصق شفاف", accepted: ["لاصق شفاف"] },
  { kind: "text", display: "اكتب: قلم رصاص", accepted: ["قلم رصاص"] },
  { kind: "text", display: "اكتب: قلم حبر", accepted: ["قلم حبر"] },
  { kind: "text", display: "اكتب: ألوان خشبية", accepted: ["ألوان خشبية"] },
  { kind: "text", display: "اكتب: ألوان مائية", accepted: ["ألوان مائية"] },
  { kind: "text", display: "اكتب: فرشاة رسم", accepted: ["فرشاة رسم"] },
  { kind: "text", display: "اكتب: لوحة رسم", accepted: ["لوحة رسم"] },
  { kind: "text", display: "اكتب: حامل رسم", accepted: ["حامل رسم"] },
  { kind: "text", display: "اكتب: أكورديون", accepted: ["أكورديون"] },
  { kind: "text", display: "اكتب: هارمونيكا", accepted: ["هارمونيكا"] },
  { kind: "text", display: "اكتب: تشيلو", accepted: ["تشيلو"] },
  { kind: "text", display: "اكتب: كونترباص", accepted: ["كونترباص"] },
  { kind: "text", display: "اكتب: أرغن", accepted: ["أرغن"] },
  { kind: "text", display: "اكتب: جلجل", accepted: ["جلجل"] },
  { kind: "text", display: "اكتب: دف صغير", accepted: ["دف صغير"] },
  { kind: "text", display: "اكتب: بوق نحاسي", accepted: ["بوق نحاسي"] },
  { kind: "text", display: "اكتب: ترومبيت", accepted: ["ترومبيت"] },
  { kind: "text", display: "اكتب: ساكسفون", accepted: ["ساكسفون"] },
  { kind: "text", display: "اكتب: قفطان", accepted: ["قفطان"] },
  { kind: "text", display: "اكتب: عباءة", accepted: ["عباءة"] },
  { kind: "text", display: "اكتب: جلباب", accepted: ["جلباب"] },
  { kind: "text", display: "اكتب: بدلة رسمية", accepted: ["بدلة رسمية"] },
  { kind: "text", display: "اكتب: ربطة عنق", accepted: ["ربطة عنق"] },
  { kind: "text", display: "اكتب: حذاء رياضي", accepted: ["حذاء رياضي"] },
  { kind: "text", display: "اكتب: نعال", accepted: ["نعال"] },
  { kind: "text", display: "اكتب: جوارب طويلة", accepted: ["جوارب طويلة"] },
  { kind: "text", display: "اكتب: سترة جلد", accepted: ["سترة جلد"] },
  { kind: "text", display: "اكتب: بيجاما", accepted: ["بيجاما"] },
  { kind: "text", display: "اكتب: محضرة طعام", accepted: ["محضرة طعام"] },
  { kind: "text", display: "اكتب: قلاية هوائية", accepted: ["قلاية هوائية"] },
  { kind: "text", display: "اكتب: آلة قهوة", accepted: ["آلة قهوة"] },
  { kind: "text", display: "اكتب: عصارة فواكه", accepted: ["عصارة فواكه"] },
  { kind: "text", display: "اكتب: ميزان مطبخ", accepted: ["ميزان مطبخ"] },
  { kind: "text", display: "اكتب: لوح تقطيع", accepted: ["لوح تقطيع"] },
  { kind: "text", display: "اكتب: قمع", accepted: ["قمع"] },
  { kind: "text", display: "اكتب: ملقط طعام", accepted: ["ملقط طعام"] },
  { kind: "text", display: "اكتب: فتاحة علب", accepted: ["فتاحة علب"] },
  { kind: "text", display: "اكتب: دلتا", accepted: ["دلتا"] },
  { kind: "text", display: "اكتب: خليج", accepted: ["خليج"] },
  { kind: "text", display: "اكتب: مضيق", accepted: ["مضيق"] },
  { kind: "text", display: "اكتب: تلة", accepted: ["تلة"] },
  { kind: "text", display: "اكتب: منحدر", accepted: ["منحدر"] },
  { kind: "text", display: "اكتب: كثيب رملي", accepted: ["كثيب رملي"] },
  { kind: "text", display: "اكتب: سهل ساحلي", accepted: ["سهل ساحلي"] },
  { kind: "text", display: "اكتب: حاجز مرجاني", accepted: ["حاجز مرجاني"] },
  { kind: "text", display: "اكتب: بركان خامد", accepted: ["بركان خامد"] },
  { kind: "text", display: "اكتب: غابة استوائية", accepted: ["غابة استوائية"] },
  { kind: "text", display: "اكتب: الهيدروجين", accepted: ["الهيدروجين"] },
  { kind: "text", display: "اكتب: النيتروجين", accepted: ["النيتروجين"] },
  { kind: "text", display: "اكتب: الكربون", accepted: ["الكربون"] },
  { kind: "text", display: "اكتب: الصوديوم", accepted: ["الصوديوم"] },
  { kind: "text", display: "اكتب: الكالسيوم", accepted: ["الكالسيوم"] },
  { kind: "text", display: "اكتب: الذرة", accepted: ["الذرة"] },
  { kind: "text", display: "اكتب: الجزيء", accepted: ["الجزيء"] },
  { kind: "text", display: "اكتب: الإلكترون", accepted: ["الإلكترون"] },
  { kind: "text", display: "اكتب: البروتون", accepted: ["البروتون"] },
  { kind: "text", display: "اكتب: النواة", accepted: ["النواة"] },
  { kind: "text", display: "اكتب: عطارد الكوكب", accepted: ["عطارد الكوكب"] },
  { kind: "text", display: "اكتب: بروكسيما", accepted: ["بروكسيما"] },
  { kind: "text", display: "اكتب: الثقب الدودي", accepted: ["الثقب الدودي"] },
  { kind: "text", display: "اكتب: السديم", accepted: ["السديم"] },
  { kind: "text", display: "اكتب: النجم القزم", accepted: ["النجم القزم"] },
  { kind: "text", display: "اكتب: المستعر الأعظم", accepted: ["المستعر الأعظم"] },
  { kind: "text", display: "اكتب: الكوازار", accepted: ["الكوازار"] },
  { kind: "text", display: "اكتب: الأقمار الصناعية", accepted: ["الأقمار الصناعية"] },
  { kind: "text", display: "اكتب: تلسكوب", accepted: ["تلسكوب"] },
  { kind: "text", display: "اكتب: معالج", accepted: ["معالج"] },
  { kind: "text", display: "اكتب: ذاكرة عشوائية", accepted: ["ذاكرة عشوائية"] },
  { kind: "text", display: "اكتب: كرت شاشة", accepted: ["كرت شاشة"] },
  { kind: "text", display: "اكتب: لوحة أم", accepted: ["لوحة أم"] },
  { kind: "text", display: "اكتب: نظام تشغيل", accepted: ["نظام تشغيل"] },
  { kind: "text", display: "اكتب: تطبيق", accepted: ["تطبيق"] },
  { kind: "text", display: "اكتب: متصفح", accepted: ["متصفح"] },
  { kind: "text", display: "اكتب: خادم", accepted: ["خادم"] },
  { kind: "text", display: "اكتب: سحابة إلكترونية", accepted: ["سحابة إلكترونية"] },
  { kind: "text", display: "اكتب: رمز مرور", accepted: ["رمز مرور"] },
  { kind: "text", display: "اكتب: كرة يد", accepted: ["كرة يد"] },
  { kind: "text", display: "اكتب: كرة طاولة", accepted: ["كرة طاولة"] },
  { kind: "text", display: "اكتب: رمي الرمح", accepted: ["رمي الرمح"] },
  { kind: "text", display: "اكتب: رمي القرص", accepted: ["رمي القرص"] },
  { kind: "text", display: "اكتب: وثب طويل", accepted: ["وثب طويل"] },
  { kind: "text", display: "اكتب: وثب عالي", accepted: ["وثب عالي"] },
  { kind: "text", display: "اكتب: سباق حواجز", accepted: ["سباق حواجز"] },
  { kind: "text", display: "اكتب: تجديف", accepted: ["تجديف"] },
  { kind: "text", display: "اكتب: إبحار شراعي", accepted: ["إبحار شراعي"] },
  { kind: "text", display: "اكتب: رفع أثقال", accepted: ["رفع أثقال"] },
  { kind: "text", display: "اكتب: أم علي", accepted: ["أم علي"] },
  { kind: "text", display: "اكتب: بسبوسة", accepted: ["بسبوسة"] },
  { kind: "text", display: "اكتب: قطايف", accepted: ["قطايف"] },
  { kind: "text", display: "اكتب: لقيمات", accepted: ["لقيمات"] },
  { kind: "text", display: "اكتب: كعك عيد", accepted: ["كعك عيد"] },
  { kind: "text", display: "اكتب: بقلاوة فستق", accepted: ["بقلاوة فستق"] },
  { kind: "text", display: "اكتب: حلاوة طحينية", accepted: ["حلاوة طحينية"] },
  { kind: "text", display: "اكتب: دبس التمر", accepted: ["دبس التمر"] },
  { kind: "text", display: "اكتب: عصير مانجو", accepted: ["عصير مانجو"] },
  { kind: "text", display: "اكتب: شاي بالنعناع", accepted: ["شاي بالنعناع"] },
  { kind: "text", display: "اكتب: كرنب", accepted: ["كرنب"] },
  { kind: "text", display: "اكتب: سبانخ", accepted: ["سبانخ"] },
  { kind: "text", display: "اكتب: بامية", accepted: ["بامية"] },
  { kind: "text", display: "اكتب: فجل", accepted: ["فجل"] },
  { kind: "text", display: "اكتب: لفت", accepted: ["لفت"] },
  { kind: "text", display: "اكتب: شمام", accepted: ["شمام"] },
  { kind: "text", display: "اكتب: رمان", accepted: ["رمان"] },
  { kind: "text", display: "اكتب: تين", accepted: ["تين"] },
  { kind: "text", display: "اكتب: جوافة", accepted: ["جوافة"] },
  { kind: "text", display: "اكتب: كيوي", accepted: ["كيوي"] },
  { kind: "text", display: "اكتب: نخلة", accepted: ["نخلة"] },
  { kind: "text", display: "اكتب: سنديان", accepted: ["سنديان"] },
  { kind: "text", display: "اكتب: صنوبر", accepted: ["صنوبر"] },
  { kind: "text", display: "اكتب: أرز لبناني", accepted: ["أرز لبناني"] },
  { kind: "text", display: "اكتب: بامبو", accepted: ["بامبو"] },
  { kind: "text", display: "اكتب: صبار", accepted: ["صبار"] },
  { kind: "text", display: "اكتب: ياسمين", accepted: ["ياسمين"] },
  { kind: "text", display: "اكتب: ورد جوري", accepted: ["ورد جوري"] },
  { kind: "text", display: "اكتب: زنبق", accepted: ["زنبق"] },
  { kind: "text", display: "اكتب: أقحوان", accepted: ["أقحوان"] },
  { kind: "text", display: "اكتب: الذهب", accepted: ["الذهب"] },
  { kind: "text", display: "اكتب: الفضة", accepted: ["الفضة"] },
  { kind: "text", display: "اكتب: النحاس", accepted: ["النحاس"] },
  { kind: "text", display: "اكتب: الحديد الخام", accepted: ["الحديد الخام"] },
  { kind: "text", display: "اكتب: الألماس", accepted: ["الألماس"] },
  { kind: "text", display: "اكتب: الياقوت", accepted: ["الياقوت"] },
  { kind: "text", display: "اكتب: الزمرد", accepted: ["الزمرد"] },
  { kind: "text", display: "اكتب: اللؤلؤ الطبيعي", accepted: ["اللؤلؤ الطبيعي"] },
  { kind: "text", display: "اكتب: الفيروز", accepted: ["الفيروز"] },
  { kind: "text", display: "اكتب: العقيق", accepted: ["العقيق"] },
  { kind: "text", display: "اكتب: صقيع", accepted: ["صقيع"] },
  { kind: "text", display: "اكتب: ندى", accepted: ["ندى"] },
  { kind: "text", display: "اكتب: برد حبيبي", accepted: ["برد حبيبي"] },
  { kind: "text", display: "اكتب: غيوم ركامية", accepted: ["غيوم ركامية"] },
  { kind: "text", display: "اكتب: موجة حر", accepted: ["موجة حر"] },
  { kind: "text", display: "اكتب: موجة برد", accepted: ["موجة برد"] },
  { kind: "text", display: "اكتب: تسونامي", accepted: ["تسونامي"] },
  { kind: "text", display: "اكتب: انهيار ثلجي", accepted: ["انهيار ثلجي"] },
  { kind: "text", display: "اكتب: جفاف", accepted: ["جفاف"] },
  { kind: "text", display: "اكتب: فيضان مفاجئ", accepted: ["فيضان مفاجئ"] },
  { kind: "text", display: "اكتب: شبه منحرف", accepted: ["شبه منحرف"] },
  { kind: "text", display: "اكتب: متوازي أضلاع", accepted: ["متوازي أضلاع"] },
  { kind: "text", display: "اكتب: مخروط", accepted: ["مخروط"] },
  { kind: "text", display: "اكتب: أسطوانة", accepted: ["أسطوانة"] },
  { kind: "text", display: "اكتب: هرم", accepted: ["هرم"] },
  { kind: "text", display: "اكتب: مكعب", accepted: ["مكعب"] },
  { kind: "text", display: "اكتب: كرة هندسية", accepted: ["كرة هندسية"] },
  { kind: "text", display: "اكتب: معين هندسي", accepted: ["معين هندسي"] },
  { kind: "text", display: "اكتب: سداسي", accepted: ["سداسي"] },
  { kind: "text", display: "اكتب: ثماني الأضلاع", accepted: ["ثماني الأضلاع"] },
  { kind: "text", display: "اكتب: محرك السيارة", accepted: ["محرك السيارة"] },
  { kind: "text", display: "اكتب: إطار السيارة", accepted: ["إطار السيارة"] },
  { kind: "text", display: "اكتب: مقود", accepted: ["مقود"] },
  { kind: "text", display: "اكتب: ناقل الحركة", accepted: ["ناقل الحركة"] },
  { kind: "text", display: "اكتب: مكابح", accepted: ["مكابح"] },
  { kind: "text", display: "اكتب: زجاج أمامي", accepted: ["زجاج أمامي"] },
  { kind: "text", display: "اكتب: مصباح أمامي", accepted: ["مصباح أمامي"] },
  { kind: "text", display: "اكتب: صندوق السيارة", accepted: ["صندوق السيارة"] },
  { kind: "text", display: "اكتب: حزام أمان", accepted: ["حزام أمان"] },
  { kind: "text", display: "اكتب: وسادة هوائية", accepted: ["وسادة هوائية"] },
  { kind: "text", display: "اكتب: منشار كهربائي", accepted: ["منشار كهربائي"] },
  { kind: "text", display: "اكتب: مثقاب", accepted: ["مثقاب"] },
  { kind: "text", display: "اكتب: مطرقة خشبية", accepted: ["مطرقة خشبية"] },
  { kind: "text", display: "اكتب: سنفرة", accepted: ["سنفرة"] },
  { kind: "text", display: "اكتب: غراء خشب", accepted: ["غراء خشب"] },
  { kind: "text", display: "اكتب: مسمار برغي", accepted: ["مسمار برغي"] },
  { kind: "text", display: "اكتب: لحام", accepted: ["لحام"] },
  { kind: "text", display: "اكتب: كماشة قطع", accepted: ["كماشة قطع"] },
  { kind: "text", display: "اكتب: متر قياس", accepted: ["متر قياس"] },
  { kind: "text", display: "اكتب: ميزان ماء", accepted: ["ميزان ماء"] },
  { kind: "text", display: "اكتب: كاراتيه", accepted: ["كاراتيه"] },
  { kind: "text", display: "اكتب: تايكوندو", accepted: ["تايكوندو"] },
  { kind: "text", display: "اكتب: جودو", accepted: ["جودو"] },
  { kind: "text", display: "اكتب: كونغ فو", accepted: ["كونغ فو"] },
  { kind: "text", display: "اكتب: كيك بوكسينغ", accepted: ["كيك بوكسينغ"] },
  { kind: "text", display: "اكتب: مصارعة حرة", accepted: ["مصارعة حرة"] },
  { kind: "text", display: "اكتب: سلاح مبارزة", accepted: ["سلاح مبارزة"] },
  { kind: "text", display: "اكتب: درع واقي", accepted: ["درع واقي"] },
  { kind: "text", display: "اكتب: حزام أبيض", accepted: ["حزام أبيض"] },
  { kind: "text", display: "اكتب: حزام أسود", accepted: ["حزام أسود"] },
  { kind: "text", display: "اكتب: موقد غاز", accepted: ["موقد غاز"] },
  { kind: "text", display: "اكتب: كشاف يدوي", accepted: ["كشاف يدوي"] },
  { kind: "text", display: "اكتب: بوصلة تخييم", accepted: ["بوصلة تخييم"] },
  { kind: "text", display: "اكتب: حقيبة نوم", accepted: ["حقيبة نوم"] },
  { kind: "text", display: "اكتب: خيمة قماشية", accepted: ["خيمة قماشية"] },
  { kind: "text", display: "اكتب: حبل تسلق جبال", accepted: ["حبل تسلق جبال"] },
  { kind: "text", display: "اكتب: قارب مطاطي", accepted: ["قارب مطاطي"] },
  { kind: "text", display: "اكتب: نظارة رؤية ليلية", accepted: ["نظارة رؤية ليلية"] },
  { kind: "text", display: "اكتب: مصفاة ماء", accepted: ["مصفاة ماء"] },
  { kind: "text", display: "اكتب: علبة إسعافات", accepted: ["علبة إسعافات"] },
  { kind: "text", display: "اكتب: شطرنج", accepted: ["شطرنج"] },
  { kind: "text", display: "اكتب: سلم وثعبان", accepted: ["سلم وثعبان"] },
  { kind: "text", display: "اكتب: مونوبولي", accepted: ["مونوبولي"] },
  { kind: "text", display: "اكتب: كلمات متقاطعة", accepted: ["كلمات متقاطعة"] },
  { kind: "text", display: "اكتب: بينغو", accepted: ["بينغو"] },
  { kind: "text", display: "اكتب: دومينو أسود", accepted: ["دومينو أسود"] },
  { kind: "text", display: "اكتب: طاولة زهر", accepted: ["طاولة زهر"] },
  { kind: "text", display: "اكتب: بلوت", accepted: ["بلوت"] },
  { kind: "text", display: "اكتب: كوتشينة", accepted: ["كوتشينة"] },
  { kind: "text", display: "اكتب: كلمة السر", accepted: ["كلمة السر"] },
  { kind: "text", display: "اكتب: مصور فوتوغرافي", accepted: ["مصور فوتوغرافي"] },
  { kind: "text", display: "اكتب: مهندس معماري", accepted: ["مهندس معماري"] },
  { kind: "text", display: "اكتب: مزارع", accepted: ["مزارع"] },
  { kind: "text", display: "اكتب: راعي", accepted: ["راعي"] },
  { kind: "text", display: "اكتب: صياد أسماك", accepted: ["صياد أسماك"] },
  { kind: "text", display: "اكتب: بستاني", accepted: ["بستاني"] },
  { kind: "text", display: "اكتب: سائق شاحنة", accepted: ["سائق شاحنة"] },
  { kind: "text", display: "اكتب: عامل بناء", accepted: ["عامل بناء"] },
  { kind: "text", display: "اكتب: مساح أراضي", accepted: ["مساح أراضي"] },
  { kind: "text", display: "اكتب: محقق خاص", accepted: ["محقق خاص"] },
  { kind: "text", display: "اكتب: مذيع رياضي", accepted: ["مذيع رياضي"] },
  { kind: "text", display: "اكتب: معلق صوتي", accepted: ["معلق صوتي"] },
  { kind: "text", display: "اكتب: مصلح سيارات", accepted: ["مصلح سيارات"] },
  { kind: "text", display: "اكتب: فني كهرباء", accepted: ["فني كهرباء"] },
  { kind: "text", display: "اكتب: سباك مياه", accepted: ["سباك مياه"] },
  { kind: "text", display: "اكتب: نجار أثاث", accepted: ["نجار أثاث"] },
  { kind: "text", display: "اكتب: خياط ملابس", accepted: ["خياط ملابس"] },
  { kind: "text", display: "اكتب: حارس أمن", accepted: ["حارس أمن"] },
  { kind: "text", display: "اكتب: مضيف طيران", accepted: ["مضيف طيران"] },
  { kind: "text", display: "اكتب: كابتن طائرة", accepted: ["كابتن طائرة"] },
  { kind: "text", display: "اكتب: ربان سفينة", accepted: ["ربان سفينة"] },
  { kind: "text", display: "اكتب: عامل مصنع", accepted: ["عامل مصنع"] },
  { kind: "text", display: "اكتب: منظار مقرب", accepted: ["منظار مقرب"] },
  { kind: "text", display: "اكتب: ميزان حرارة", accepted: ["ميزان حرارة"] },
  { kind: "text", display: "اكتب: جهاز قياس ضغط", accepted: ["جهاز قياس ضغط"] },
  { kind: "text", display: "اكتب: سماعة طبيب", accepted: ["سماعة طبيب"] },
  { kind: "text", display: "اكتب: حقنة طبية", accepted: ["حقنة طبية"] },
  { kind: "text", display: "اكتب: ضمادة جروح", accepted: ["ضمادة جروح"] },
  { kind: "text", display: "اكتب: جبيرة", accepted: ["جبيرة"] },
  { kind: "text", display: "اكتب: كرسي متحرك", accepted: ["كرسي متحرك"] },
  { kind: "text", display: "اكتب: عكاز", accepted: ["عكاز"] },
  { kind: "text", display: "اكتب: نظارة طبية", accepted: ["نظارة طبية"] },
  { kind: "text", display: "اكتب: سماعة أذن طبية", accepted: ["سماعة أذن طبية"] },
  { kind: "text", display: "اكتب: جهاز تنفس", accepted: ["جهاز تنفس"] },
  { kind: "text", display: "اكتب: سرير طبي", accepted: ["سرير طبي"] },
  { kind: "text", display: "اكتب: معطف طبي", accepted: ["معطف طبي"] },
  { kind: "text", display: "اكتب: قفازات طبية", accepted: ["قفازات طبية"] },
  { kind: "text", display: "اكتب: كمامة طبية", accepted: ["كمامة طبية"] },
  { kind: "text", display: "اكتب: محلول معقم", accepted: ["محلول معقم"] },
  { kind: "text", display: "اكتب: ترمومتر", accepted: ["ترمومتر"] },
  { kind: "text", display: "اكتب: مطهر جروح", accepted: ["مطهر جروح"] },
  { kind: "text", display: "اكتب: لاصق طبي", accepted: ["لاصق طبي"] },
  { kind: "text", display: "اكتب: بنفسج", accepted: ["بنفسج"] },
  { kind: "text", display: "اكتب: زعتر", accepted: ["زعتر"] },
  { kind: "text", display: "اكتب: ريحان", accepted: ["ريحان"] },
  { kind: "text", display: "اكتب: نعناع", accepted: ["نعناع"] },
  { kind: "text", display: "اكتب: إكليل الجبل", accepted: ["إكليل الجبل"] },
  { kind: "text", display: "اكتب: بابونج", accepted: ["بابونج"] },
  { kind: "text", display: "اكتب: خزامى", accepted: ["خزامى"] },
  { kind: "text", display: "اكتب: توليب", accepted: ["توليب"] },
  { kind: "text", display: "اكتب: دوار الشمس", accepted: ["دوار الشمس"] },
  { kind: "text", display: "اكتب: عصفر", accepted: ["عصفر"] },
  { kind: "text", display: "اكتب: أوركيد", accepted: ["أوركيد"] },
  { kind: "text", display: "اكتب: فل", accepted: ["فل"] },
  { kind: "text", display: "اكتب: كاديا", accepted: ["كاديا"] },
  { kind: "text", display: "اكتب: سرو", accepted: ["سرو"] },
  { kind: "text", display: "اكتب: أثل", accepted: ["أثل"] },
  { kind: "text", display: "اكتب: غار", accepted: ["غار"] },
  { kind: "text", display: "اكتب: جوز الهند", accepted: ["جوز الهند"] },
  { kind: "text", display: "اكتب: نخيل التمر", accepted: ["نخيل التمر"] },
  { kind: "text", display: "اكتب: شوكران", accepted: ["شوكران"] },
  { kind: "text", display: "اكتب: حنظل", accepted: ["حنظل"] },
  { kind: "text", display: "اكتب: حسون", accepted: ["حسون"] },
  { kind: "text", display: "اكتب: بلبل", accepted: ["بلبل"] },
  { kind: "text", display: "اكتب: كناري", accepted: ["كناري"] },
  { kind: "text", display: "اكتب: دوري", accepted: ["دوري"] },
  { kind: "text", display: "اكتب: غراب", accepted: ["غراب"] },
  { kind: "text", display: "اكتب: بوم", accepted: ["بوم"] },
  { kind: "text", display: "اكتب: لقلق", accepted: ["لقلق"] },
  { kind: "text", display: "اكتب: كركي", accepted: ["كركي"] },
  { kind: "text", display: "اكتب: إوز", accepted: ["إوز"] },
  { kind: "text", display: "اكتب: بط بري", accepted: ["بط بري"] },
  { kind: "text", display: "اكتب: طاووس أبيض", accepted: ["طاووس أبيض"] },
  { kind: "text", display: "اكتب: حمام زاجل", accepted: ["حمام زاجل"] },
  { kind: "text", display: "اكتب: صقر حر", accepted: ["صقر حر"] },
  { kind: "text", display: "اكتب: نسر ذهبي", accepted: ["نسر ذهبي"] },
  { kind: "text", display: "اكتب: عقاب", accepted: ["عقاب"] },
  { kind: "text", display: "اكتب: بجع", accepted: ["بجع"] },
  { kind: "text", display: "اكتب: فلامنغو", accepted: ["فلامنغو"] },
  { kind: "text", display: "اكتب: كاسر عظام", accepted: ["كاسر عظام"] },
  { kind: "text", display: "اكتب: وقواق", accepted: ["وقواق"] },
  { kind: "text", display: "اكتب: سنونو", accepted: ["سنونو"] },
  { kind: "text", display: "اكتب: أبو مقص", accepted: ["أبو مقص"] },
  { kind: "text", display: "اكتب: خنفساء", accepted: ["خنفساء"] },
  { kind: "text", display: "اكتب: فراشة ليلية", accepted: ["فراشة ليلية"] },
  { kind: "text", display: "اكتب: دودة القز", accepted: ["دودة القز"] },
  { kind: "text", display: "اكتب: صرصور طائر", accepted: ["صرصور طائر"] },
  { kind: "text", display: "اكتب: نملة نار", accepted: ["نملة نار"] },
  { kind: "text", display: "اكتب: نحلة طنانة", accepted: ["نحلة طنانة"] },
  { kind: "text", display: "اكتب: سرعوف", accepted: ["سرعوف"] },
  { kind: "text", display: "اكتب: أرضة", accepted: ["أرضة"] },
  { kind: "text", display: "اكتب: برغوث", accepted: ["برغوث"] },
  { kind: "text", display: "اكتب: ثعبان", accepted: ["ثعبان"] },
  { kind: "text", display: "اكتب: سلحفاة بحرية", accepted: ["سلحفاة بحرية"] },
  { kind: "text", display: "اكتب: تمساح النيل", accepted: ["تمساح النيل"] },
  { kind: "text", display: "اكتب: ورل", accepted: ["ورل"] },
  { kind: "text", display: "اكتب: سمندل", accepted: ["سمندل"] },
  { kind: "text", display: "اكتب: ضب", accepted: ["ضب"] },
  { kind: "text", display: "اكتب: حية رقطاء", accepted: ["حية رقطاء"] },
  { kind: "text", display: "اكتب: سحلية زرقاء", accepted: ["سحلية زرقاء"] },
  { kind: "text", display: "اكتب: تنين كومودو", accepted: ["تنين كومودو"] },
  { kind: "text", display: "اكتب: أفعى الكوبرا", accepted: ["أفعى الكوبرا"] },
  { kind: "text", display: "اكتب: عصا هوكي", accepted: ["عصا هوكي"] },
  { kind: "text", display: "اكتب: قفازات ملاكمة", accepted: ["قفازات ملاكمة"] },
  { kind: "text", display: "اكتب: حذاء تزلج", accepted: ["حذاء تزلج"] },
  { kind: "text", display: "اكتب: لوح تزلج", accepted: ["لوح تزلج"] },
  { kind: "text", display: "اكتب: دراجة جبلية", accepted: ["دراجة جبلية"] },
  { kind: "text", display: "اكتب: حبل قفز", accepted: ["حبل قفز"] },
  { kind: "text", display: "اكتب: وزن حديدي", accepted: ["وزن حديدي"] },
  { kind: "text", display: "اكتب: حصيرة يوغا", accepted: ["حصيرة يوغا"] },
  { kind: "text", display: "اكتب: كرة يوغا", accepted: ["كرة يوغا"] },
  { kind: "text", display: "اكتب: شريط مقاومة", accepted: ["شريط مقاومة"] },
  { kind: "text", display: "اكتب: عصا غولف", accepted: ["عصا غولف"] },
  { kind: "text", display: "اكتب: كرة غولف", accepted: ["كرة غولف"] },
  { kind: "text", display: "اكتب: مضرب اسكواش", accepted: ["مضرب اسكواش"] },
  { kind: "text", display: "اكتب: كرة اسكواش", accepted: ["كرة اسكواش"] },
  { kind: "text", display: "اكتب: حذاء كرة قدم", accepted: ["حذاء كرة قدم"] },
  { kind: "text", display: "اكتب: قميص فريق", accepted: ["قميص فريق"] },
  { kind: "text", display: "اكتب: شارة كابتن", accepted: ["شارة كابتن"] },
  { kind: "text", display: "اكتب: كأس بطولة", accepted: ["كأس بطولة"] },
  { kind: "text", display: "اكتب: ميدالية ذهبية", accepted: ["ميدالية ذهبية"] },
  { kind: "text", display: "اكتب: ميدالية فضية", accepted: ["ميدالية فضية"] },
  { kind: "text", display: "اكتب: فطيرة تفاح", accepted: ["فطيرة تفاح"] },
  { kind: "text", display: "اكتب: كعكة عيد ميلاد", accepted: ["كعكة عيد ميلاد"] },
  { kind: "text", display: "اكتب: بسكويت شوكولاتة", accepted: ["بسكويت شوكولاتة"] },
  { kind: "text", display: "اكتب: مثلجات فانيليا", accepted: ["مثلجات فانيليا"] },
  { kind: "text", display: "اكتب: عصير برتقال طازج", accepted: ["عصير برتقال طازج"] },
  { kind: "text", display: "اكتب: قهوة عربية", accepted: ["قهوة عربية"] },
  { kind: "text", display: "اكتب: قهوة تركية", accepted: ["قهوة تركية"] },
  { kind: "text", display: "اكتب: شاي أحمر", accepted: ["شاي أحمر"] },
  { kind: "text", display: "اكتب: ماء معدني", accepted: ["ماء معدني"] },
  { kind: "text", display: "اكتب: مشروب طاقة", accepted: ["مشروب طاقة"] },
  { kind: "text", display: "اكتب: سلطة خضراء", accepted: ["سلطة خضراء"] },
  { kind: "text", display: "اكتب: حساء عدس", accepted: ["حساء عدس"] },
  { kind: "text", display: "اكتب: بيتزا مارغريتا", accepted: ["بيتزا مارغريتا"] },
  { kind: "text", display: "اكتب: برغر لحم", accepted: ["برغر لحم"] },
  { kind: "text", display: "اكتب: دجاج مشوي", accepted: ["دجاج مشوي"] },
  { kind: "text", display: "اكتب: سمك مقلي", accepted: ["سمك مقلي"] },
  { kind: "text", display: "اكتب: أرز بسمتي", accepted: ["أرز بسمتي"] },
  { kind: "text", display: "اكتب: خبز بلدي", accepted: ["خبز بلدي"] },
  { kind: "text", display: "اكتب: معكرونة إيطالية", accepted: ["معكرونة إيطالية"] },
  { kind: "text", display: "اكتب: صلصة طماطم", accepted: ["صلصة طماطم"] },
  { kind: "text", display: "اكتب: سلة غسيل", accepted: ["سلة غسيل"] },
  { kind: "text", display: "اكتب: حبل غسيل", accepted: ["حبل غسيل"] },
  { kind: "text", display: "اكتب: مشبك غسيل", accepted: ["مشبك غسيل"] },
  { kind: "text", display: "اكتب: دلو ماء", accepted: ["دلو ماء"] },
  { kind: "text", display: "اكتب: ممسحة أرضية", accepted: ["ممسحة أرضية"] },
  { kind: "text", display: "اكتب: فرشاة تنظيف", accepted: ["فرشاة تنظيف"] },
  { kind: "text", display: "اكتب: إسفنجة غسيل", accepted: ["إسفنجة غسيل"] },
  { kind: "text", display: "اكتب: منظف زجاج", accepted: ["منظف زجاج"] },
  { kind: "text", display: "اكتب: معطر جو", accepted: ["معطر جو"] },
  { kind: "text", display: "اكتب: شمعة معطرة", accepted: ["شمعة معطرة"] },
  { kind: "text", display: "اكتب: وسادة أريكة", accepted: ["وسادة أريكة"] },
  { kind: "text", display: "اكتب: بطانية صوف", accepted: ["بطانية صوف"] },
  { kind: "text", display: "اكتب: مفرش سرير", accepted: ["مفرش سرير"] },
  { kind: "text", display: "اكتب: ستارة نافذة", accepted: ["ستارة نافذة"] },
  { kind: "text", display: "اكتب: سجادة صلاة", accepted: ["سجادة صلاة"] },
  { kind: "text", display: "اكتب: مسند قدم", accepted: ["مسند قدم"] },
  { kind: "text", display: "اكتب: طاولة قهوة", accepted: ["طاولة قهوة"] },
  { kind: "text", display: "اكتب: خزانة ملابس", accepted: ["خزانة ملابس"] },
  { kind: "text", display: "اكتب: مرآة حائط", accepted: ["مرآة حائط"] },
  { kind: "text", display: "اكتب: لوحة جدارية", accepted: ["لوحة جدارية"] },
  { kind: "text", display: "اكتب: تطبيق جوال", accepted: ["تطبيق جوال"] },
  { kind: "text", display: "اكتب: موقع إلكتروني", accepted: ["موقع إلكتروني"] },
  { kind: "text", display: "اكتب: قاعدة بيانات", accepted: ["قاعدة بيانات"] },
  { kind: "text", display: "اكتب: خوارزمية", accepted: ["خوارزمية"] },
  { kind: "text", display: "اكتب: ذكاء اصطناعي", accepted: ["ذكاء اصطناعي"] },
  { kind: "text", display: "اكتب: تعلم آلي", accepted: ["تعلم آلي"] },
  { kind: "text", display: "اكتب: واقع افتراضي", accepted: ["واقع افتراضي"] },
  { kind: "text", display: "اكتب: واقع معزز", accepted: ["واقع معزز"] },
  { kind: "text", display: "اكتب: طابعة ثلاثية الأبعاد", accepted: ["طابعة ثلاثية الأبعاد"] },
  { kind: "text", display: "اكتب: روبوت آلي", accepted: ["روبوت آلي"] },
  { kind: "text", display: "اكتب: شبكة لاسلكية", accepted: ["شبكة لاسلكية"] },
  { kind: "text", display: "اكتب: بلوتوث", accepted: ["بلوتوث"] },
  { kind: "text", display: "اكتب: كاميرا مراقبة", accepted: ["كاميرا مراقبة"] },
  { kind: "text", display: "اكتب: جرس ذكي", accepted: ["جرس ذكي"] },
  { kind: "text", display: "اكتب: ساعة ذكية", accepted: ["ساعة ذكية"] },
  { kind: "text", display: "اكتب: سماعة ذكية", accepted: ["سماعة ذكية"] },
  { kind: "text", display: "اكتب: مصباح ذكي", accepted: ["مصباح ذكي"] },
  { kind: "text", display: "اكتب: ثلاجة ذكية", accepted: ["ثلاجة ذكية"] },
  { kind: "text", display: "اكتب: سيارة كهربائية", accepted: ["سيارة كهربائية"] },
  { kind: "text", display: "اكتب: دراجة كهربائية", accepted: ["دراجة كهربائية"] },
  { kind: "text", display: "اكتب: سبورة ذكية", accepted: ["سبورة ذكية"] },
  { kind: "text", display: "اكتب: جهاز عرض", accepted: ["جهاز عرض"] },
  { kind: "text", display: "اكتب: حقيبة مدرسية", accepted: ["حقيبة مدرسية"] },
  { kind: "text", display: "اكتب: زي مدرسي", accepted: ["زي مدرسي"] },
  { kind: "text", display: "اكتب: جرس مدرسة", accepted: ["جرس مدرسة"] },
  { kind: "text", display: "اكتب: فصل دراسي", accepted: ["فصل دراسي"] },
  { kind: "text", display: "اكتب: ملعب مدرسة", accepted: ["ملعب مدرسة"] },
  { kind: "text", display: "اكتب: مختبر علوم", accepted: ["مختبر علوم"] },
  { kind: "text", display: "اكتب: مكتبة مدرسية", accepted: ["مكتبة مدرسية"] },
  { kind: "text", display: "اكتب: كافتيريا", accepted: ["كافتيريا"] },
  { kind: "text", display: "اكتب: شهادة تخرج", accepted: ["شهادة تخرج"] },
  { kind: "text", display: "اكتب: قبعة تخرج", accepted: ["قبعة تخرج"] },
  { kind: "text", display: "اكتب: رداء تخرج", accepted: ["رداء تخرج"] },
  { kind: "text", display: "اكتب: اختبار نهائي", accepted: ["اختبار نهائي"] },
  { kind: "text", display: "اكتب: واجب منزلي", accepted: ["واجب منزلي"] },
  { kind: "text", display: "اكتب: جدول دراسي", accepted: ["جدول دراسي"] },
  { kind: "text", display: "اكتب: معلم فصل", accepted: ["معلم فصل"] },
  { kind: "text", display: "اكتب: مدير مدرسة", accepted: ["مدير مدرسة"] },
  { kind: "text", display: "اكتب: مرشد طلابي", accepted: ["مرشد طلابي"] },
  { kind: "text", display: "اكتب: حافلة مدرسية", accepted: ["حافلة مدرسية"] },
  { kind: "text", display: "اكتب: طوب أحمر", accepted: ["طوب أحمر"] },
  { kind: "text", display: "اكتب: إسمنت", accepted: ["إسمنت"] },
  { kind: "text", display: "اكتب: رمل بناء", accepted: ["رمل بناء"] },
  { kind: "text", display: "اكتب: حصى", accepted: ["حصى"] },
  { kind: "text", display: "اكتب: سقالة بناء", accepted: ["سقالة بناء"] },
  { kind: "text", display: "اكتب: خوذة بناء", accepted: ["خوذة بناء"] },
  { kind: "text", display: "اكتب: رافعة برجية", accepted: ["رافعة برجية"] },
  { kind: "text", display: "اكتب: خلاطة إسمنت", accepted: ["خلاطة إسمنت"] },
  { kind: "text", display: "اكتب: مثقاب كهربائي", accepted: ["مثقاب كهربائي"] },
  { kind: "text", display: "اكتب: منشار دائري", accepted: ["منشار دائري"] },
  { kind: "text", display: "اكتب: سلم معدني", accepted: ["سلم معدني"] },
  { kind: "text", display: "اكتب: حبل أمان", accepted: ["حبل أمان"] },
  { kind: "text", display: "اكتب: نظارة واقية", accepted: ["نظارة واقية"] },
  { kind: "text", display: "اكتب: قفاز عمل", accepted: ["قفاز عمل"] },
  { kind: "text", display: "اكتب: حذاء أمان", accepted: ["حذاء أمان"] },
  { kind: "text", display: "اكتب: سترة عاكسة", accepted: ["سترة عاكسة"] },
  { kind: "text", display: "اكتب: لافتة تحذير", accepted: ["لافتة تحذير"] },
  { kind: "text", display: "اكتب: حاجز أمان", accepted: ["حاجز أمان"] },
  { kind: "text", display: "اكتب: مولد كهرباء", accepted: ["مولد كهرباء"] },
  { kind: "text", display: "اكتب: كشاف إنارة", accepted: ["كشاف إنارة"] },
  { kind: "text", display: "اكتب: سوار يد", accepted: ["سوار يد"] },
  { kind: "text", display: "اكتب: قلادة ذهب", accepted: ["قلادة ذهب"] },
  { kind: "text", display: "اكتب: خاتم زواج", accepted: ["خاتم زواج"] },
  { kind: "text", display: "اكتب: أقراط ذهب", accepted: ["أقراط ذهب"] },
  { kind: "text", display: "اكتب: دبوس شعر", accepted: ["دبوس شعر"] },
  { kind: "text", display: "اكتب: ربطة شعر", accepted: ["ربطة شعر"] },
  { kind: "text", display: "اكتب: شنطة يد", accepted: ["شنطة يد"] },
  { kind: "text", display: "اكتب: حقيبة سفر", accepted: ["حقيبة سفر"] },
  { kind: "text", display: "اكتب: نظارة طيران", accepted: ["نظارة طيران"] },
  { kind: "text", display: "اكتب: قبعة شمس", accepted: ["قبعة شمس"] },
  { kind: "text", display: "اكتب: شال حرير", accepted: ["شال حرير"] },
  { kind: "text", display: "اكتب: وشاح صوف", accepted: ["وشاح صوف"] },
  { kind: "text", display: "اكتب: قفاز جلد", accepted: ["قفاز جلد"] },
  { kind: "text", display: "اكتب: جوارب صوف", accepted: ["جوارب صوف"] },
  { kind: "text", display: "اكتب: حذاء كعب", accepted: ["حذاء كعب"] },
  { kind: "text", display: "اكتب: حذاء رياضي فاخر", accepted: ["حذاء رياضي فاخر"] },
  { kind: "text", display: "اكتب: بدلة سباحة", accepted: ["بدلة سباحة"] },
  { kind: "text", display: "اكتب: رداء استحمام", accepted: ["رداء استحمام"] },
  { kind: "text", display: "اكتب: منامة أطفال", accepted: ["منامة أطفال"] },
  { kind: "text", display: "اكتب: زي تنكري", accepted: ["زي تنكري"] },
  { kind: "text", display: "اكتب: أرخبيل", accepted: ["أرخبيل"] },
  { kind: "text", display: "اكتب: بحيرة مالحة", accepted: ["بحيرة مالحة"] },
  { kind: "text", display: "اكتب: نهر جليدي", accepted: ["نهر جليدي"] },
  { kind: "text", display: "اكتب: كثبان بيضاء", accepted: ["كثبان بيضاء"] },
  { kind: "text", display: "اكتب: سهل فيضي", accepted: ["سهل فيضي"] },
  { kind: "text", display: "اكتب: حوض نهري", accepted: ["حوض نهري"] },
  { kind: "text", display: "اكتب: منبع نهر", accepted: ["منبع نهر"] },
  { kind: "text", display: "اكتب: مصب نهر", accepted: ["مصب نهر"] },
  { kind: "text", display: "اكتب: خط استواء", accepted: ["خط استواء"] },
  { kind: "text", display: "اكتب: مدار سرطان", accepted: ["مدار سرطان"] },
  { kind: "text", display: "اكتب: مدار جدي", accepted: ["مدار جدي"] },
  { kind: "text", display: "اكتب: قطب شمالي", accepted: ["قطب شمالي"] },
  { kind: "text", display: "اكتب: قطب جنوبي", accepted: ["قطب جنوبي"] },
  { kind: "text", display: "اكتب: نصف كرة شمالي", accepted: ["نصف كرة شمالي"] },
  { kind: "text", display: "اكتب: نصف كرة جنوبي", accepted: ["نصف كرة جنوبي"] },
  { kind: "text", display: "اكتب: صفيحة تكتونية", accepted: ["صفيحة تكتونية"] },
  { kind: "text", display: "اكتب: قشرة أرضية", accepted: ["قشرة أرضية"] },
  { kind: "text", display: "اكتب: وشاح أرضي", accepted: ["وشاح أرضي"] },
  { kind: "text", display: "اكتب: لب الأرض", accepted: ["لب الأرض"] },
  { kind: "text", display: "اكتب: غلاف جوي علوي", accepted: ["غلاف جوي علوي"] },
  { kind: "text", display: "اكتب: نحات تماثيل", accepted: ["نحات تماثيل"] },
  { kind: "text", display: "اكتب: خطاط عربي", accepted: ["خطاط عربي"] },
  { kind: "text", display: "اكتب: مصمم جرافيك", accepted: ["مصمم جرافيك"] },
  { kind: "text", display: "اكتب: منتج أفلام", accepted: ["منتج أفلام"] },
  { kind: "text", display: "اكتب: كاتب سيناريو", accepted: ["كاتب سيناريو"] },
  { kind: "text", display: "اكتب: ممثل مسرحي", accepted: ["ممثل مسرحي"] },
  { kind: "text", display: "اكتب: راقص باليه", accepted: ["راقص باليه"] },
  { kind: "text", display: "اكتب: مغني أوبرا", accepted: ["مغني أوبرا"] },
  { kind: "text", display: "اكتب: عازف بيانو", accepted: ["عازف بيانو"] },
  { kind: "text", display: "اكتب: قائد أوركسترا", accepted: ["قائد أوركسترا"] },
  { kind: "text", display: "اكتب: إزميل نحت", accepted: ["إزميل نحت"] },
  { kind: "text", display: "اكتب: قلم رصاص فني", accepted: ["قلم رصاص فني"] },
  { kind: "text", display: "اكتب: ألوان أكريليك", accepted: ["ألوان أكريليك"] },
  { kind: "text", display: "اكتب: لوح كانفس", accepted: ["لوح كانفس"] },
  { kind: "text", display: "اكتب: حامل لوحة", accepted: ["حامل لوحة"] },
  { kind: "text", display: "اكتب: سكين تلوين", accepted: ["سكين تلوين"] },
  { kind: "text", display: "اكتب: فرشاة سميكة", accepted: ["فرشاة سميكة"] },
  { kind: "text", display: "اكتب: فرشاة رفيعة", accepted: ["فرشاة رفيعة"] },
  { kind: "text", display: "اكتب: باليتة ألوان", accepted: ["باليتة ألوان"] },
  { kind: "text", display: "اكتب: ورق رسم", accepted: ["ورق رسم"] },
  { kind: "text", display: "اكتب: سفينة شراعية", accepted: ["سفينة شراعية"] },
  { kind: "text", display: "اكتب: غواصة حربية", accepted: ["غواصة حربية"] },
  { kind: "text", display: "اكتب: حاملة طائرات", accepted: ["حاملة طائرات"] },
  { kind: "text", display: "اكتب: مرفأ بحري", accepted: ["مرفأ بحري"] },
  { kind: "text", display: "اكتب: فنار بحري", accepted: ["فنار بحري"] },
  { kind: "text", display: "اكتب: خفر سواحل", accepted: ["خفر سواحل"] },
  { kind: "text", display: "اكتب: صياد لؤلؤ", accepted: ["صياد لؤلؤ"] },
  { kind: "text", display: "اكتب: رصيف ميناء", accepted: ["رصيف ميناء"] },
  { kind: "text", display: "اكتب: قارب صيد", accepted: ["قارب صيد"] },
  { kind: "text", display: "اكتب: يخت فاخر", accepted: ["يخت فاخر"] },
  { kind: "text", display: "اكتب: دمية دب", accepted: ["دمية دب"] },
  { kind: "text", display: "اكتب: سيارة لعبة", accepted: ["سيارة لعبة"] },
  { kind: "text", display: "اكتب: قطار لعبة", accepted: ["قطار لعبة"] },
  { kind: "text", display: "اكتب: مكعبات بناء", accepted: ["مكعبات بناء"] },
  { kind: "text", display: "اكتب: عجلة قيادة لعبة", accepted: ["عجلة قيادة لعبة"] },
  { kind: "text", display: "اكتب: لعبة تركيب", accepted: ["لعبة تركيب"] },
  { kind: "text", display: "اكتب: دراجة أطفال", accepted: ["دراجة أطفال"] },
  { kind: "text", display: "اكتب: أرجوحة حديقة", accepted: ["أرجوحة حديقة"] },
  { kind: "text", display: "اكتب: زحليقة أطفال", accepted: ["زحليقة أطفال"] },
  { kind: "text", display: "اكتب: حوض رمل", accepted: ["حوض رمل"] },
  { kind: "text", display: "اكتب: طنجرة ضغط", accepted: ["طنجرة ضغط"] },
  { kind: "text", display: "اكتب: صينية فرن", accepted: ["صينية فرن"] },
  { kind: "text", display: "اكتب: ملعقة خشب", accepted: ["ملعقة خشب"] },
  { kind: "text", display: "اكتب: مصفاة معكرونة", accepted: ["مصفاة معكرونة"] },
  { kind: "text", display: "اكتب: ميزان حلويات", accepted: ["ميزان حلويات"] },
  { kind: "text", display: "اكتب: قالب كيك", accepted: ["قالب كيك"] },
  { kind: "text", display: "اكتب: فرن غاز", accepted: ["فرن غاز"] },
  { kind: "text", display: "اكتب: شواية فحم", accepted: ["شواية فحم"] },
  { kind: "text", display: "اكتب: سيخ شواء", accepted: ["سيخ شواء"] },
  { kind: "text", display: "اكتب: فحم شواء", accepted: ["فحم شواء"] },
  { kind: "text", display: "اكتب: مسطرة معدنية", accepted: ["مسطرة معدنية"] },
  { kind: "text", display: "اكتب: فرجار هندسي", accepted: ["فرجار هندسي"] },
  { kind: "text", display: "اكتب: منقلة زوايا", accepted: ["منقلة زوايا"] },
  { kind: "text", display: "اكتب: ميزان رقمي", accepted: ["ميزان رقمي"] },
  { kind: "text", display: "اكتب: ساعة توقيت", accepted: ["ساعة توقيت"] },
  { kind: "text", display: "اكتب: عداد خطوات", accepted: ["عداد خطوات"] },
  { kind: "text", display: "اكتب: مقياس حرارة رقمي", accepted: ["مقياس حرارة رقمي"] },
  { kind: "text", display: "اكتب: بوصلة ملاحية", accepted: ["بوصلة ملاحية"] },
  { kind: "text", display: "اكتب: تلسكوب فلكي", accepted: ["تلسكوب فلكي"] },
  { kind: "text", display: "اكتب: مجهر مخبري", accepted: ["مجهر مخبري"] },
  { kind: "text", display: "اكتب: محطة إطلاق", accepted: ["محطة إطلاق"] },
  { kind: "text", display: "اكتب: برج تحكم", accepted: ["برج تحكم"] },
  { kind: "text", display: "اكتب: سلم صعود صاروخ", accepted: ["سلم صعود صاروخ"] },
  { kind: "text", display: "اكتب: خوذة رائد فضاء", accepted: ["خوذة رائد فضاء"] },
  { kind: "text", display: "اكتب: حزام أدوات فضائي", accepted: ["حزام أدوات فضائي"] },
  { kind: "text", display: "اكتب: عربة قمرية", accepted: ["عربة قمرية"] },
  { kind: "text", display: "اكتب: مسبار مريخي", accepted: ["مسبار مريخي"] },
  { kind: "text", display: "اكتب: تلسكوب هابل", accepted: ["تلسكوب هابل"] },
  { kind: "text", display: "اكتب: محطة رصد فلكي", accepted: ["محطة رصد فلكي"] },
  { kind: "text", display: "اكتب: قمر صناعي للاتصالات", accepted: ["قمر صناعي للاتصالات"] },
  { kind: "text", display: "اكتب: محطة أرصاد", accepted: ["محطة أرصاد"] },
  { kind: "text", display: "اكتب: بالون طقس", accepted: ["بالون طقس"] },
  { kind: "text", display: "اكتب: رادار أمطار", accepted: ["رادار أمطار"] },
  { kind: "text", display: "اكتب: قمر صناعي أرصاد", accepted: ["قمر صناعي أرصاد"] },
  { kind: "text", display: "اكتب: مقياس رياح", accepted: ["مقياس رياح"] },
  { kind: "text", display: "اكتب: مقياس أمطار", accepted: ["مقياس أمطار"] },
  { kind: "text", display: "اكتب: خريطة طقس", accepted: ["خريطة طقس"] },
  { kind: "text", display: "اكتب: نشرة جوية", accepted: ["نشرة جوية"] },
  { kind: "text", display: "اكتب: تنبؤ جوي", accepted: ["تنبؤ جوي"] },
  { kind: "text", display: "اكتب: موجة مد", accepted: ["موجة مد"] },
  { kind: "text", display: "اكتب: نوتة موسيقية", accepted: ["نوتة موسيقية"] },
  { kind: "text", display: "اكتب: مفتاح صول", accepted: ["مفتاح صول"] },
  { kind: "text", display: "اكتب: إيقاع موسيقي", accepted: ["إيقاع موسيقي"] },
  { kind: "text", display: "اكتب: لحن موسيقي", accepted: ["لحن موسيقي"] },
  { kind: "text", display: "اكتب: استوديو تسجيل", accepted: ["استوديو تسجيل"] },
  { kind: "text", display: "اكتب: ميكروفون احترافي", accepted: ["ميكروفون احترافي"] },
  { kind: "text", display: "اكتب: سماعة استوديو", accepted: ["سماعة استوديو"] },
  { kind: "text", display: "اكتب: مكبر صوت", accepted: ["مكبر صوت"] },
  { kind: "text", display: "اكتب: جهاز خلط صوت", accepted: ["جهاز خلط صوت"] },
  { kind: "text", display: "اكتب: حفلة موسيقية", accepted: ["حفلة موسيقية"] },
  { kind: "text", display: "اكتب: سرير أطفال", accepted: ["سرير أطفال"] },
  { kind: "text", display: "اكتب: كرسي مكتب", accepted: ["كرسي مكتب"] },
  { kind: "text", display: "اكتب: طاولة طعام", accepted: ["طاولة طعام"] },
  { kind: "text", display: "اكتب: خزانة مطبخ", accepted: ["خزانة مطبخ"] },
  { kind: "text", display: "اكتب: رف كتب", accepted: ["رف كتب"] },
  { kind: "text", display: "اكتب: منضدة زينة", accepted: ["منضدة زينة"] },
  { kind: "text", display: "اكتب: كرسي هزاز", accepted: ["كرسي هزاز"] },
  { kind: "text", display: "اكتب: أريكة جلد", accepted: ["أريكة جلد"] },
  { kind: "text", display: "اكتب: طاولة تلفاز", accepted: ["طاولة تلفاز"] },
  { kind: "text", display: "اكتب: خزانة أحذية", accepted: ["خزانة أحذية"] },
  { kind: "text", display: "اكتب: كرسي حديقة", accepted: ["كرسي حديقة"] },
  { kind: "text", display: "اكتب: طاولة حديقة", accepted: ["طاولة حديقة"] },
  { kind: "text", display: "اكتب: مظلة حديقة", accepted: ["مظلة حديقة"] },
  { kind: "text", display: "اكتب: نافورة حديقة", accepted: ["نافورة حديقة"] },
  { kind: "text", display: "اكتب: تمثال حديقة", accepted: ["تمثال حديقة"] },
  { kind: "text", display: "اكتب: سياج خشبي", accepted: ["سياج خشبي"] },
  { kind: "text", display: "اكتب: بوابة حديد", accepted: ["بوابة حديد"] },
  { kind: "text", display: "اكتب: درج خارجي", accepted: ["درج خارجي"] },
  { kind: "text", display: "اكتب: شرفة منزل", accepted: ["شرفة منزل"] },
  { kind: "text", display: "اكتب: سطح منزل", accepted: ["سطح منزل"] },
  { kind: "text", display: "اكتب: مدخنة منزل", accepted: ["مدخنة منزل"] },
  { kind: "text", display: "اكتب: نافذة زجاجية", accepted: ["نافذة زجاجية"] },
  { kind: "text", display: "اكتب: باب خشبي", accepted: ["باب خشبي"] },
  { kind: "text", display: "اكتب: قفل باب", accepted: ["قفل باب"] },
  { kind: "text", display: "اكتب: مقبض باب", accepted: ["مقبض باب"] },
  { kind: "text", display: "اكتب: جرس باب", accepted: ["جرس باب"] },
  { kind: "text", display: "اكتب: عين مراقبة", accepted: ["عين مراقبة"] },
  { kind: "text", display: "اكتب: سلم داخلي", accepted: ["سلم داخلي"] },
  { kind: "text", display: "اكتب: مصعد كهربائي", accepted: ["مصعد كهربائي"] },
  { kind: "text", display: "اكتب: درابزين", accepted: ["درابزين"] },
  { kind: "text", display: "اكتب: حوض استحمام", accepted: ["حوض استحمام"] },
  { kind: "text", display: "اكتب: دش استحمام", accepted: ["دش استحمام"] },
  { kind: "text", display: "اكتب: مغسلة حمام", accepted: ["مغسلة حمام"] },
  { kind: "text", display: "اكتب: مرآة حمام", accepted: ["مرآة حمام"] },
  { kind: "text", display: "اكتب: خزانة حمام", accepted: ["خزانة حمام"] },
  { kind: "text", display: "اكتب: سجادة حمام", accepted: ["سجادة حمام"] },
  { kind: "text", display: "اكتب: فرشاة أسنان", accepted: ["فرشاة أسنان"] },
  { kind: "text", display: "اكتب: معجون أسنان", accepted: ["معجون أسنان"] },
  { kind: "text", display: "اكتب: شامبو شعر", accepted: ["شامبو شعر"] },
  { kind: "text", display: "اكتب: صابون سائل", accepted: ["صابون سائل"] },
  { kind: "text", display: "اكتب: مشط شعر", accepted: ["مشط شعر"] },
  { kind: "text", display: "اكتب: مجفف يد", accepted: ["مجفف يد"] },
  { kind: "text", display: "اكتب: حامل مناشف", accepted: ["حامل مناشف"] },
  { kind: "text", display: "اكتب: سلة مهملات", accepted: ["سلة مهملات"] },
  { kind: "text", display: "اكتب: علبة مناديل", accepted: ["علبة مناديل"] },
  { kind: "text", display: "اكتب: مبخرة عود", accepted: ["مبخرة عود"] },
  { kind: "text", display: "اكتب: دخون بخور", accepted: ["دخون بخور"] },
  { kind: "text", display: "اكتب: عطر نسائي", accepted: ["عطر نسائي"] },
  { kind: "text", display: "اكتب: عطر رجالي", accepted: ["عطر رجالي"] },
  { kind: "text", display: "اكتب: كريم ترطيب", accepted: ["كريم ترطيب"] },
  { kind: "text", display: "اكتب: مقلمة رصاص", accepted: ["مقلمة رصاص"] },
  { kind: "text", display: "اكتب: حقيبة لابتوب", accepted: ["حقيبة لابتوب"] },
  { kind: "text", display: "اكتب: سماعة سلكية", accepted: ["سماعة سلكية"] },
  { kind: "text", display: "اكتب: كابل شحن", accepted: ["كابل شحن"] },
  { kind: "text", display: "اكتب: بطاقة ذاكرة", accepted: ["بطاقة ذاكرة"] },
  { kind: "text", display: "اكتب: قرص مضغوط", accepted: ["قرص مضغوط"] },
  { kind: "text", display: "اكتب: فلاش ميموري", accepted: ["فلاش ميموري"] },
  { kind: "text", display: "اكتب: شاشة عرض", accepted: ["شاشة عرض"] },
  { kind: "text", display: "اكتب: جهاز تحكم", accepted: ["جهاز تحكم"] },
  { kind: "text", display: "اكتب: عصا تحكم", accepted: ["عصا تحكم"] },
  { kind: "text", display: "اكتب: كرسي دراسة", accepted: ["كرسي دراسة"] },
  { kind: "text", display: "اكتب: مصباح مكتب", accepted: ["مصباح مكتب"] },
  { kind: "text", display: "اكتب: ساعة حائط", accepted: ["ساعة حائط"] },
  { kind: "text", display: "اكتب: تقويم سنوي", accepted: ["تقويم سنوي"] },
  { kind: "text", display: "اكتب: دفتر ملاحظات", accepted: ["دفتر ملاحظات"] },
  { kind: "text", display: "اكتب: لاصق ملاحظات", accepted: ["لاصق ملاحظات"] },
  { kind: "text", display: "اكتب: مبراة أقلام", accepted: ["مبراة أقلام"] },
  { kind: "text", display: "اكتب: حقيبة قلم رصاص", accepted: ["حقيبة قلم رصاص"] },
  { kind: "text", display: "اكتب: طاولة رسم", accepted: ["طاولة رسم"] },
  { kind: "text", display: "اكتب: لوح أبيض", accepted: ["لوح أبيض"] },
  { kind: "text", display: "اكتب: عربة تسوق", accepted: ["عربة تسوق"] },
  { kind: "text", display: "اكتب: سلة تسوق", accepted: ["سلة تسوق"] },
  { kind: "text", display: "اكتب: بطاقة خصم", accepted: ["بطاقة خصم"] },
  { kind: "text", display: "اكتب: محفظة إلكترونية", accepted: ["محفظة إلكترونية"] },
  { kind: "text", display: "اكتب: آلة صراف", accepted: ["آلة صراف"] },
  { kind: "text", display: "اكتب: إيصال شراء", accepted: ["إيصال شراء"] },
  { kind: "text", display: "اكتب: كيس ورقي", accepted: ["كيس ورقي"] },
  { kind: "text", display: "اكتب: كيس بلاستيك", accepted: ["كيس بلاستيك"] },
  { kind: "text", display: "اكتب: صندوق شحن", accepted: ["صندوق شحن"] },
  { kind: "text", display: "اكتب: شريط لاصق", accepted: ["شريط لاصق"] },
  { kind: "text", display: "اكتب: مروحة يدوية", accepted: ["مروحة يدوية"] },
  { kind: "text", display: "اكتب: مظلة مطر", accepted: ["مظلة مطر"] },
  { kind: "text", display: "اكتب: حذاء مطر", accepted: ["حذاء مطر"] },
  { kind: "text", display: "اكتب: معطف واق", accepted: ["معطف واق"] },
  { kind: "text", display: "اكتب: شمسية شاطئ", accepted: ["شمسية شاطئ"] },
  { kind: "text", display: "اكتب: كرسي شاطئ", accepted: ["كرسي شاطئ"] },
  { kind: "text", display: "اكتب: منشفة شاطئ", accepted: ["منشفة شاطئ"] },
  { kind: "text", display: "اكتب: نظارة غوص", accepted: ["نظارة غوص"] },
  { kind: "text", display: "اكتب: زعانف سباحة", accepted: ["زعانف سباحة"] },
  { kind: "text", display: "اكتب: أسطوانة غوص", accepted: ["أسطوانة غوص"] },
  { kind: "text", display: "اكتب: عربة أطفال", accepted: ["عربة أطفال"] },
  { kind: "text", display: "اكتب: كرسي أطفال", accepted: ["كرسي أطفال"] },
  { kind: "text", display: "اكتب: لهاية طفل", accepted: ["لهاية طفل"] },
  { kind: "text", display: "اكتب: حفاضة طفل", accepted: ["حفاضة طفل"] },
  { kind: "text", display: "اكتب: زجاجة رضاعة", accepted: ["زجاجة رضاعة"] },
  { kind: "text", display: "اكتب: سرير طفل", accepted: ["سرير طفل"] },
  { kind: "text", display: "اكتب: لعبة قماشية", accepted: ["لعبة قماشية"] },
  { kind: "text", display: "اكتب: جرس أطفال", accepted: ["جرس أطفال"] },
  { kind: "text", display: "اكتب: كتاب أطفال", accepted: ["كتاب أطفال"] },
  { kind: "text", display: "اكتب: قصة مصورة", accepted: ["قصة مصورة"] },
  { kind: "text", display: "اكتب: إبريق فخار", accepted: ["إبريق فخار"] },
  { kind: "text", display: "اكتب: صحن خزف", accepted: ["صحن خزف"] },
  { kind: "text", display: "اكتب: كوب زجاجي", accepted: ["كوب زجاجي"] },
  { kind: "text", display: "اكتب: كأس بلوري", accepted: ["كأس بلوري"] },
  { kind: "text", display: "اكتب: سكين مطبخ", accepted: ["سكين مطبخ"] },
  { kind: "text", display: "اكتب: ملعقة تقديم", accepted: ["ملعقة تقديم"] },
  { kind: "text", display: "اكتب: شوكة سلطة", accepted: ["شوكة سلطة"] },
  { kind: "text", display: "اكتب: طبق تقديم", accepted: ["طبق تقديم"] },
  { kind: "text", display: "اكتب: سلطانية", accepted: ["سلطانية"] },
  { kind: "text", display: "اكتب: إناء طبخ", accepted: ["إناء طبخ"] },
  { kind: "text", display: "اكتب: محفظة جلدية", accepted: ["محفظة جلدية"] },
  { kind: "text", display: "اكتب: حقيبة ظهر مدرسية", accepted: ["حقيبة ظهر مدرسية"] },
  { kind: "text", display: "اكتب: حزام جلد", accepted: ["حزام جلد"] },
  { kind: "text", display: "اكتب: قبعة صيف", accepted: ["قبعة صيف"] },
  { kind: "text", display: "اكتب: نظارة قراءة", accepted: ["نظارة قراءة"] },
  { kind: "text", display: "اكتب: ساعة رقمية", accepted: ["ساعة رقمية"] },
  { kind: "text", display: "اكتب: سوار رياضي", accepted: ["سوار رياضي"] },
  { kind: "text", display: "اكتب: خاتم فضة", accepted: ["خاتم فضة"] },
  { kind: "text", display: "اكتب: دبوس ربطة عنق", accepted: ["دبوس ربطة عنق"] },
  { kind: "text", display: "اكتب: زر قميص", accepted: ["زر قميص"] },
  { kind: "text", display: "اكتب: شجرة عيد ميلاد", accepted: ["شجرة عيد ميلاد"] },
  { kind: "text", display: "اكتب: زينة احتفال", accepted: ["زينة احتفال"] },
  { kind: "text", display: "اكتب: بالونات ملونة", accepted: ["بالونات ملونة"] },
  { kind: "text", display: "اكتب: شموع كيك", accepted: ["شموع كيك"] },
  { kind: "text", display: "اكتب: هدية ملفوفة", accepted: ["هدية ملفوفة"] },
  { kind: "text", display: "اكتب: بطاقة تهنئة", accepted: ["بطاقة تهنئة"] },
  { kind: "text", display: "اكتب: ورق تغليف", accepted: ["ورق تغليف"] },
  { kind: "text", display: "اكتب: شريط زينة", accepted: ["شريط زينة"] },
  { kind: "text", display: "اكتب: قبعة حفلة", accepted: ["قبعة حفلة"] },
  { kind: "text", display: "اكتب: أضواء زينة", accepted: ["أضواء زينة"] },
  { kind: "text", display: "اكتب: قارورة ماء", accepted: ["قارورة ماء"] },
  { kind: "text", display: "اكتب: كوب حراري معدني", accepted: ["كوب حراري معدني"] },
  { kind: "text", display: "اكتب: صندوق غداء", accepted: ["صندوق غداء"] },
  { kind: "text", display: "اكتب: حقيبة غداء", accepted: ["حقيبة غداء"] },
  { kind: "text", display: "اكتب: منديل قماش", accepted: ["منديل قماش"] },
  { kind: "text", display: "اكتب: مفرش طاولة", accepted: ["مفرش طاولة"] },
  { kind: "text", display: "اكتب: شمعدان فضي", accepted: ["شمعدان فضي"] },
  { kind: "text", display: "اكتب: مزهرية زجاج", accepted: ["مزهرية زجاج"] },
  { kind: "text", display: "اكتب: إطار صورة", accepted: ["إطار صورة"] },
  { kind: "text", display: "اكتب: ساعة رملية", accepted: ["ساعة رملية"] },
  { kind: "text", display: "اكتب: عود بخور", accepted: ["عود بخور"] },
  { kind: "text", display: "اكتب: مبخرة نحاسية", accepted: ["مبخرة نحاسية"] },
  { kind: "text", display: "اكتب: سجادة يدوية", accepted: ["سجادة يدوية"] },
  { kind: "text", display: "اكتب: وسادة مطرزة", accepted: ["وسادة مطرزة"] },
  { kind: "text", display: "اكتب: ستارة تطريز", accepted: ["ستارة تطريز"] },
  { kind: "text", display: "اكتب: خيط تطريز", accepted: ["خيط تطريز"] },
  { kind: "text", display: "اكتب: إبرة خياطة", accepted: ["إبرة خياطة"] },
  { kind: "text", display: "اكتب: مقص خياطة", accepted: ["مقص خياطة"] },
  { kind: "text", display: "اكتب: ماكينة خياطة", accepted: ["ماكينة خياطة"] },
  { kind: "text", display: "اكتب: كشتبان", accepted: ["كشتبان"] }
];
