import type { TriviaQuestion } from "../engine";

export const flagsGuessBank: TriviaQuestion[] = [
  { kind: "flag", display: "🇸🇦", accepted: ["السعودية", "سعودية"] },
  { kind: "flag", display: "🇪🇬", accepted: ["مصر"] },
  { kind: "flag", display: "🇦🇪", accepted: ["الامارات", "الإمارات", "امارات"] },
  { kind: "flag", display: "🇯🇴", accepted: ["الأردن", "الاردن", "اردن"] },
  { kind: "flag", display: "🇰🇼", accepted: ["الكويت", "كويت"] },
  { kind: "flag", display: "🇶🇦", accepted: ["قطر"] },
  { kind: "flag", display: "🇧🇭", accepted: ["البحرين", "بحرين"] },
  { kind: "flag", display: "🇴🇲", accepted: ["عمان", "عُمان"] },
  { kind: "flag", display: "🇮🇶", accepted: ["العراق", "عراق"] },
  { kind: "flag", display: "🇸🇾", accepted: ["سوريا", "سورية"] },
  { kind: "flag", display: "🇱🇧", accepted: ["لبنان"] },
  { kind: "flag", display: "🇵🇸", accepted: ["فلسطين"] },
  { kind: "flag", display: "🇾🇪", accepted: ["اليمن", "يمن"] },
  { kind: "flag", display: "🇲🇦", accepted: ["المغرب", "مغرب"] },
  { kind: "flag", display: "🇩🇿", accepted: ["الجزائر", "جزائر"] },
  { kind: "flag", display: "🇹🇳", accepted: ["تونس"] },
  { kind: "flag", display: "🇱🇾", accepted: ["ليبيا"] },
  { kind: "flag", display: "🇸🇩", accepted: ["السودان", "سودان"] },
  { kind: "flag", display: "🇲🇷", accepted: ["موريتانيا"] },
  { kind: "flag", display: "🇸🇴", accepted: ["الصومال"] },
  { kind: "flag", display: "🇩🇯", accepted: ["جيبوتي"] },
  { kind: "flag", display: "🇰🇲", accepted: ["جزر القمر"] },
  { kind: "flag", display: "🇺🇸", accepted: ["امريكا", "أمريكا", "الولايات المتحدة"] },
  { kind: "flag", display: "🇨🇦", accepted: ["كندا"] },
  { kind: "flag", display: "🇲🇽", accepted: ["المكسيك"] },
  { kind: "flag", display: "🇧🇷", accepted: ["البرازيل", "برازيل"] },
  { kind: "flag", display: "🇦🇷", accepted: ["الأرجنتين"] },
  { kind: "flag", display: "🇨🇱", accepted: ["تشيلي"] },
  { kind: "flag", display: "🇨🇴", accepted: ["كولومبيا"] },
  { kind: "flag", display: "🇵🇪", accepted: ["بيرو"] },
  { kind: "flag", display: "🇻🇪", accepted: ["فنزويلا"] },
  { kind: "flag", display: "🇪🇨", accepted: ["الاكوادور"] },
  { kind: "flag", display: "🇧🇴", accepted: ["بوليفيا"] },
  { kind: "flag", display: "🇺🇾", accepted: ["الأوروغواي"] },
  { kind: "flag", display: "🇵🇾", accepted: ["باراغواي"] },
  { kind: "flag", display: "🇨🇺", accepted: ["كوبا"] },
  { kind: "flag", display: "🇬🇧", accepted: ["بريطانيا", "انجلترا", "إنجلترا"] },
  { kind: "flag", display: "🇫🇷", accepted: ["فرنسا"] },
  { kind: "flag", display: "🇩🇪", accepted: ["المانيا", "ألمانيا"] },
  { kind: "flag", display: "🇮🇹", accepted: ["ايطاليا", "إيطاليا"] },
  { kind: "flag", display: "🇪🇸", accepted: ["اسبانيا", "إسبانيا"] },
  { kind: "flag", display: "🇵🇹", accepted: ["البرتغال"] },
  { kind: "flag", display: "🇳🇱", accepted: ["هولندا"] },
  { kind: "flag", display: "🇧🇪", accepted: ["بلجيكا"] },
  { kind: "flag", display: "🇨🇭", accepted: ["سويسرا"] },
  { kind: "flag", display: "🇦🇹", accepted: ["النمسا"] },
  { kind: "flag", display: "🇸🇪", accepted: ["السويد"] },
  { kind: "flag", display: "🇳🇴", accepted: ["النرويج"] },
  { kind: "flag", display: "🇩🇰", accepted: ["الدنمارك"] },
  { kind: "flag", display: "🇫🇮", accepted: ["فنلندا"] },
  { kind: "flag", display: "🇮🇸", accepted: ["ايسلندا"] },
  { kind: "flag", display: "🇮🇪", accepted: ["ايرلندا"] },
  { kind: "flag", display: "🇬🇷", accepted: ["اليونان"] },
  { kind: "flag", display: "🇵🇱", accepted: ["بولندا"] },
  { kind: "flag", display: "🇨🇿", accepted: ["التشيك"] },
  { kind: "flag", display: "🇸🇰", accepted: ["سلوفاكيا"] },
  { kind: "flag", display: "🇭🇺", accepted: ["المجر"] },
  { kind: "flag", display: "🇷🇴", accepted: ["رومانيا"] },
  { kind: "flag", display: "🇧🇬", accepted: ["بلغاريا"] },
  { kind: "flag", display: "🇺🇦", accepted: ["اوكرانيا"] },
  { kind: "flag", display: "🇧🇾", accepted: ["بيلاروسيا"] },
  { kind: "flag", display: "🇷🇺", accepted: ["روسيا"] },
  { kind: "flag", display: "🇹🇷", accepted: ["تركيا"] },
  { kind: "flag", display: "🇭🇷", accepted: ["كرواتيا"] },
  { kind: "flag", display: "🇷🇸", accepted: ["صربيا"] },
  { kind: "flag", display: "🇸🇮", accepted: ["سلوفينيا"] },
  { kind: "flag", display: "🇦🇱", accepted: ["البانيا"] },
  { kind: "flag", display: "🇲🇰", accepted: ["مقدونيا الشمالية"] },
  { kind: "flag", display: "🇽🇰", accepted: ["كوسوفو"] },
  { kind: "flag", display: "🇧🇦", accepted: ["البوسنة والهرسك"] },
  { kind: "flag", display: "🇲🇹", accepted: ["مالطا"] },
  { kind: "flag", display: "🇱🇺", accepted: ["لوكسمبورغ"] },
  { kind: "flag", display: "🇱🇹", accepted: ["ليتوانيا"] },
  { kind: "flag", display: "🇱🇻", accepted: ["لاتفيا"] },
  { kind: "flag", display: "🇪🇪", accepted: ["استونيا"] },
  { kind: "flag", display: "🇲🇩", accepted: ["مولدوفا"] },
  { kind: "flag", display: "🇬🇪", accepted: ["جورجيا"] },
  { kind: "flag", display: "🇦🇲", accepted: ["أرمينيا"] },
  { kind: "flag", display: "🇦🇿", accepted: ["أذربيجان"] },
  { kind: "flag", display: "🇯🇵", accepted: ["اليابان", "يابان"] },
  { kind: "flag", display: "🇨🇳", accepted: ["الصين", "صين"] },
  { kind: "flag", display: "🇰🇷", accepted: ["كوريا الجنوبية", "كوريا"] },
  { kind: "flag", display: "🇰🇵", accepted: ["كوريا الشمالية"] },
  { kind: "flag", display: "🇮🇳", accepted: ["الهند"] },
  { kind: "flag", display: "🇵🇰", accepted: ["باكستان"] },
  { kind: "flag", display: "🇧🇩", accepted: ["بنغلاديش"] },
  { kind: "flag", display: "🇱🇰", accepted: ["سريلانكا"] },
  { kind: "flag", display: "🇳🇵", accepted: ["نيبال"] },
  { kind: "flag", display: "🇦🇫", accepted: ["أفغانستان"] },
  { kind: "flag", display: "🇮🇷", accepted: ["ايران"] },
  { kind: "flag", display: "🇮🇩", accepted: ["اندونيسيا"] },
  { kind: "flag", display: "🇲🇾", accepted: ["ماليزيا"] },
  { kind: "flag", display: "🇸🇬", accepted: ["سنغافورة"] },
  { kind: "flag", display: "🇹🇭", accepted: ["تايلاند"] },
  { kind: "flag", display: "🇻🇳", accepted: ["فيتنام"] },
  { kind: "flag", display: "🇵🇭", accepted: ["الفلبين"] },
  { kind: "flag", display: "🇲🇲", accepted: ["ميانمار"] },
  { kind: "flag", display: "🇰🇭", accepted: ["كمبوديا"] },
  { kind: "flag", display: "🇱🇦", accepted: ["لاوس"] },
  { kind: "flag", display: "🇲🇳", accepted: ["منغوليا"] },
  { kind: "flag", display: "🇰🇿", accepted: ["كازاخستان"] },
  { kind: "flag", display: "🇺🇿", accepted: ["أوزبكستان"] },
  { kind: "flag", display: "🇹🇲", accepted: ["تركمانستان"] },
  { kind: "flag", display: "🇰🇬", accepted: ["قيرغيزستان"] },
  { kind: "flag", display: "🇹🇯", accepted: ["طاجيكستان"] },
  { kind: "flag", display: "🇦🇺", accepted: ["استراليا"] },
  { kind: "flag", display: "🇳🇿", accepted: ["نيوزيلندا"] },
  { kind: "flag", display: "🇫🇯", accepted: ["فيجي"] },
  { kind: "flag", display: "🇵🇬", accepted: ["بابوا غينيا الجديدة"] },
  { kind: "flag", display: "🇿🇦", accepted: ["جنوب افريقيا"] },
  { kind: "flag", display: "🇳🇬", accepted: ["نيجيريا"] },
  { kind: "flag", display: "🇰🇪", accepted: ["كينيا"] },
  { kind: "flag", display: "🇪🇹", accepted: ["اثيوبيا"] },
  { kind: "flag", display: "🇬🇭", accepted: ["غانا"] },
  { kind: "flag", display: "🇹🇿", accepted: ["تنزانيا"] },
  { kind: "flag", display: "🇺🇬", accepted: ["أوغندا"] },
  { kind: "flag", display: "🇸🇳", accepted: ["السنغال"] },
  { kind: "flag", display: "🇨🇮", accepted: ["ساحل العاج"] },
  { kind: "flag", display: "🇨🇲", accepted: ["الكاميرون"] },
  { kind: "flag", display: "🇿🇼", accepted: ["زيمبابوي"] },
  { kind: "flag", display: "🇿🇲", accepted: ["زامبيا"] },
  { kind: "flag", display: "🇦🇴", accepted: ["أنغولا"] },
  { kind: "flag", display: "🇲🇿", accepted: ["موزمبيق"] },
  { kind: "flag", display: "🇳🇦", accepted: ["ناميبيا"] },
  { kind: "flag", display: "🇧🇼", accepted: ["بوتسوانا"] },
  { kind: "flag", display: "🇷🇼", accepted: ["رواندا"] },
  { kind: "flag", display: "🇲🇱", accepted: ["مالي"] },
  { kind: "flag", display: "🇳🇪", accepted: ["النيجر"] },
  { kind: "flag", display: "🇹🇩", accepted: ["تشاد"] },
  { kind: "flag", display: "🇧🇫", accepted: ["بوركينا فاسو"] },
  { kind: "flag", display: "🇬🇦", accepted: ["الغابون"] },
  { kind: "flag", display: "🇧🇯", accepted: ["بنين"] },
  { kind: "flag", display: "🇹🇬", accepted: ["توغو"] },
  { kind: "flag", display: "🇱🇷", accepted: ["ليبيريا"] },
  { kind: "flag", display: "🇸🇱", accepted: ["سيراليون"] },
  { kind: "flag", display: "🇲🇬", accepted: ["مدغشقر"] },
  { kind: "flag", display: "🇲🇺", accepted: ["موريشيوس"] }
];
