import type { TriviaQuestion } from "../engine";

export const letterCellBank: TriviaQuestion[] = [
  { kind: "letter-hive", display: "اكتب كلمة فيها حرف \"ب\"", meta: { center: "ب", outerLetters: ["ح", "ر", "ي", "ت", "ن", "د"] }, accepted: ["بحر", "بيت", "بنت"] },
  { kind: "letter-hive", display: "اكتب كلمة فيها حرف \"س\"", meta: { center: "س", outerLetters: ["م", "ا", "ك", "ن", "ر", "و"] }, accepted: ["سكن", "سمك", "سنا"] },
  { kind: "letter-hive", display: "اكتب كلمة فيها حرف \"ك\"", meta: { center: "ك", outerLetters: ["ت", "ب", "ر", "م", "س", "ل"] }, accepted: ["كتب", "كبر", "كسر"] },
  { kind: "letter-hive", display: "اكتب كلمة فيها حرف \"ن\"", meta: { center: "ن", outerLetters: ["ج", "م", "د", "ي", "ب", "ة"] }, accepted: ["نجم", "ندم", "نبي"] },
  { kind: "letter-hive", display: "اكتب كلمة فيها حرف \"ق\"", meta: { center: "ق", outerLetters: ["ل", "م", "ر", "ب", "ط", "ة"] }, accepted: ["قلم", "قمر", "قطب"] },
  { kind: "letter-hive", display: "اكتب كلمة فيها حرف \"ح\"", meta: { center: "ح", outerLetters: ["ل", "ي", "ب", "م", "ق", "ة"] }, accepted: ["حليب", "حلم", "حبل"] },
  { kind: "letter-hive", display: "اكتب كلمة فيها حرف \"ط\"", meta: { center: "ط", outerLetters: ["ي", "ر", "ب", "ل", "ق", "ة"] }, accepted: ["طير", "طبل", "طريق"] },
  { kind: "letter-hive", display: "اكتب كلمة فيها حرف \"ذ\"", meta: { center: "ذ", outerLetters: ["ه", "ب", "ك", "ر", "ا", "ة"] }, accepted: ["ذهب", "ذكر"] },
  { kind: "letter-hive", display: "اكتب كلمة فيها حرف \"ص\"", meta: { center: "ص", outerLetters: ["د", "ق", "ب", "ر", "ح", "ة"] }, accepted: ["صدق", "صبر", "صحب"] },
  { kind: "letter-hive", display: "اكتب كلمة فيها حرف \"ف\"", meta: { center: "ف", outerLetters: ["ر", "ح", "م", "ت", "ن", "ة"] }, accepted: ["فرح", "فتح", "فرن"] },
  { kind: "letter-hive", display: "اكتب كلمة فيها حرف \"م\"", meta: { center: "م", outerLetters: ["د", "ر", "س", "ن", "ل", "ة"] }, accepted: ["مدرس", "مدن", "مرسل"] },
  { kind: "letter-hive", display: "اكتب كلمة فيها حرف \"ع\"", meta: { center: "ع", outerLetters: ["ل", "م", "ن", "ب", "د", "ة"] }, accepted: ["علم", "عمل", "عند", "عبد"] },
  { kind: "letter-hive", display: "اكتب كلمة فيها حرف \"ك\"", meta: { center: "ك", outerLetters: ["ت", "ب", "ذ", "و", "ل", "ة"] }, accepted: ["كتب", "كذب"] },
  { kind: "letter-hive", display: "اكتب كلمة فيها حرف \"ل\"", meta: { center: "ل", outerLetters: ["ع", "ب", "م", "س", "ن", "ة"] }, accepted: ["لعب", "لبن"] },
  { kind: "letter-hive", display: "اكتب كلمة فيها حرف \"ن\"", meta: { center: "ن", outerLetters: ["ج", "م", "د", "و", "ر", "ة"] }, accepted: ["نجم", "نور", "نمر"] },
  { kind: "letter-hive", display: "اكتب كلمة فيها حرف \"م\"", meta: { center: "م", outerLetters: ["ل", "ك", "ب", "ي", "ر", "ة"] }, accepted: ["ملك", "مكر"] },
  { kind: "letter-hive", display: "اكتب كلمة فيها حرف \"س\"", meta: { center: "س", outerLetters: ["ل", "ك", "ي", "ن", "ب", "ة"] }, accepted: ["سكن", "سلك", "سيل"] },
  { kind: "letter-hive", display: "اكتب كلمة فيها حرف \"ط\"", meta: { center: "ط", outerLetters: ["ب", "خ", "ي", "ز", "م", "ة"] }, accepted: ["طبخ"] },
  { kind: "letter-hive", display: "اكتب كلمة فيها حرف \"ف\"", meta: { center: "ف", outerLetters: ["ه", "م", "ك", "ر", "ي", "ة"] }, accepted: ["فهم", "فكر"] },
  { kind: "letter-hive", display: "اكتب كلمة فيها حرف \"ع\"", meta: { center: "ع", outerLetters: ["ي", "ن", "ب", "ك", "ر", "ة"] }, accepted: ["عين", "عنب"] },
  { kind: "letter-hive", display: "اكتب كلمة فيها حرف \"ح\"", meta: { center: "ح", outerLetters: ["ر", "ب", "ك", "م", "ة", "ن"] }, accepted: ["حرب", "حكم"] },
  { kind: "letter-hive", display: "اكتب كلمة فيها حرف \"ص\"", meta: { center: "ص", outerLetters: ["ي", "د", "ح", "ة", "ن", "ر"] }, accepted: ["صيد", "صحن"] },
  { kind: "letter-hive", display: "اكتب كلمة فيها حرف \"ق\"", meta: { center: "ق", outerLetters: ["ص", "ة", "ر", "ي", "د", "ن"] }, accepted: ["قصر", "قرد"] },
  { kind: "letter-hive", display: "اكتب كلمة فيها حرف \"ذ\"", meta: { center: "ذ", outerLetters: ["ر", "ة", "ي", "ل", "ب", "ن"] }, accepted: ["ذيل"] },
  { kind: "letter-hive", display: "اكتب كلمة فيها حرف \"ت\"", meta: { center: "ت", outerLetters: ["ع", "ب", "م", "ر", "ن", "ة"] }, accepted: ["تعب", "تمر"] },
  { kind: "letter-hive", display: "اكتب كلمة فيها حرف \"ب\"", meta: { center: "ب", outerLetters: ["ح", "ر", "د", "ي", "ن", "ة"] }, accepted: ["بحر", "برد", "بند"] },
  { kind: "letter-hive", display: "اكتب كلمة فيها حرف \"ج\"", meta: { center: "ج", outerLetters: ["ب", "ل", "د", "ن", "ي", "ة"] }, accepted: ["جبل", "جيد"] },
  { kind: "letter-hive", display: "اكتب كلمة فيها حرف \"خ\"", meta: { center: "خ", outerLetters: ["ب", "ز", "ط", "ر", "ي", "ة"] }, accepted: ["خبز", "خطر"] },
  { kind: "letter-hive", display: "اكتب كلمة فيها حرف \"د\"", meta: { center: "د", outerLetters: ["ر", "س", "و", "ن", "م", "ة"] }, accepted: ["درس", "دور"] },
  { kind: "letter-hive", display: "اكتب كلمة فيها حرف \"ر\"", meta: { center: "ر", outerLetters: ["ي", "ح", "ل", "ب", "ع", "ة"] }, accepted: ["ريح", "رحلة"] },
  { kind: "letter-hive", display: "اكتب كلمة فيها حرف \"ز\"", meta: { center: "ز", outerLetters: ["ه", "ر", "ة", "ن", "ب", "د"] }, accepted: ["زهرة"] },
  { kind: "letter-hive", display: "اكتب كلمة فيها حرف \"ن\"", meta: { center: "ن", outerLetters: ["ه", "ر", "ب", "ي", "ل", "ة"] }, accepted: ["نهر"] }
];
