import type { TriviaQuestion } from "../engine";

export const quizBank: TriviaQuestion[] = [
  { kind: "text", display: "كم عدد أيام السنة الكبيسة؟", accepted: ["366", "ثلاثمية وستة وستين"] },
  { kind: "text", display: "ما هي عاصمة اليابان؟", accepted: ["طوكيو"] },
  { kind: "text", display: "كم عدد قارات العالم؟", accepted: ["7", "سبع", "سبعة"] },
  { kind: "text", display: "ما هو أطول نهر في العالم؟", accepted: ["النيل"] },
  { kind: "text", display: "من مؤلف رواية \"الف ليلة وليلة\" الشعبية؟ (اكتب: مجهول)", accepted: ["مجهول"] },
  { kind: "text", display: "كم عدد اللاعبين الأساسيين بفريق كرة القدم؟", accepted: ["11", "احدعشر", "أحد عشر"] },
  { kind: "text", display: "ما هي أكبر صحراء حارة بالعالم؟", accepted: ["الصحراء الكبرى", "الصحراء الكبرى الافريقية"] },
  { kind: "text", display: "كم لون في قوس قزح؟", accepted: ["7", "سبع", "سبعة"] },
  { kind: "text", display: "ما اسم أول سورة في القرآن الكريم؟", accepted: ["الفاتحة"] },
  { kind: "text", display: "ما هو غاز يتنفسه الإنسان؟", accepted: ["الأكسجين"] },
  { kind: "text", display: "كم عدد أحرف اللغة العربية؟", accepted: ["28", "ثمانية وعشرين", "ثمانيه وعشرين"] },
  { kind: "text", display: "ما اسم أكبر كوكب بالمجموعة الشمسية؟", accepted: ["المشتري"] },
  { kind: "text", display: "في أي قارة تقع مصر؟", accepted: ["افريقيا", "أفريقيا"] },
  { kind: "text", display: "ما هي عملة السعودية؟", accepted: ["ريال", "الريال السعودي"] },
  { kind: "text", display: "كم عدد أضلاع المثلث؟", accepted: ["3", "ثلاثة", "ثلاث"] },
  { kind: "text", display: "ما اسم العضلة التي تضخ الدم بالجسم؟", accepted: ["القلب"] },
  { kind: "text", display: "ما هي أصغر دولة بالعالم من حيث المساحة؟", accepted: ["الفاتيكان"] },
  { kind: "text", display: "كم قارة اسمها يبدأ بحرف الألف؟", accepted: ["3", "ثلاثة", "ثلاث"] },
  { kind: "text", display: "ما اسم الكوكب الأحمر؟", accepted: ["المريخ"] },
  { kind: "text", display: "من أين تُستخرج مادة اللؤلؤ؟", accepted: ["المحار"] },
  { kind: "text", display: "ما هي أكبر دولة عربية من حيث المساحة؟", accepted: ["الجزائر"] },
  { kind: "text", display: "ما هي أصغر دولة عربية من حيث المساحة؟", accepted: ["البحرين"] },
  { kind: "text", display: "ما هي عاصمة فرنسا؟", accepted: ["باريس"] },
  { kind: "text", display: "ما هي عاصمة ألمانيا؟", accepted: ["برلين"] },
  { kind: "text", display: "ما هي عاصمة إيطاليا؟", accepted: ["روما"] },
  { kind: "text", display: "ما هي عاصمة إسبانيا؟", accepted: ["مدريد"] },
  { kind: "text", display: "ما هي عاصمة روسيا؟", accepted: ["موسكو"] },
  { kind: "text", display: "ما هي عاصمة الصين؟", accepted: ["بكين"] },
  { kind: "text", display: "ما هي عاصمة الهند؟", accepted: ["نيودلهي", "دلهي"] },
  { kind: "text", display: "ما هي عاصمة كندا؟", accepted: ["أوتاوا", "اوتاوا"] },
  { kind: "text", display: "ما هي عاصمة البرازيل؟", accepted: ["برازيليا"] },
  { kind: "text", display: "ما هي عاصمة تركيا؟", accepted: ["أنقرة", "انقره"] },
  { kind: "text", display: "ما هي عاصمة اليونان؟", accepted: ["أثينا", "اثينا"] },
  { kind: "text", display: "ما اسم أطول سلسلة جبال في العالم؟", accepted: ["الأنديز", "الانديز"] },
  { kind: "text", display: "ما هي أكبر قارة في العالم من حيث المساحة؟", accepted: ["آسيا", "اسيا"] },
  { kind: "text", display: "ما هي أصغر قارة في العالم؟", accepted: ["أستراليا", "استراليا"] },
  { kind: "text", display: "كم عدد المحيطات في العالم؟", accepted: ["5", "خمسة", "خمسه"] },
  { kind: "text", display: "ما هو أكبر محيط في العالم؟", accepted: ["الهادئ", "المحيط الهادئ", "الهادي", "المحيط الهادي"] },
  { kind: "text", display: "ما اسم أعلى قمة جبلية في العالم؟", accepted: ["إيفرست", "ايفرست"] },
  { kind: "text", display: "في أي دولة يقع برج إيفل؟", accepted: ["فرنسا"] },
  { kind: "text", display: "في أي دولة يقع تمثال الحرية؟", accepted: ["أمريكا", "امريكا", "الولايات المتحدة"] },
  { kind: "text", display: "في أي مدينة يقع الكولوسيوم؟", accepted: ["روما"] },
  { kind: "text", display: "ما اسم الدولة الاسكندنافية المعروفة بالفايكنغ وعاصمتها أوسلو؟", accepted: ["النرويج"] },
  { kind: "text", display: "ما هو الكوكب الأقرب للشمس؟", accepted: ["عطارد"] },
  { kind: "text", display: "ما هو أقرب نجم للأرض؟", accepted: ["الشمس"] },
  { kind: "text", display: "كم عدد عظام جسم الإنسان البالغ؟", accepted: ["206"] },
  { kind: "text", display: "ما هي وحدة قياس القوة؟", accepted: ["نيوتن"] },
  { kind: "text", display: "من مكتشف قانون الجاذبية؟", accepted: ["نيوتن", "إسحاق نيوتن", "اسحاق نيوتن"] },
  { kind: "text", display: "ما هو أكبر حيوان في العالم؟", accepted: ["الحوت الأزرق", "الحوت الازرق"] },
  { kind: "text", display: "ما هو أسرع حيوان بري في العالم؟", accepted: ["الفهد"] },
  { kind: "text", display: "كم عدد قلوب الأخطبوط؟", accepted: ["3", "ثلاثة", "ثلاثه", "ثلاث"] },
  { kind: "text", display: "ما هو العنصر الكيميائي الذي رمزه Fe؟", accepted: ["الحديد"] },
  { kind: "text", display: "ما هي درجة غليان الماء بالمئوية؟", accepted: ["100"] },
  { kind: "text", display: "ما هي درجة تجمد الماء بالمئوية؟", accepted: ["0", "صفر"] },
  { kind: "text", display: "كم عدد أرجل العنكبوت؟", accepted: ["8", "ثمانية", "ثمانيه"] },
  { kind: "text", display: "ما اسم العملية التي تحول فيها النباتات ضوء الشمس لطاقة؟", accepted: ["التمثيل الضوئي", "البناء الضوئي"] },
  { kind: "text", display: "كم عدد أسنان الإنسان البالغ؟", accepted: ["32"] },
  { kind: "text", display: "ما اسم الطبقة الغازية المحيطة بالأرض؟", accepted: ["الغلاف الجوي"] },
  { kind: "text", display: "من مخترع المصباح الكهربائي؟", accepted: ["توماس إديسون", "اديسون", "توماس اديسون"] },
  { kind: "text", display: "من مخترع الهاتف؟", accepted: ["غراهام بيل", "ألكسندر غراهام بيل", "الكسندر غراهام بيل"] },
  { kind: "text", display: "ما هو أكبر عضو في جسم الإنسان؟", accepted: ["الجلد"] },
  { kind: "text", display: "ما اسم الغدة التي تفرز الأنسولين في الجسم؟", accepted: ["البنكرياس"] },
  { kind: "text", display: "ما اسم القمر الطبيعي للأرض؟", accepted: ["القمر"] },
  { kind: "text", display: "كم عدد كواكب المجموعة الشمسية؟", accepted: ["8", "ثمانية", "ثمانيه"] },
  { kind: "text", display: "في أي عام بدأت الحرب العالمية الثانية؟", accepted: ["1939"] },
  { kind: "text", display: "في أي عام انتهت الحرب العالمية الثانية؟", accepted: ["1945"] },
  { kind: "text", display: "من هو أول رئيس لأمريكا؟", accepted: ["جورج واشنطن", "واشنطن"] },
  { kind: "text", display: "من هو مكتشف قارة أمريكا؟", accepted: ["كريستوفر كولومبوس", "كولومبوس"] },
  { kind: "text", display: "في أي دولة قامت حضارة الفراعنة؟", accepted: ["مصر"] },
  { kind: "text", display: "من هو أول خليفة للمسلمين؟", accepted: ["أبو بكر الصديق", "ابو بكر الصديق", "ابوبكر", "أبو بكر"] },
  { kind: "text", display: "في أي عام سقطت الأندلس؟", accepted: ["1492"] },
  { kind: "text", display: "من هو فاتح الأندلس؟", accepted: ["طارق بن زياد"] },
  { kind: "text", display: "في أي دولة يقع سور الصين العظيم؟", accepted: ["الصين"] },
  { kind: "text", display: "ما اسم الحرب التي استمرت قرابة 100 عام بين إنجلترا وفرنسا؟", accepted: ["حرب المئة عام", "حرب المئه عام"] },
  { kind: "text", display: "من هو مؤسس الدولة السعودية الأولى؟", accepted: ["محمد بن سعود", "الإمام محمد بن سعود", "الامام محمد بن سعود"] },
  { kind: "text", display: "ما اسم أول قمر صناعي أطلق للفضاء؟", accepted: ["سبوتنيك"] },
  { kind: "text", display: "من هو أول إنسان مشى على سطح القمر؟", accepted: ["نيل أرمسترونغ", "نيل ارمسترونغ"] },
  { kind: "text", display: "في أي عام هبط الإنسان أول مرة على القمر؟", accepted: ["1969"] },
  { kind: "text", display: "كم عدد لاعبي فريق كرة السلة بالملعب لكل فريق؟", accepted: ["5", "خمسة", "خمسه"] },
  { kind: "text", display: "كم عدد أشواط مباراة كرة القدم؟", accepted: ["2", "شوطين", "اثنين"] },
  { kind: "text", display: "كم دقيقة مدة الشوط الواحد بكرة القدم عادة؟", accepted: ["45"] },
  { kind: "text", display: "في أي دولة أقيمت أول كأس عالم لكرة القدم؟", accepted: ["الأوروغواي", "الاوروغواي"] },
  { kind: "text", display: "من الفريق الأكثر فوزاً بكأس العالم لكرة القدم؟", accepted: ["البرازيل"] },
  { kind: "text", display: "كم عدد الحلقات في الشعار الأولمبي؟", accepted: ["5", "خمسة", "خمسه"] },
  { kind: "text", display: "ما لون الحزام الأعلى في رياضة الجودو؟", accepted: ["الأسود", "الاسود"] },
  { kind: "text", display: "كم عدد اللاعبين بفريق الكرة الطائرة بالملعب؟", accepted: ["6", "ستة", "سته"] },
  { kind: "text", display: "في أي مدينة أقيمت أول ألعاب أولمبية حديثة؟", accepted: ["أثينا", "اثينا"] },
  { kind: "text", display: "ما اسم أول فيلم كرتون طويل أنتجته ديزني؟", accepted: ["بياض الثلج", "سنو وايت"] },
  { kind: "text", display: "من هو رسام لوحة الموناليزا؟", accepted: ["ليوناردو دافينشي", "دافينشي"] },
  { kind: "text", display: "ما اسم أشهر برج ساعة في لندن؟", accepted: ["بيغ بن", "بيج بن"] },
  { kind: "text", display: "في أي مدينة يقع متحف اللوفر؟", accepted: ["باريس"] },
  { kind: "text", display: "من مؤلف مسرحية \"روميو وجولييت\"؟", accepted: ["شكسبير", "وليم شكسبير"] },
  { kind: "text", display: "كم عدد حروف الهجاء بالأبجدية الإنجليزية؟", accepted: ["26"] },
  { kind: "text", display: "ما هو جمع كلمة \"قلم\"؟", accepted: ["أقلام", "اقلام"] },
  { kind: "text", display: "ما هو مضاد كلمة \"كبير\"؟", accepted: ["صغير"] },
  { kind: "text", display: "ما هو مرادف كلمة \"سعيد\"؟", accepted: ["فرحان", "مسرور"] },
  { kind: "text", display: "ما هو جمع كلمة \"كتاب\"؟", accepted: ["كتب"] },
  { kind: "text", display: "كم عدد أركان الإسلام؟", accepted: ["5", "خمسة", "خمسه"] },
  { kind: "text", display: "كم عدد أركان الإيمان؟", accepted: ["6", "ستة", "سته"] },
  { kind: "text", display: "كم عدد الصلوات المفروضة في اليوم؟", accepted: ["5", "خمس", "خمسة", "خمسه"] },
  { kind: "text", display: "ما اسم الشهر الذي يصوم فيه المسلمون؟", accepted: ["رمضان"] },
  { kind: "text", display: "كم عدد سور القرآن الكريم؟", accepted: ["114"] },
  { kind: "text", display: "ما هي أطول سورة في القرآن الكريم؟", accepted: ["البقرة"] },
  { kind: "text", display: "ما هي أقصر سورة في القرآن الكريم؟", accepted: ["الكوثر"] },
  { kind: "text", display: "في أي مدينة يقع المسجد الحرام؟", accepted: ["مكة", "مكه", "مكة المكرمة", "مكه المكرمه"] },
  { kind: "text", display: "في أي مدينة يقع المسجد النبوي؟", accepted: ["المدينة", "المدينه", "المدينة المنورة", "المدينه المنوره"] },
  { kind: "text", display: "من مؤسس شركة مايكروسوفت؟", accepted: ["بيل غيتس"] },
  { kind: "text", display: "من مؤسس شركة آبل؟", accepted: ["ستيف جوبز"] },
  { kind: "text", display: "في أي عام تأسس فيسبوك؟", accepted: ["2004"] },
  { kind: "text", display: "من مؤسس شركتي تسلا وسبيس إكس؟", accepted: ["إيلون ماسك", "ايلون ماسك"] },
  { kind: "text", display: "ما اسم متصفح الإنترنت التابع لجوجل؟", accepted: ["كروم", "جوجل كروم"] },
  { kind: "text", display: "ما هي عاصمة المملكة المتحدة؟", accepted: ["لندن"] },
  { kind: "text", display: "ما هي عاصمة هولندا؟", accepted: ["أمستردام", "امستردام"] },
  { kind: "text", display: "ما هي عاصمة البرتغال؟", accepted: ["لشبونة"] },
  { kind: "text", display: "ما هي عاصمة سويسرا؟", accepted: ["برن"] },
  { kind: "text", display: "ما هي عاصمة النمسا؟", accepted: ["فيينا"] },
  { kind: "text", display: "ما هي عاصمة بولندا؟", accepted: ["وارسو"] },
  { kind: "text", display: "ما هي عاصمة السويد؟", accepted: ["ستوكهولم"] },
  { kind: "text", display: "ما هي عاصمة كوريا الجنوبية؟", accepted: ["سيول"] },
  { kind: "text", display: "ما هي عاصمة إندونيسيا؟", accepted: ["جاكرتا"] },
  { kind: "text", display: "ما هي عاصمة تايلاند؟", accepted: ["بانكوك"] },
  { kind: "text", display: "ما هي عاصمة المكسيك؟", accepted: ["مكسيكو سيتي", "مدينة مكسيكو"] },
  { kind: "text", display: "ما هي عاصمة الأرجنتين؟", accepted: ["بوينس آيرس", "بوينس ايرس"] },
  { kind: "text", display: "ما هي عاصمة جنوب أفريقيا؟", accepted: ["بريتوريا"] },
  { kind: "text", display: "ما هي عاصمة نيجيريا؟", accepted: ["أبوجا", "ابوجا"] },
  { kind: "text", display: "ما هي عاصمة كينيا؟", accepted: ["نيروبي"] },
  { kind: "text", display: "ما هي عاصمة إثيوبيا؟", accepted: ["أديس أبابا", "اديس ابابا"] },
  { kind: "text", display: "ما هي عاصمة ليبيا؟", accepted: ["طرابلس"] },
  { kind: "text", display: "ما هي عاصمة تونس؟", accepted: ["تونس"] },
  { kind: "text", display: "ما هي عاصمة السودان؟", accepted: ["الخرطوم"] },
  { kind: "text", display: "ما هي عاصمة العراق؟", accepted: ["بغداد"] },
  { kind: "text", display: "ما هي عاصمة سوريا؟", accepted: ["دمشق"] },
  { kind: "text", display: "ما هي عاصمة لبنان؟", accepted: ["بيروت"] },
  { kind: "text", display: "ما هي عاصمة الأردن؟", accepted: ["عمان"] },
  { kind: "text", display: "ما هي عاصمة اليمن؟", accepted: ["صنعاء"] },
  { kind: "text", display: "ما هي عاصمة عُمان؟", accepted: ["مسقط"] },
  { kind: "text", display: "ما هي عاصمة قطر؟", accepted: ["الدوحة"] },
  { kind: "text", display: "ما هي عاصمة الكويت؟", accepted: ["الكويت"] },
  { kind: "text", display: "ما هي عاصمة البحرين؟", accepted: ["المنامة"] },
  { kind: "text", display: "ما هي عاصمة الإمارات؟", accepted: ["أبوظبي", "ابوظبي"] },
  { kind: "text", display: "ما هي عاصمة المغرب؟", accepted: ["الرباط"] },
  { kind: "text", display: "ما هو أصغر عظم في جسم الإنسان؟", accepted: ["الركابي"] },
  { kind: "text", display: "كم عدد فقرات العمود الفقري عند الإنسان؟", accepted: ["33"] },
  { kind: "text", display: "ما هو العضو المسؤول عن تنقية الدم؟", accepted: ["الكلى", "الكلية"] },
  { kind: "text", display: "ما اسم العلم الذي يدرس النجوم والكواكب؟", accepted: ["الفلك", "علم الفلك"] },
  { kind: "text", display: "ما هو الغاز الذي تطلقه النباتات أثناء التمثيل الضوئي؟", accepted: ["الأكسجين"] },
  { kind: "text", display: "ما اسم أصغر وحدة في الكائن الحي؟", accepted: ["الخلية"] },
  { kind: "text", display: "ما هي وحدة قياس شدة التيار الكهربائي؟", accepted: ["الأمبير"] },
  { kind: "text", display: "ما هي وحدة قياس الحرارة؟", accepted: ["السيلسيوس", "الدرجة المئوية", "كلفن"] },
  { kind: "text", display: "من مكتشف البنسلين؟", accepted: ["ألكسندر فليمنغ", "الكسندر فليمنغ", "فليمنغ"] },
  { kind: "text", display: "ما هو الكوكب المعروف بحلقاته؟", accepted: ["زحل"] },
  { kind: "text", display: "كم عدد أقمار كوكب الأرض؟", accepted: ["1", "واحد", "قمر واحد"] },
  { kind: "text", display: "ما اسم أول حيوان أُرسل إلى الفضاء؟", accepted: ["الكلبة لايكا", "لايكا"] },
  { kind: "text", display: "ما هي المادة التي تصنع منها أقلام الرصاص؟", accepted: ["الجرافيت"] },
  { kind: "text", display: "ما اسم العالم الذي وضع النظرية النسبية؟", accepted: ["ألبرت أينشتاين", "اينشتاين"] },
  { kind: "text", display: "كم عدد حواس الإنسان الأساسية؟", accepted: ["5", "خمسة", "خمسه"] },
  { kind: "text", display: "ما اسم الحشرة التي تنتج العسل؟", accepted: ["النحلة"] },
  { kind: "text", display: "ما هو أطول حيوان بري في العالم؟", accepted: ["الزرافة"] },
  { kind: "text", display: "من هو قائد معركة بدر من المسلمين؟", accepted: ["الرسول محمد", "الرسول صلى الله عليه وسلم", "النبي محمد"] },
  { kind: "text", display: "في أي عام كانت الهجرة النبوية؟", accepted: ["622"] },
  { kind: "text", display: "ما اسم أول عاصمة للدولة الإسلامية؟", accepted: ["المدينة المنورة", "المدينة"] },
  { kind: "text", display: "من هو الخليفة الراشد الرابع؟", accepted: ["علي بن أبي طالب", "علي"] },
  { kind: "text", display: "من هو فاتح القسطنطينية؟", accepted: ["محمد الفاتح"] },
  { kind: "text", display: "في أي عام سقطت القسطنطينية؟", accepted: ["1453"] },
  { kind: "text", display: "من هو قائد جيش المسلمين في معركة اليرموك؟", accepted: ["خالد بن الوليد"] },
  { kind: "text", display: "ما اسم الحرب التي نشبت بين دول أوروبا 1914؟", accepted: ["الحرب العالمية الأولى"] },
  { kind: "text", display: "من هو الرئيس الأمريكي إبان الحرب الأهلية؟", accepted: ["أبراهام لينكولن", "ابراهام لينكولن"] },
  { kind: "text", display: "من هو مكتشف قارة أستراليا؟", accepted: ["جيمس كوك"] },
  { kind: "text", display: "ما اسم السفينة التي غرقت عام 1912؟", accepted: ["تايتانيك"] },
  { kind: "text", display: "من هو أول ملك لتوحيد المملكة العربية السعودية؟", accepted: ["الملك عبدالعزيز", "عبدالعزيز آل سعود"] },
  { kind: "text", display: "في أي عام تأسست المملكة العربية السعودية؟", accepted: ["1932"] },
  { kind: "text", display: "كم عدد اللاعبين في فريق البيسبول؟", accepted: ["9", "تسعة", "تسعه"] },
  { kind: "text", display: "كم شوطاً في مباراة كرة السلة؟", accepted: ["4", "أربعة", "اربعه"] },
  { kind: "text", display: "في أي دولة أقيمت أولمبياد 2016؟", accepted: ["البرازيل"] },
  { kind: "text", display: "في أي دولة أقيمت كأس العالم 2022؟", accepted: ["قطر"] },
  { kind: "text", display: "من هو الهداف التاريخي لكأس العالم؟", accepted: ["ميروسلاف كلوزه", "كلوزه"] },
  { kind: "text", display: "كم عدد أشواط مباراة التنس للرجال في البطولات الكبرى؟", accepted: ["5", "خمسة", "خمسه"] },
  { kind: "text", display: "ما اسم الرياضة التي تُلعب بمضرب وريشة؟", accepted: ["الريشة الطائرة", "البادمنتون"] },
  { kind: "text", display: "كم عدد حلقات كرة السلة اللازمة لبدء المباراة بكل فريق؟", accepted: ["5", "خمسة", "خمسه"] },
  { kind: "text", display: "ما هي الرياضة الوطنية لليابان؟", accepted: ["السومو"] },
  { kind: "text", display: "كم دقيقة مدة مباراة كرة السلة الاحترافية؟", accepted: ["48"] },
  { kind: "text", display: "من رسام لوحة \"الصرخة\"؟", accepted: ["إدفارد مونك", "ادفارد مونك"] },
  { kind: "text", display: "من مؤلف رواية \"الحرب والسلام\"؟", accepted: ["ليو تولستوي", "تولستوي"] },
  { kind: "text", display: "من مخرج فيلم \"تيتانيك\"؟", accepted: ["جيمس كاميرون"] },
  { kind: "text", display: "ما اسم أشهر متحف للفن في نيويورك؟", accepted: ["متحف المتروبوليتان"] },
  { kind: "text", display: "من ملحن السيمفونية التاسعة؟", accepted: ["بيتهوفن"] },
  { kind: "text", display: "ما اسم فرقة البيتلز الموسيقية بلد المنشأ؟", accepted: ["بريطانيا", "إنجلترا", "انجلترا"] },
  { kind: "text", display: "ما هو مرادف كلمة \"جميل\"؟", accepted: ["حسن", "بديع"] },
  { kind: "text", display: "ما هو مضاد كلمة \"طويل\"؟", accepted: ["قصير"] },
  { kind: "text", display: "ما هو جمع كلمة \"رجل\"؟", accepted: ["رجال"] },
  { kind: "text", display: "ما هو جمع كلمة \"بيت\"؟", accepted: ["بيوت"] },
  { kind: "text", display: "ما هو مضاد كلمة \"قوي\"؟", accepted: ["ضعيف"] },
  { kind: "text", display: "كم عدد حروف العلة في اللغة العربية؟", accepted: ["3", "ثلاثة", "ثلاث"] },
  { kind: "text", display: "ما اسم علامة الترقيم التي تدل على السؤال؟", accepted: ["علامة الاستفهام"] },
  { kind: "text", display: "ما هو مرادف كلمة \"شجاع\"؟", accepted: ["جريء", "باسل"] },
  { kind: "text", display: "كم عدد سور القرآن المكية؟", accepted: ["86"] },
  { kind: "text", display: "كم عدد سور القرآن المدنية؟", accepted: ["28"] },
  { kind: "text", display: "ما هي أول غزوة في الإسلام؟", accepted: ["غزوة بدر"] },
  { kind: "text", display: "ما اسم الملك الذي بنى سد مأرب؟", accepted: ["سبأ", "سد مأرب بناه قوم سبأ"] },
  { kind: "text", display: "كم عدد الأنبياء المذكورين في القرآن الكريم؟", accepted: ["25"] },
  { kind: "text", display: "ما اسم أول رسول أرسله الله؟", accepted: ["نوح"] },
  { kind: "text", display: "ما اسم النبي الذي ابتلعه الحوت؟", accepted: ["يونس"] },
  { kind: "text", display: "من مخترع أول جهاز حاسوب شخصي؟", accepted: ["ستيف وزنياك"] },
  { kind: "text", display: "ما اسم أول شبكة تواصل اجتماعي منتشرة؟", accepted: ["ماي سبيس", "فيسبوك"] },
  { kind: "text", display: "من مؤسس شركة أمازون؟", accepted: ["جيف بيزوس"] },
  { kind: "text", display: "ما اسم نظام تشغيل هواتف آيفون؟", accepted: ["iOS", "آي أو إس"] },
  { kind: "text", display: "في أي عام تأسست شركة جوجل؟", accepted: ["1998"] },
  { kind: "text", display: "ما اسم أول لغة برمجة شائعة الاستخدام؟", accepted: ["فورتران"] },
  { kind: "text", display: "من مؤسس شركة تويتر (إكس)؟", accepted: ["جاك دورسي"] },
  { kind: "text", display: "ما اسم شبكة الإنترنت العنكبوتية اختصاراً؟", accepted: ["WWW", "الويب"] },
  { kind: "text", display: "ما اسم أول قمر صناعي عربي؟", accepted: ["عربسات"] },
  { kind: "text", display: "ما هي عاصمة النرويج؟", accepted: ["أوسلو", "اوسلو"] },
  { kind: "text", display: "ما هي عاصمة الدنمارك؟", accepted: ["كوبنهاغن"] },
  { kind: "text", display: "ما هي عاصمة فنلندا؟", accepted: ["هلسنكي"] },
  { kind: "text", display: "ما هي عاصمة أيرلندا؟", accepted: ["دبلن"] },
  { kind: "text", display: "ما هي عاصمة بلجيكا؟", accepted: ["بروكسل"] },
  { kind: "text", display: "ما هي عاصمة رومانيا؟", accepted: ["بوخارست"] },
  { kind: "text", display: "ما هي عاصمة المجر؟", accepted: ["بودابست"] },
  { kind: "text", display: "ما هي عاصمة تشيكيا؟", accepted: ["براغ"] },
  { kind: "text", display: "ما هي عاصمة أوكرانيا؟", accepted: ["كييف"] },
  { kind: "text", display: "ما هي عاصمة كوبا؟", accepted: ["هافانا"] },
  { kind: "text", display: "ما هي عاصمة تشيلي؟", accepted: ["سانتياغو"] },
  { kind: "text", display: "ما هي عاصمة بيرو؟", accepted: ["ليما"] },
  { kind: "text", display: "ما هي عاصمة كولومبيا؟", accepted: ["بوغوتا"] },
  { kind: "text", display: "ما هي عاصمة فنزويلا؟", accepted: ["كاراكاس"] },
  { kind: "text", display: "ما هي عاصمة نيوزيلندا؟", accepted: ["ويلينغتون"] },
  { kind: "text", display: "ما هي عاصمة ماليزيا؟", accepted: ["كوالالمبور"] },
  { kind: "text", display: "ما هي عاصمة الفلبين؟", accepted: ["مانيلا"] },
  { kind: "text", display: "ما هي عاصمة فيتنام؟", accepted: ["هانوي"] },
  { kind: "text", display: "ما هي عاصمة باكستان؟", accepted: ["إسلام آباد", "اسلام اباد"] },
  { kind: "text", display: "ما هي عاصمة أفغانستان؟", accepted: ["كابل"] },
  { kind: "text", display: "ما هي عاصمة إيران؟", accepted: ["طهران"] },
  { kind: "text", display: "ما هي عاصمة موريتانيا؟", accepted: ["نواكشوط"] },
  { kind: "text", display: "ما هي عاصمة الصومال؟", accepted: ["مقديشو"] },
  { kind: "text", display: "ما هي عاصمة جيبوتي؟", accepted: ["جيبوتي"] },
  { kind: "text", display: "ما هي عاصمة السنغال؟", accepted: ["داكار"] },
  { kind: "text", display: "ما اسم أصغر عظم يوجد بالأذن؟", accepted: ["الركابي"] },
  { kind: "text", display: "ما اسم الغشاء الذي يحيط بالقلب؟", accepted: ["التامور"] },
  { kind: "text", display: "كم عدد فصوص الرئة اليمنى؟", accepted: ["3", "ثلاثة", "ثلاث"] },
  { kind: "text", display: "ما اسم الخلايا المسؤولة عن نقل الأكسجين بالدم؟", accepted: ["كريات الدم الحمراء"] },
  { kind: "text", display: "ما هي وحدة قياس الضغط الجوي؟", accepted: ["الباسكال"] },
  { kind: "text", display: "ما اسم القوة التي تجذب الأجسام نحو الأرض؟", accepted: ["الجاذبية"] },
  { kind: "text", display: "من مكتشف الكهرباء الساكنة عبر تجربة الطائرة الورقية؟", accepted: ["بنجامين فرانكلين"] },
  { kind: "text", display: "ما اسم أول عملية استنساخ ناجحة لحيوان؟", accepted: ["النعجة دوللي", "دوللي"] },
  { kind: "text", display: "ما هو الكوكب الأصغر في المجموعة الشمسية؟", accepted: ["عطارد"] },
  { kind: "text", display: "ما اسم المجرة التي تنتمي إليها الأرض؟", accepted: ["درب التبانة"] },
  { kind: "text", display: "ما هو أثقل عنصر طبيعي معروف؟", accepted: ["اليورانيوم"] },
  { kind: "text", display: "ما اسم الظاهرة التي تصف انحناء الضوء في الصحراء؟", accepted: ["السراب"] },
  { kind: "text", display: "ما هو الحيوان الوحيد الذي لا يستطيع القفز؟", accepted: ["الفيل"] },
  { kind: "text", display: "ما اسم أكبر جزيرة في العالم؟", accepted: ["غرينلاند"] },
  { kind: "text", display: "كم عدد فصول السنة؟", accepted: ["4", "أربعة", "اربعه"] },
  { kind: "text", display: "من هو مؤسس الدولة الأموية؟", accepted: ["معاوية بن أبي سفيان", "معاوية"] },
  { kind: "text", display: "من هو مؤسس الدولة العباسية؟", accepted: ["أبو العباس السفاح", "السفاح"] },
  { kind: "text", display: "من فتح مصر في عهد عمر بن الخطاب؟", accepted: ["عمرو بن العاص"] },
  { kind: "text", display: "في أي معركة انتصر المسلمون على الفرس بشكل حاسم؟", accepted: ["معركة القادسية"] },
  { kind: "text", display: "من هو مؤسس الدولة الفاطمية؟", accepted: ["عبيد الله المهدي"] },
  { kind: "text", display: "من هو صلاح الدين الأيوبي الذي حرر القدس؟", accepted: ["صلاح الدين الأيوبي", "صلاح الدين"] },
  { kind: "text", display: "في أي عام تم تحرير القدس على يد صلاح الدين؟", accepted: ["1187"] },
  { kind: "text", display: "ما اسم الحرب التي شنها الأوروبيون على بلاد الشام؟", accepted: ["الحروب الصليبية"] },
  { kind: "text", display: "من هو أول رئيس لجمهورية مصر؟", accepted: ["محمد نجيب"] },
  { kind: "text", display: "من هو الزعيم الذي قاد ثورة الجزائر؟", accepted: ["أحمد بن بلة"] },
  { kind: "text", display: "في أي عام استقلت الجزائر عن فرنسا؟", accepted: ["1962"] },
  { kind: "text", display: "من هو مكتشف أمريكا الجنوبية؟", accepted: ["أمريكو فسبوتشي"] },
  { kind: "text", display: "في أي عام سقط جدار برلين؟", accepted: ["1989"] },
  { kind: "text", display: "ما اسم أول امرأة حكمت مصر القديمة؟", accepted: ["حتشبسوت"] },
  { kind: "text", display: "كم عدد اللاعبين في فريق الهوكي على الجليد؟", accepted: ["6", "ستة", "سته"] },
  { kind: "text", display: "ما اسم البطولة الأكبر لكرة القدم الأوروبية للأندية؟", accepted: ["دوري أبطال أوروبا"] },
  { kind: "text", display: "من الفريق الأكثر تتويجاً بدوري أبطال أوروبا؟", accepted: ["ريال مدريد"] },
  { kind: "text", display: "كم عدد الأشواط في مباراة الكريكيت التقليدية؟", accepted: ["2", "شوطين", "اثنين"] },
  { kind: "text", display: "ما اسم الرياضة التي تلعب على الجليد بمكانس وحجارة؟", accepted: ["الكيرلنغ"] },
  { kind: "text", display: "كم عدد اللاعبين بفريق الرغبي؟", accepted: ["15", "خمسة عشر"] },
  { kind: "text", display: "ما اسم أشهر سباق دراجات في العالم؟", accepted: ["تور دو فرانس"] },
  { kind: "text", display: "كم مرة استضافت البرازيل كأس العالم؟", accepted: ["2", "مرتين"] },
  { kind: "text", display: "ما اسم الملعب الذي يستضيف نهائي كأس العالم غالباً؟", accepted: ["يختلف حسب الدولة المضيفة"] },
  { kind: "text", display: "من مؤلف رواية \"مئة عام من العزلة\"؟", accepted: ["غابرييل غارسيا ماركيز", "ماركيز"] },
  { kind: "text", display: "من مؤلف رواية \"البؤساء\"؟", accepted: ["فيكتور هوغو"] },
  { kind: "text", display: "من رسام لوحة \"ليلة النجوم\"؟", accepted: ["فان جوخ"] },
  { kind: "text", display: "من ملحن أوبرا \"الزهرة\"؟", accepted: ["فيردي"] },
  { kind: "text", display: "ما اسم أشهر مسرح في لندن؟", accepted: ["مسرح غلوب"] },
  { kind: "text", display: "من مخرج سلسلة أفلام \"هاري بوتر\" الأولى؟", accepted: ["كريس كولومبوس"] },
  { kind: "text", display: "ما اسم الجائزة الأشهر في صناعة السينما العالمية؟", accepted: ["الأوسكار"] },
  { kind: "text", display: "ما هو مرادف كلمة \"ذكي\"؟", accepted: ["فطن", "نبيه"] },
  { kind: "text", display: "ما هو مضاد كلمة \"بعيد\"؟", accepted: ["قريب"] },
  { kind: "text", display: "ما هو جمع كلمة \"طفل\"؟", accepted: ["أطفال"] },
  { kind: "text", display: "ما هو جمع كلمة \"نجم\"؟", accepted: ["نجوم"] },
  { kind: "text", display: "ما هو مضاد كلمة \"فرح\"؟", accepted: ["حزن"] },
  { kind: "text", display: "ما اسم علم النحو الذي يهتم بضبط أواخر الكلمات؟", accepted: ["الإعراب"] },
  { kind: "text", display: "ما هو مرادف كلمة \"جبان\"؟", accepted: ["خائف", "وجل"] },
  { kind: "text", display: "كم عدد الأحرف الشمسية في اللغة العربية؟", accepted: ["14", "أربعة عشر"] },
  { kind: "text", display: "ما هي أول كلمة نزلت في القرآن الكريم؟", accepted: ["اقرأ"] },
  { kind: "text", display: "ما اسم السورة التي سميت باسم امرأة؟", accepted: ["مريم"] },
  { kind: "text", display: "كم عدد أيام شهر رمضان عادة؟", accepted: ["29", "30", "تسعة وعشرون أو ثلاثون"] },
  { kind: "text", display: "ما اسم الليلة التي يُستحب فيها قيام الليل بالعشر الأواخر من رمضان؟", accepted: ["ليلة القدر"] },
  { kind: "text", display: "ما اسم الركن الخامس من أركان الإسلام؟", accepted: ["الحج"] },
  { kind: "text", display: "في أي شهر يؤدى فريضة الحج؟", accepted: ["ذو الحجة"] },
  { kind: "text", display: "ما اسم اليوم الذي يقف فيه الحجاج بعرفة؟", accepted: ["يوم عرفة"] },
  { kind: "text", display: "من مؤسس شركة سامسونج؟", accepted: ["لي بيونغ تشول"] },
  { kind: "text", display: "ما اسم أول متصفح إنترنت شائع؟", accepted: ["نتسكيب"] },
  { kind: "text", display: "من مخترع شبكة الويب العالمية؟", accepted: ["تيم بيرنرز لي"] },
  { kind: "text", display: "ما اسم أول هاتف ذكي أطلقته شركة آبل؟", accepted: ["آيفون"] },
  { kind: "text", display: "من مؤسس شركة نتفليكس؟", accepted: ["ريد هاستنغز"] },
  { kind: "text", display: "ما اسم أول شبكة اجتماعية أطلقتها شركة ميتا؟", accepted: ["فيسبوك"] },
  { kind: "text", display: "في أي عام أُطلق أول آيفون؟", accepted: ["2007"] },
  { kind: "text", display: "ما اسم اللغة البرمجية الأكثر استخدماً في تطوير الويب؟", accepted: ["جافا سكريبت"] },
  { kind: "text", display: "من مؤسس شركة إنستغرام؟", accepted: ["كيفن سيستروم"] },
  { kind: "text", display: "ما اسم نظام التشغيل مفتوح المصدر الأشهر؟", accepted: ["لينكس"] },
  { kind: "text", display: "من مؤسس شركة سبيس إكس بالإضافة لتسلا؟", accepted: ["إيلون ماسك", "ايلون ماسك"] },
  { kind: "text", display: "ما اسم أول قمر صناعي عربي أطلقته السعودية؟", accepted: ["سعودي سات"] },
  { kind: "text", display: "ما اسم شركة الطيران السعودية الوطنية؟", accepted: ["الخطوط السعودية"] },
  { kind: "text", display: "ما اسم أول جامعة أُنشئت في العالم؟", accepted: ["جامعة القرويين"] },
  { kind: "text", display: "ما اسم أقدم لغة مكتوبة معروفة؟", accepted: ["السومرية"] },
  { kind: "text", display: "ما هي عاصمة كرواتيا؟", accepted: ["زغرب"] },
  { kind: "text", display: "ما هي عاصمة صربيا؟", accepted: ["بلغراد"] },
  { kind: "text", display: "ما هي عاصمة بلغاريا؟", accepted: ["صوفيا"] },
  { kind: "text", display: "ما هي عاصمة سلوفاكيا؟", accepted: ["براتيسلافا"] },
  { kind: "text", display: "ما هي عاصمة أيسلندا؟", accepted: ["ريكيافيك"] },
  { kind: "text", display: "ما هي عاصمة لاتفيا؟", accepted: ["ريغا"] },
  { kind: "text", display: "ما هي عاصمة ليتوانيا؟", accepted: ["فيلنيوس"] },
  { kind: "text", display: "ما هي عاصمة إستونيا؟", accepted: ["تالين"] },
  { kind: "text", display: "ما هي عاصمة جورجيا؟", accepted: ["تبليسي"] },
  { kind: "text", display: "ما هي عاصمة أرمينيا؟", accepted: ["يريفان"] },
  { kind: "text", display: "ما هي عاصمة أذربيجان؟", accepted: ["باكو"] },
  { kind: "text", display: "ما هي عاصمة كازاخستان؟", accepted: ["أستانا", "استانا"] },
  { kind: "text", display: "ما هي عاصمة أوزبكستان؟", accepted: ["طشقند"] },
  { kind: "text", display: "ما هي عاصمة منغوليا؟", accepted: ["أولان باتور", "اولان باتور"] },
  { kind: "text", display: "ما هي عاصمة بنغلاديش؟", accepted: ["دكا"] },
  { kind: "text", display: "ما هي عاصمة سريلانكا؟", accepted: ["كولومبو"] },
  { kind: "text", display: "ما هي عاصمة نيبال؟", accepted: ["كاتماندو"] },
  { kind: "text", display: "ما هي عاصمة ميانمار؟", accepted: ["نايبيداو"] },
  { kind: "text", display: "ما هي عاصمة كمبوديا؟", accepted: ["بنوم بنه"] },
  { kind: "text", display: "ما هي عاصمة لاوس؟", accepted: ["فينتيان"] },
  { kind: "text", display: "ما هي عاصمة الإكوادور؟", accepted: ["كيتو"] },
  { kind: "text", display: "ما هي عاصمة بوليفيا؟", accepted: ["لاباز"] },
  { kind: "text", display: "ما هي عاصمة باراغواي؟", accepted: ["أسونسيون", "اسونسيون"] },
  { kind: "text", display: "ما هي عاصمة أوروغواي؟", accepted: ["مونتيفيديو"] },
  { kind: "text", display: "ما هي عاصمة بنما؟", accepted: ["بنما"] },
  { kind: "text", display: "ما هي عاصمة غانا؟", accepted: ["أكرا", "اكرا"] },
  { kind: "text", display: "ما هي عاصمة تنزانيا؟", accepted: ["دودوما"] },
  { kind: "text", display: "ما هي عاصمة أوغندا؟", accepted: ["كمبالا"] },
  { kind: "text", display: "ما هي عاصمة زيمبابوي؟", accepted: ["هراري"] },
  { kind: "text", display: "ما هي عاصمة الكاميرون؟", accepted: ["ياوندي"] },
  { kind: "text", display: "ما اسم أكبر عضلة في جسم الإنسان؟", accepted: ["العضلة الألوية"] },
  { kind: "text", display: "ما اسم السائل الذي يزلق المفاصل؟", accepted: ["السائل الزلالي"] },
  { kind: "text", display: "كم عدد الحواس التي يمتلكها الإنسان بالإضافة للحواس الخمس (التوازن)؟", accepted: ["حاسة التوازن"] },
  { kind: "text", display: "ما اسم الهرمون المسؤول عن النمو؟", accepted: ["هرمون النمو"] },
  { kind: "text", display: "ما اسم العضو المسؤول عن إفراز الصفراء؟", accepted: ["الكبد"] },
  { kind: "text", display: "ما هي وحدة قياس التردد؟", accepted: ["الهرتز"] },
  { kind: "text", display: "ما هي وحدة قياس الطاقة؟", accepted: ["الجول"] },
  { kind: "text", display: "من مكتشف أشعة إكس؟", accepted: ["فيلهلم رونتغن", "رونتغن"] },
  { kind: "text", display: "ما اسم العالم الذي طور نظرية التطور؟", accepted: ["تشارلز داروين", "داروين"] },
  { kind: "text", display: "ما هو الغاز الأكثر وفرة في الغلاف الجوي؟", accepted: ["النيتروجين"] },
  { kind: "text", display: "ما اسم أكبر قمر في المجموعة الشمسية؟", accepted: ["غانيميد"] },
  { kind: "text", display: "ما اسم النجم الأقرب إلى الأرض بعد الشمس؟", accepted: ["بروكسيما سنتوري", "بروكسيما"] },
  { kind: "text", display: "كم يستغرق ضوء الشمس للوصول إلى الأرض؟", accepted: ["8 دقائق", "ثماني دقائق"] },
  { kind: "text", display: "ما اسم أول امرأة تسافر إلى الفضاء؟", accepted: ["فالنتينا تريشكوفا"] },
  { kind: "text", display: "ما اسم أول رجل مشى في الفضاء المفتوح؟", accepted: ["أليكسي ليونوف"] },
  { kind: "text", display: "ما هو أعمق محيط في العالم؟", accepted: ["المحيط الهادئ"] },
  { kind: "text", display: "ما اسم أعمق نقطة في المحيطات؟", accepted: ["خندق ماريانا"] },
  { kind: "text", display: "ما اسم أكبر صحراء باردة في العالم؟", accepted: ["القارة القطبية الجنوبية"] },
  { kind: "text", display: "من هو مؤسس الدولة الأيوبية؟", accepted: ["صلاح الدين الأيوبي", "صلاح الدين"] },
  { kind: "text", display: "من هو مؤسس الدولة المملوكية؟", accepted: ["عز الدين أيبك"] },
  { kind: "text", display: "من هو السلطان العثماني الذي فتح مصر؟", accepted: ["سليم الأول"] },
  { kind: "text", display: "ما اسم أول خليفة عباسي؟", accepted: ["أبو العباس السفاح", "السفاح"] },
  { kind: "text", display: "من هو قائد معركة عين جالوت؟", accepted: ["سيف الدين قطز", "قطز"] },
  { kind: "text", display: "في أي عام وقعت معركة عين جالوت؟", accepted: ["1260"] },
  { kind: "text", display: "من هو مؤسس الدولة السلجوقية؟", accepted: ["طغرل بك"] },
  { kind: "text", display: "من هو القائد الذي هزم المغول في عين جالوت؟", accepted: ["قطز وبيبرس"] },
  { kind: "text", display: "في أي عام سقطت بغداد على يد المغول؟", accepted: ["1258"] },
  { kind: "text", display: "من هو مؤسس الدولة الإدريسية بالمغرب؟", accepted: ["إدريس الأول"] },
  { kind: "text", display: "من هو أول رئيس لجمهورية تركيا؟", accepted: ["مصطفى أتاتورك", "أتاتورك"] },
  { kind: "text", display: "من هو أول رئيس أمريكي أسود؟", accepted: ["باراك أوباما"] },
  { kind: "text", display: "في أي عام انتهت الحرب الباردة؟", accepted: ["1991"] },
  { kind: "text", display: "ما اسم الاتفاقية التي أنهت الحرب العالمية الأولى؟", accepted: ["معاهدة فرساي"] },
  { kind: "text", display: "في أي عام تأسست منظمة الأمم المتحدة؟", accepted: ["1945"] },
  { kind: "text", display: "كم عدد اللاعبين في فريق البولو المائي؟", accepted: ["7", "سبعة", "سبعه"] },
  { kind: "text", display: "ما اسم البطولة الرباعية الكبرى في التنس؟", accepted: ["البطولات الأربع الكبرى", "الغراند سلام"] },
  { kind: "text", display: "من الفريق الأكثر تتويجاً بالدوري الإنجليزي؟", accepted: ["مانشستر يونايتد"] },
  { kind: "text", display: "كم عدد الحلقات الأولمبية الملونة؟", accepted: ["5", "خمسة", "خمسه"] },
  { kind: "text", display: "ما اسم أول دولة استضافت الألعاب الأولمبية الشتوية؟", accepted: ["فرنسا"] },
  { kind: "text", display: "كم عدد اللاعبين الأساسيين في فريق الهوكي الميداني؟", accepted: ["11", "أحد عشر"] },
  { kind: "text", display: "ما اسم أشهر سباق للخيول في بريطانيا؟", accepted: ["ديربي إنجلترا"] },
  { kind: "text", display: "كم عدد جولات الملاكمة الاحترافية القياسية؟", accepted: ["12", "اثنا عشر"] },
  { kind: "text", display: "ما اسم الرياضة التي تجمع الجري والسباحة وركوب الدراجات؟", accepted: ["الترياثلون"] },
  { kind: "text", display: "كم متراً طول حلبة الجري الأولمبية القياسية؟", accepted: ["400"] },
  { kind: "text", display: "من مؤلف رواية \"الأمير الصغير\"؟", accepted: ["أنطوان دو سانت إكزوبيري"] },
  { kind: "text", display: "من مؤلف \"ألف ليلة وليلة\" الأصلية؟", accepted: ["مجهول المؤلف", "مجهول"] },
  { kind: "text", display: "من رسام لوحة \"غيرنيكا\"؟", accepted: ["بابلو بيكاسو", "بيكاسو"] },
  { kind: "text", display: "من ملحن أوبرا \"الناي السحري\"؟", accepted: ["موزارت"] },
  { kind: "text", display: "ما اسم أشهر متحف فني في مدريد؟", accepted: ["متحف برادو"] },
  { kind: "text", display: "من مخرج فيلم \"العراب\"؟", accepted: ["فرانسيس فورد كوبولا"] },
  { kind: "text", display: "ما اسم أول فيلم ناطق في تاريخ السينما؟", accepted: ["مغني الجاز"] },
  { kind: "text", display: "من مؤلف مسرحية \"هاملت\"؟", accepted: ["شكسبير", "وليم شكسبير"] },
  { kind: "text", display: "ما اسم فرقة الروك الشهيرة \"كوين\" ومغنيها الرئيسي؟", accepted: ["فريدي ميركوري"] },
  { kind: "text", display: "ما هو مرادف كلمة \"عادل\"؟", accepted: ["منصف", "مقسط"] },
  { kind: "text", display: "ما هو مضاد كلمة \"نظيف\"؟", accepted: ["وسخ", "قذر"] },
  { kind: "text", display: "ما هو جمع كلمة \"قمر\"؟", accepted: ["أقمار"] },
  { kind: "text", display: "ما هو جمع كلمة \"يد\"؟", accepted: ["أيدي", "أيادي"] },
  { kind: "text", display: "ما هو مضاد كلمة \"سهل\"؟", accepted: ["صعب"] },
  { kind: "text", display: "ما اسم العلم الذي يهتم بدراسة معاني الكلمات؟", accepted: ["علم الدلالة"] },
  { kind: "text", display: "ما هو مرادف كلمة \"كريم\"؟", accepted: ["سخي", "جواد"] },
  { kind: "text", display: "كم عدد الأحرف القمرية في اللغة العربية؟", accepted: ["14", "أربعة عشر"] },
  { kind: "text", display: "ما هو أول ديوان شعري معروف بالعربية؟", accepted: ["المعلقات"] },
  { kind: "text", display: "ما اسم علامة الترقيم التي تفصل بين جمل مترابطة؟", accepted: ["الفاصلة المنقوطة", "الفاصلة"] },
  { kind: "text", display: "ما اسم السورة التي تعدل ثلث القرآن؟", accepted: ["الإخلاص"] },
  { kind: "text", display: "كم عدد آيات سورة الفاتحة؟", accepted: ["7", "سبع", "سبعة"] },
  { kind: "text", display: "ما اسم الغزوة التي حفر فيها المسلمون خندقاً حول المدينة؟", accepted: ["غزوة الخندق"] },
  { kind: "text", display: "ما اسم الصلح الذي وقعه المسلمون مع قريش قبل فتح مكة؟", accepted: ["صلح الحديبية"] },
  { kind: "text", display: "في أي عام كان فتح مكة؟", accepted: ["630", "8 هجري"] },
  { kind: "text", display: "ما اسم أول مسجد بني في الإسلام؟", accepted: ["مسجد قباء"] },
  { kind: "text", display: "من هو مؤذن الرسول صلى الله عليه وسلم؟", accepted: ["بلال بن رباح"] },
  { kind: "text", display: "ما اسم كاتب الوحي المشهور؟", accepted: ["زيد بن ثابت"] },
  { kind: "text", display: "من مؤسس شركة ياهو؟", accepted: ["جيري يانغ"] },
  { kind: "text", display: "من مؤسس شركة إيباي؟", accepted: ["بيير أوميديار"] },
  { kind: "text", display: "ما اسم أول لعبة فيديو تجارية؟", accepted: ["بونغ"] },
  { kind: "text", display: "من مؤسس شركة نينتندو الحديثة؟", accepted: ["هيروشي ياماوتشي"] },
  { kind: "text", display: "ما اسم أول متجر إلكتروني ضخم على الإنترنت؟", accepted: ["أمازون"] },
  { kind: "text", display: "من مؤسس شركة أوبر؟", accepted: ["ترافيس كالانيك"] },
  { kind: "text", display: "ما اسم بروتوكول نقل الملفات المستخدم في الإنترنت اختصاراً؟", accepted: ["FTP"] },
  { kind: "text", display: "من مؤسس شركة سناب شات؟", accepted: ["إيفان شبيغل"] },
  { kind: "text", display: "ما اسم أول حاسوب إلكتروني في العالم؟", accepted: ["إينياك"] },
  { kind: "text", display: "من مؤسس شركة ديل للحواسيب؟", accepted: ["مايكل ديل"] },
  { kind: "text", display: "ما اسم أكبر بحيرة في العالم من حيث المساحة؟", accepted: ["بحر قزوين"] },
  { kind: "text", display: "ما اسم أطول جسر معلق في العالم؟", accepted: ["جسر تشاناكالي"] },
  { kind: "text", display: "ما اسم أعلى برج في العالم؟", accepted: ["برج خليفة"] },
  { kind: "text", display: "في أي مدينة يقع برج خليفة؟", accepted: ["دبي"] },
  { kind: "text", display: "ما اسم أكبر مسجد في العالم؟", accepted: ["المسجد الحرام"] },
  { kind: "text", display: "ما اسم أكبر كنيسة في العالم؟", accepted: ["كاتدرائية القديس بطرس"] },
  { kind: "text", display: "ما اسم أطول نفق بحري في العالم؟", accepted: ["نفق سيكان"] },
  { kind: "text", display: "ما اسم أكبر ميناء في العالم؟", accepted: ["ميناء شنغهاي"] },
  { kind: "text", display: "ما اسم أصغر قارة مأهولة من حيث السكان؟", accepted: ["أستراليا"] },
  { kind: "text", display: "ما اسم أكبر شلال في العالم من حيث التدفق؟", accepted: ["شلالات فيكتوريا"] },
  { kind: "text", display: "ما اسم أطول سور دفاعي بناه الإنسان؟", accepted: ["سور الصين العظيم"] },
  { kind: "text", display: "ما اسم أكبر غابة استوائية في العالم؟", accepted: ["غابات الأمازون"] },
  { kind: "text", display: "ما اسم أطول نهر في قارة آسيا؟", accepted: ["نهر اليانغتسي"] },
  { kind: "text", display: "ما اسم أعلى شلال في العالم؟", accepted: ["شلال أنجل"] },
  { kind: "text", display: "ما اسم أكبر جزيرة عربية؟", accepted: ["جزيرة سقطرى"] },
  { kind: "text", display: "ما اسم أكبر واحة صحراوية في العالم؟", accepted: ["واحة الأحساء"] },
  { kind: "text", display: "ما اسم أكبر دولة من حيث عدد السكان؟", accepted: ["الهند"] },
  { kind: "text", display: "ما اسم أصغر دولة من حيث عدد السكان؟", accepted: ["الفاتيكان"] },
  { kind: "text", display: "ما هو اللون الناتج عن مزج الأزرق والأصفر؟", accepted: ["الأخضر"] },
  { kind: "text", display: "ما هو اللون الناتج عن مزج الأحمر والأزرق؟", accepted: ["البنفسجي"] },
  { kind: "text", display: "ما هو اللون الناتج عن مزج الأحمر والأصفر؟", accepted: ["البرتقالي"] },
  { kind: "text", display: "كم عدد الألوان الأساسية في الطيف الضوئي؟", accepted: ["3", "ثلاثة", "ثلاث"] },
  { kind: "text", display: "ما اسم أول لغة برمجة كائنية التوجه؟", accepted: ["سيمولا"] },
  { kind: "text", display: "ما اسم الفلز السائل في درجة حرارة الغرفة؟", accepted: ["الزئبق"] },
  { kind: "text", display: "ما هو الغاز المستخدم في البالونات الطائرة؟", accepted: ["الهيليوم"] },
  { kind: "text", display: "ما هي درجة انصهار الحديد تقريباً؟", accepted: ["1538 درجة مئوية"] },
  { kind: "text", display: "ما اسم أخف عنصر في الجدول الدوري؟", accepted: ["الهيدروجين"] },
  { kind: "text", display: "من مكتشف الجدول الدوري للعناصر؟", accepted: ["ديمتري مندليف", "مندليف"] },
  { kind: "text", display: "ما اسم أول قمر اصطناعي أطلقه الاتحاد السوفيتي؟", accepted: ["سبوتنيك"] },
  { kind: "text", display: "في أي عام أُطلق سبوتنيك؟", accepted: ["1957"] },
  { kind: "text", display: "من أول عربي يذهب إلى الفضاء؟", accepted: ["سلطان بن سلمان"] },
  { kind: "text", display: "ما اسم أول رائدة فضاء عربية؟", accepted: ["ريانة برناوي"] },
  { kind: "text", display: "من أول رجل يهبط على سطح القمر؟", accepted: ["نيل أرمسترونغ", "نيل ارمسترونغ"] },
  { kind: "text", display: "ما اسم المهمة التي هبطت على القمر أول مرة؟", accepted: ["أبولو 11"] },
  { kind: "text", display: "كم يبلغ عمر الأرض تقريباً؟", accepted: ["4.5 مليار سنة"] },
  { kind: "text", display: "ما اسم النظرية التي تفسر أصل الكون؟", accepted: ["الانفجار العظيم"] },
  { kind: "text", display: "ما اسم أول حيوان مستأنس عرفه الإنسان؟", accepted: ["الكلب"] },
  { kind: "text", display: "ما اسم أطول حيوان مائي في العالم؟", accepted: ["الحوت الأزرق"] },
  { kind: "text", display: "كم عدد أرجل الحصان؟", accepted: ["4", "أربعة", "اربعه"] },
  { kind: "text", display: "ما هو الحيوان الملقب بسفينة الصحراء؟", accepted: ["الجمل"] },
  { kind: "text", display: "ما اسم أسرع طائر في العالم أثناء الانقضاض؟", accepted: ["الصقر الشاهين"] },
  { kind: "text", display: "ما هو الحيوان الذي يغير لون جلده؟", accepted: ["الحرباء"] },
  { kind: "text", display: "كم عدد قلوب دودة الأرض؟", accepted: ["5", "خمسة", "خمسه"] },
  { kind: "text", display: "ما هو الطائر الذي لا يستطيع الطيران رغم امتلاكه أجنحة؟", accepted: ["النعامة"] },
  { kind: "text", display: "ما اسم الحيوان الذي ينام واقفاً؟", accepted: ["الحصان"] },
  { kind: "text", display: "كم عدد أعين العنكبوت عادة؟", accepted: ["8", "ثمانية", "ثمانيه"] },
  { kind: "text", display: "ما هو الحيوان الذي يحمل صغاره في جراب؟", accepted: ["الكنغر"] },
  { kind: "text", display: "ما اسم أكبر قط بري في العالم؟", accepted: ["النمر السيبيري"] },
  { kind: "text", display: "كم عدد سنوات دورة القمر حول الأرض بالأيام؟", accepted: ["27", "29.5"] },
  { kind: "text", display: "ما اسم الظاهرة التي يختفي فيها القمر خلف ظل الأرض؟", accepted: ["خسوف القمر"] },
  { kind: "text", display: "ما اسم الظاهرة التي تحجب فيها القمر الشمس؟", accepted: ["كسوف الشمس"] },
  { kind: "text", display: "كم يستغرق دوران الأرض حول الشمس؟", accepted: ["365 يوم", "سنة واحدة"] },
  { kind: "text", display: "كم يستغرق دوران الأرض حول نفسها؟", accepted: ["24 ساعة", "يوم واحد"] },
  { kind: "text", display: "ما اسم خط الطول الذي يحدد بداية التوقيت العالمي؟", accepted: ["خط غرينتش"] },
  { kind: "text", display: "ما اسم الخط الذي يقسم الأرض لنصفين شمالي وجنوبي؟", accepted: ["خط الاستواء"] },
  { kind: "text", display: "كم عدد خطوط العرض الرئيسية المعروفة؟", accepted: ["5", "خمسة", "خمسه"] },
  { kind: "text", display: "ما اسم أبرد مكان مسجل على سطح الأرض؟", accepted: ["فوستوك بالقارة القطبية"] },
  { kind: "text", display: "ما اسم أحر مكان مسجل على سطح الأرض؟", accepted: ["وادي الموت"] },
  { kind: "text", display: "ما اسم الرياح الموسمية التي تهب على جنوب آسيا؟", accepted: ["الرياح الموسمية"] },
  { kind: "text", display: "ما اسم أشهر مطبخ إيطالي شهير عالمياً؟", accepted: ["البيتزا", "المعكرونة"] },
  { kind: "text", display: "ما اسم الطبق الياباني المصنوع من الأرز والسمك النيء؟", accepted: ["السوشي"] },
  { kind: "text", display: "ما اسم الحلوى الفرنسية المصنوعة من طبقات رقيقة؟", accepted: ["الكرواسون"] },
  { kind: "text", display: "ما اسم المشروب التقليدي في المغرب العربي؟", accepted: ["الشاي بالنعناع"] },
  { kind: "text", display: "ما اسم الطبق السعودي التقليدي المصنوع من الأرز واللحم؟", accepted: ["الكبسة"] },
  { kind: "text", display: "ما اسم الطبق اللبناني المصنوع من الحمص المطحون؟", accepted: ["الحمص"] },
  { kind: "text", display: "ما اسم الحلوى المصرية المشهورة بشهر رمضان؟", accepted: ["الكنافة"] },
  { kind: "text", display: "ما اسم التوابل الحمراء المستخدمة في الطبخ الهندي؟", accepted: ["الفلفل الحار", "الكاري"] },
  { kind: "text", display: "ما اسم المشروب الغازي الأكثر مبيعاً في العالم؟", accepted: ["كوكا كولا"] },
  { kind: "text", display: "ما اسم الفطر المستخدم في صناعة الخبز؟", accepted: ["الخميرة"] },
  { kind: "text", display: "من مؤسس أول مطعم وجبات سريعة عالمي؟", accepted: ["ماكدونالدز"] },
  { kind: "text", display: "ما اسم الفاكهة الملقبة بملكة الفواكه؟", accepted: ["المانجوستين"] },
  { kind: "text", display: "ما اسم أول متجر تجزئة كبير في العالم؟", accepted: ["وول مارت"] },
  { kind: "text", display: "ما اسم الكوكب الذي يدور حوله أكبر عدد من الأقمار المعروفة؟", accepted: ["زحل"] },
  { kind: "text", display: "ما اسم أول شركة سيارات في العالم؟", accepted: ["بنز"] },
  { kind: "text", display: "من مخترع السيارة العملية الأولى؟", accepted: ["كارل بنز"] },
  { kind: "text", display: "من مخترع الطائرة؟", accepted: ["الأخوان رايت"] },
  { kind: "text", display: "في أي عام كانت أول رحلة طيران للأخوين رايت؟", accepted: ["1903"] },
  { kind: "text", display: "من مخترع المحرك البخاري؟", accepted: ["جيمس واط"] },
  { kind: "text", display: "من مخترع الراديو؟", accepted: ["غولييلمو ماركوني", "ماركوني"] },
  { kind: "text", display: "من مخترع التلفاز؟", accepted: ["جون لوغي بيرد"] },
  { kind: "text", display: "من مخترع الطباعة الحديثة؟", accepted: ["يوهان غوتنبرغ", "غوتنبرغ"] },
  { kind: "text", display: "من مخترع الدراجة الهوائية؟", accepted: ["كارل دريز"] },
  { kind: "text", display: "من مخترع آلة الخياطة؟", accepted: ["إلياس هاو"] },
  { kind: "text", display: "من مخترع البارود؟", accepted: ["الصينيون"] },
  { kind: "text", display: "من مخترع الساعة الميكانيكية؟", accepted: ["بيتر هينلاين"] },
  { kind: "text", display: "ما اسم أول صحيفة إخبارية مطبوعة؟", accepted: ["ريلاتيون"] },
  { kind: "text", display: "ما اسم أشهر شلال بين كندا وأمريكا؟", accepted: ["شلالات نياغرا"] },
  { kind: "text", display: "ما اسم أطول نفق بري في العالم؟", accepted: ["نفق غوتهارد"] },
  { kind: "text", display: "ما اسم أضخم بناء حجري قديم في العالم؟", accepted: ["الأهرامات"] },
  { kind: "text", display: "كم عدد أهرامات الجيزة الكبرى؟", accepted: ["3", "ثلاثة", "ثلاث"] },
  { kind: "text", display: "ما هي عاصمة تشاد؟", accepted: ["أنجمينا", "انجمينا"] },
  { kind: "text", display: "ما هي عاصمة مالي؟", accepted: ["باماكو"] },
  { kind: "text", display: "ما هي عاصمة النيجر؟", accepted: ["نيامي"] },
  { kind: "text", display: "ما هي عاصمة بوركينا فاسو؟", accepted: ["واغادوغو"] },
  { kind: "text", display: "ما هي عاصمة ساحل العاج؟", accepted: ["ياموسوكرو"] },
  { kind: "text", display: "ما هي عاصمة غينيا؟", accepted: ["كوناكري"] },
  { kind: "text", display: "ما هي عاصمة سيراليون؟", accepted: ["فريتاون"] },
  { kind: "text", display: "ما هي عاصمة ليبيريا؟", accepted: ["مونروفيا"] },
  { kind: "text", display: "ما هي عاصمة الجابون؟", accepted: ["ليبرفيل"] },
  { kind: "text", display: "ما هي عاصمة الكونغو؟", accepted: ["برازافيل"] },
  { kind: "text", display: "ما هي عاصمة أنغولا؟", accepted: ["لواندا"] },
  { kind: "text", display: "ما هي عاصمة زامبيا؟", accepted: ["لوساكا"] },
  { kind: "text", display: "ما هي عاصمة موزمبيق؟", accepted: ["مابوتو"] },
  { kind: "text", display: "ما هي عاصمة مدغشقر؟", accepted: ["أنتاناناريفو", "انتاناناريفو"] },
  { kind: "text", display: "ما هي عاصمة رواندا؟", accepted: ["كيغالي"] },
  { kind: "text", display: "ما هي عاصمة بوروندي؟", accepted: ["بوجومبورا"] },
  { kind: "text", display: "ما هي عاصمة ملاوي؟", accepted: ["ليلونغوي"] },
  { kind: "text", display: "ما هي عاصمة ناميبيا؟", accepted: ["ويندهوك"] },
  { kind: "text", display: "ما هي عاصمة بوتسوانا؟", accepted: ["غابورون"] },
  { kind: "text", display: "ما هي عاصمة ليسوتو؟", accepted: ["ماسيرو"] },
  { kind: "text", display: "ما اسم أول خط سكة حديد في العالم؟", accepted: ["خط ستوكتون دارلينغتون"] },
  { kind: "text", display: "من مخترع القطار البخاري؟", accepted: ["جورج ستيفنسون"] },
  { kind: "text", display: "ما اسم أول عاصمة للخلافة الأموية؟", accepted: ["دمشق"] },
  { kind: "text", display: "ما اسم أول عاصمة للخلافة العباسية؟", accepted: ["بغداد"] },
  { kind: "text", display: "ما اسم أول عاصمة للدولة الفاطمية بمصر؟", accepted: ["القاهرة"] },
  { kind: "text", display: "من هو مؤسس مدينة بغداد؟", accepted: ["أبو جعفر المنصور", "المنصور"] },
  { kind: "text", display: "من هو مؤسس مدينة القاهرة؟", accepted: ["جوهر الصقلي"] },
  { kind: "text", display: "ما اسم الحضارة التي بنت أهرامات الجيزة؟", accepted: ["الحضارة الفرعونية", "المصرية القديمة"] },
  { kind: "text", display: "ما اسم الحضارة التي عاشت بين نهري دجلة والفرات؟", accepted: ["بلاد ما بين النهرين", "الرافدين"] },
  { kind: "text", display: "ما اسم أقدم مجموعة قوانين مكتوبة في التاريخ؟", accepted: ["شريعة حمورابي"] },
  { kind: "text", display: "من هو الملك الذي وضع شريعة حمورابي؟", accepted: ["حمورابي"] },
  { kind: "text", display: "ما اسم الكتابة التي استخدمها المصريون القدماء؟", accepted: ["الهيروغليفية"] },
  { kind: "text", display: "ما اسم الحجر الذي ساعد على فك رموز الهيروغليفية؟", accepted: ["حجر رشيد"] },
  { kind: "text", display: "من فك رموز حجر رشيد؟", accepted: ["جان فرانسوا شامبليون", "شامبليون"] },
  { kind: "text", display: "ما اسم أول امبراطورية عرفها التاريخ؟", accepted: ["الإمبراطورية الأكدية"] },
  { kind: "text", display: "من هو مؤسس الإمبراطورية الفارسية؟", accepted: ["قورش الكبير"] },
  { kind: "text", display: "من هو القائد الذي وحد اليونان القديمة وغزا فارس؟", accepted: ["الإسكندر الأكبر"] },
  { kind: "text", display: "ما اسم المعركة التي هزم فيها الإسكندر الأكبر الفرس بشكل حاسم؟", accepted: ["معركة جاوجميلا"] },
  { kind: "text", display: "من هو أول إمبراطور روماني؟", accepted: ["أوغسطس"] },
  { kind: "text", display: "ما اسم الحضارة التي بنت مدينة البتراء؟", accepted: ["الأنباط", "النبطية"] },
  { kind: "text", display: "في أي دولة تقع مدينة البتراء؟", accepted: ["الأردن"] },
  { kind: "text", display: "ما اسم حضارة الإنكا القديمة وأين كانت؟", accepted: ["بيرو"] },
  { kind: "text", display: "ما اسم حضارة المايا وأين ازدهرت؟", accepted: ["أمريكا الوسطى"] },
  { kind: "text", display: "ما اسم الإمبراطورية التي حكمت الهند لفترة طويلة قبل الاستقلال؟", accepted: ["الإمبراطورية البريطانية"] },
  { kind: "text", display: "في أي عام استقلت الهند عن بريطانيا؟", accepted: ["1947"] },
  { kind: "text", display: "من هو زعيم استقلال الهند بالمقاومة السلمية؟", accepted: ["المهاتما غاندي", "غاندي"] },
  { kind: "text", display: "من هو أول رئيس وزراء للهند بعد الاستقلال؟", accepted: ["جواهر لال نهرو"] },
  { kind: "text", display: "من هو مؤسس الصين الشعبية؟", accepted: ["ماو تسي تونغ"] },
  { kind: "text", display: "في أي عام تأسست جمهورية الصين الشعبية؟", accepted: ["1949"] },
  { kind: "text", display: "ما اسم أول امرأة تفوز بجائزة نوبل؟", accepted: ["ماري كوري"] },
  { kind: "text", display: "كم مرة فازت ماري كوري بجائزة نوبل؟", accepted: ["مرتين", "2"] },
  { kind: "text", display: "ما اسم أول عربي يفوز بجائزة نوبل؟", accepted: ["نجيب محفوظ"] },
  { kind: "text", display: "في أي مجال فاز نجيب محفوظ بجائزة نوبل؟", accepted: ["الأدب"] },
  { kind: "text", display: "ما اسم أصغر شخص فاز بجائزة نوبل للسلام؟", accepted: ["ملالا يوسفزاي"] },
  { kind: "text", display: "ما اسم أول امرأة عربية تفوز بجائزة نوبل؟", accepted: ["توكل كرمان"] },
  { kind: "text", display: "كم عدد فئات جائزة نوبل؟", accepted: ["6", "ستة", "سته"] },
  { kind: "text", display: "في أي مدينة تُمنح جائزة نوبل للسلام؟", accepted: ["أوسلو"] },
  { kind: "text", display: "في أي مدينة تُمنح باقي جوائز نوبل؟", accepted: ["ستوكهولم"] },
  { kind: "text", display: "ما اسم مخترع الديناميت الذي أسس جائزة نوبل؟", accepted: ["ألفريد نوبل"] },
  { kind: "text", display: "كم عدد اللاعبين في فريق الشطرنج الجماعي (أوليمبياد الشطرنج)؟", accepted: ["4", "أربعة", "اربعه"] },
  { kind: "text", display: "كم عدد المربعات في رقعة الشطرنج؟", accepted: ["64"] },
  { kind: "text", display: "كم عدد قطع الشطرنج لكل لاعب في بداية اللعبة؟", accepted: ["16", "ستة عشر"] },
  { kind: "text", display: "ما اسم أقوى قطعة في لعبة الشطرنج؟", accepted: ["الوزير", "الملكة"] },
  { kind: "text", display: "كم عدد الجنود في رقعة الشطرنج لكل لاعب؟", accepted: ["8", "ثمانية", "ثمانيه"] },
  { kind: "text", display: "ما اسم الحركة الخاصة التي يقوم بها الملك والقلعة معاً؟", accepted: ["التبييت", "الرركة"] },
  { kind: "text", display: "كم عدد الأحجار في لعبة الدومينو الكاملة؟", accepted: ["28"] },
  { kind: "text", display: "كم عدد أوراق لعبة الكوتشينة الكاملة؟", accepted: ["52"] },
  { kind: "text", display: "كم عدد ألوان أوراق الكوتشينة؟", accepted: ["4", "أربعة", "اربعه"] },
  { kind: "text", display: "ما اسم أعلى ورقة في لعبة الكوتشينة عادة؟", accepted: ["الأس"] },
  { kind: "text", display: "كم وجه للنرد التقليدي؟", accepted: ["6", "ستة", "سته"] },
  { kind: "text", display: "ما اسم اللعبة الأولمبية التي تجمع الرماية والسباحة والجري وركوب الخيل والمبارزة؟", accepted: ["الخماسي الحديث"] },
  { kind: "text", display: "أين أقيمت أول دورة ألعاب أولمبية حديثة؟", accepted: ["أثينا"] },
  { kind: "text", display: "في أي عام أقيمت أول دورة أولمبية حديثة؟", accepted: ["1896"] },
  { kind: "text", display: "كل كم سنة تقام الألعاب الأولمبية الصيفية؟", accepted: ["4", "أربع سنوات"] },
  { kind: "text", display: "من هو أكثر رياضي حصولاً على ميداليات أولمبية في التاريخ؟", accepted: ["مايكل فيلبس"] },
  { kind: "text", display: "ما هي الرياضة التي برع فيها مايكل فيلبس؟", accepted: ["السباحة"] },
  { kind: "text", display: "من هو الملقب بأسطورة الملاكمة \"الفراشة\"؟", accepted: ["محمد علي كلاي"] },
  { kind: "text", display: "من هو أسرع رجل في العالم بالعدو 100 متر (رقم قياسي)؟", accepted: ["يوسين بولت"] },
  { kind: "text", display: "من أي دولة الرياضي يوسين بولت؟", accepted: ["جامايكا"] },
  { kind: "text", display: "ما هو الرقم القياسي العالمي لسباق 100 متر تقريباً؟", accepted: ["9.58 ثانية"] },
  { kind: "text", display: "من هو أفضل هداف تاريخي لكرة القدم الدولية (منتخبات)؟", accepted: ["كريستيانو رونالدو"] },
  { kind: "text", display: "من الفريق الحاصل على أكبر عدد من كؤوس العالم لكرة القدم؟", accepted: ["البرازيل"] },
  { kind: "text", display: "كم مرة فازت البرازيل بكأس العالم؟", accepted: ["5", "خمس مرات"] },
  { kind: "text", display: "من مدرب منتخب الأرجنتين الفائز بكأس العالم 2022؟", accepted: ["ليونيل سكالوني"] },
  { kind: "text", display: "من هو النجم الأرجنتيني الذي قاد بلاده للفوز بكأس العالم 2022؟", accepted: ["ليونيل ميسي"] },
  { kind: "text", display: "ما اسم أول بطولة كأس عالم أقيمت؟", accepted: ["كأس العالم 1930"] },
  { kind: "text", display: "أين أقيمت أول بطولة كأس عالم؟", accepted: ["الأوروغواي"] },
  { kind: "text", display: "ما اسم النادي الملقب بالنادي الملكي في إسبانيا؟", accepted: ["ريال مدريد"] },
  { kind: "text", display: "ما اسم النادي الملقب بالبلوغرانا؟", accepted: ["برشلونة"] },
  { kind: "text", display: "من هو هداف تاريخ دوري أبطال أوروبا؟", accepted: ["كريستيانو رونالدو"] },
  { kind: "text", display: "ما اسم كأس آسيا لكرة القدم آخر نسخة فازت بها قطر (سنة)؟", accepted: ["2023"] },
  { kind: "text", display: "من هو أول رئيس لجمهورية العراق؟", accepted: ["عبد الكريم قاسم", "محمد نجيب الربيعي"] },
  { kind: "text", display: "من هو أول رئيس لجمهورية سوريا؟", accepted: ["شكري القوتلي"] },
  { kind: "text", display: "من هو أول رئيس لجمهورية لبنان؟", accepted: ["شارل دباس"] },
  { kind: "text", display: "من هو أول رئيس لجمهورية تونس؟", accepted: ["الحبيب بورقيبة"] },
  { kind: "text", display: "من هو مؤسس دولة باكستان؟", accepted: ["محمد علي جناح"] },
  { kind: "text", display: "من هو مؤسس دولة إسرائيل المعلن؟", accepted: ["ديفيد بن غوريون"] },
  { kind: "text", display: "في أي عام أعلن قيام دولة إسرائيل؟", accepted: ["1948"] },
  { kind: "text", display: "ما اسم الحرب العربية الإسرائيلية الأولى؟", accepted: ["حرب 1948", "النكبة"] },
  { kind: "text", display: "ما اسم حرب أكتوبر بين مصر وإسرائيل؟", accepted: ["حرب أكتوبر", "حرب 1973", "حرب رمضان"] },
  { kind: "text", display: "من هو الرئيس المصري الذي وقع اتفاقية كامب ديفيد؟", accepted: ["أنور السادات"] },
  { kind: "text", display: "من هو الرئيس المصري الراحل جمال؟", accepted: ["جمال عبد الناصر"] },
  { kind: "text", display: "ما اسم المشروع الذي بناه جمال عبد الناصر على النيل؟", accepted: ["السد العالي"] },
  { kind: "text", display: "في أي عام تم تأميم قناة السويس؟", accepted: ["1956"] },
  { kind: "text", display: "من هو حافر قناة السويس (المهندس الفرنسي)؟", accepted: ["فرديناند ديليسبس"] },
  { kind: "text", display: "في أي عام افتتحت قناة السويس؟", accepted: ["1869"] },
  { kind: "text", display: "ما اسم القناة التي تربط المحيط الأطلسي بالهادئ؟", accepted: ["قناة بنما"] },
  { kind: "text", display: "في أي عام افتتحت قناة بنما؟", accepted: ["1914"] },
  { kind: "text", display: "من رسام لوحة \"العشاء الأخير\"؟", accepted: ["ليوناردو دافينشي", "دافينشي"] },
  { kind: "text", display: "من نحت تمثال داود الشهير؟", accepted: ["مايكل أنجلو"] },
  { kind: "text", display: "من رسم سقف كنيسة سيستين؟", accepted: ["مايكل أنجلو"] },
  { kind: "text", display: "من هو مؤلف \"الكوميديا الإلهية\"؟", accepted: ["دانتي أليغييري", "دانتي"] },
  { kind: "text", display: "من هو مؤلف رواية \"دون كيخوته\"؟", accepted: ["ميغيل دي سرفانتس", "سرفانتس"] },
  { kind: "text", display: "من هو الشاعر العباسي الملقب بأشعر شعراء العرب؟", accepted: ["المتنبي"] },
  { kind: "text", display: "من هو أشهر شعراء العصر العباسي الملقب بشاعر الحكمة؟", accepted: ["المتنبي"] },
  { kind: "text", display: "من هو مؤلف معلقة \"لامية العرب\"؟", accepted: ["الشنفرى"] },
  { kind: "text", display: "من هو الشاعر الملقب \"أمير الشعراء\"؟", accepted: ["أحمد شوقي"] },
  { kind: "text", display: "من هو الشاعر الملقب \"شاعر النيل\"؟", accepted: ["حافظ إبراهيم"] },
  { kind: "text", display: "من مؤلف رواية \"مدن الملح\"؟", accepted: ["عبد الرحمن منيف"] },
  { kind: "text", display: "من مؤلف ثلاثية \"بين القصرين\"؟", accepted: ["نجيب محفوظ"] },
  { kind: "text", display: "من هو الأديب الملقب \"عميد الأدب العربي\"؟", accepted: ["طه حسين"] },
  { kind: "text", display: "ما اسم أول رواية عربية حديثة معروفة؟", accepted: ["زينب"] },
  { kind: "text", display: "من مؤلف رواية \"زينب\"؟", accepted: ["محمد حسين هيكل"] },
  { kind: "text", display: "ما اسم أشهر معلقة لعنترة بن شداد؟", accepted: ["معلقة عنترة"] },
  { kind: "text", display: "من هو الشاعر الجاهلي الملقب بالملك الضليل؟", accepted: ["امرؤ القيس"] },
  { kind: "text", display: "كم عدد المعلقات السبع المشهورة؟", accepted: ["7", "سبع", "سبعة"] },
  { kind: "text", display: "ما هي وحدة قياس سرعة الرياح؟", accepted: ["العقدة", "كيلومتر بالساعة"] },
  { kind: "text", display: "ما اسم الجهاز المستخدم لقياس سرعة الرياح؟", accepted: ["أنيمومتر"] },
  { kind: "text", display: "ما اسم الجهاز المستخدم لقياس الزلازل؟", accepted: ["السيزموغراف"] },
  { kind: "text", display: "ما هو مقياس شدة الزلازل الأكثر شيوعاً؟", accepted: ["مقياس ريختر"] },
  { kind: "text", display: "ما اسم الظاهرة الجيولوجية الناتجة عن حركة الصفائح التكتونية؟", accepted: ["الزلازل"] },
  { kind: "text", display: "ما اسم الموجات البحرية العملاقة الناتجة عن الزلازل تحت الماء؟", accepted: ["تسونامي"] },
  { kind: "text", display: "ما اسم الدائرة النارية المحيطة بالمحيط الهادئ والمعروفة بالزلازل والبراكين؟", accepted: ["حلقة النار"] },
  { kind: "text", display: "ما اسم أعلى جبل بركاني نشط في أفريقيا؟", accepted: ["كليمنجارو"] },
  { kind: "text", display: "في أي دولة يقع جبل كليمنجارو؟", accepted: ["تنزانيا"] },
  { kind: "text", display: "ما اسم أعلى جبل في أوروبا؟", accepted: ["إلبروس"] },
  { kind: "text", display: "ما اسم أعلى جبل في أمريكا الشمالية؟", accepted: ["دينالي"] },
  { kind: "text", display: "ما اسم أعلى جبل في أمريكا الجنوبية؟", accepted: ["أكونكاغوا"] },
  { kind: "text", display: "ما اسم أعلى جبل في الوطن العربي؟", accepted: ["جبل توبقال"] },
  { kind: "text", display: "في أي دولة عربية يقع جبل توبقال؟", accepted: ["المغرب"] },
  { kind: "text", display: "ما اسم أطول سلسلة جبال في آسيا؟", accepted: ["جبال الهيمالايا"] },
  { kind: "text", display: "كم عدد قمم جبال الهيمالايا التي تتجاوز 8000 متر؟", accepted: ["14"] },
  { kind: "text", display: "ما اسم ثاني أعلى قمة جبلية بالعالم بعد إفرست؟", accepted: ["كي 2"] },
  { kind: "text", display: "ما اسم البحر الذي يعتبر أكثر بحار العالم ملوحة؟", accepted: ["البحر الميت"] },
  { kind: "text", display: "أين يقع البحر الميت؟", accepted: ["الأردن وفلسطين"] },
  { kind: "text", display: "ما هو أخفض نقطة على سطح اليابسة في العالم؟", accepted: ["البحر الميت"] },
  { kind: "text", display: "ما اسم البحر الذي يفصل بين أوروبا وأفريقيا؟", accepted: ["البحر الأبيض المتوسط"] },
  { kind: "text", display: "ما اسم المضيق الذي يفصل بين آسيا وأوروبا؟", accepted: ["مضيق البوسفور"] },
  { kind: "text", display: "ما اسم المضيق الذي يربط الخليج العربي بالمحيط الهندي؟", accepted: ["مضيق هرمز"] },
  { kind: "text", display: "ما اسم المضيق الذي يفصل بين اليمن وجيبوتي؟", accepted: ["باب المندب"] },
  { kind: "text", display: "ما اسم البحر الذي يقع بين السعودية ومصر؟", accepted: ["البحر الأحمر"] },
  { kind: "text", display: "ما اسم أكبر خليج في العالم؟", accepted: ["خليج المكسيك"] },
  { kind: "text", display: "ما اسم الخليج الذي تطل عليه دول الكويت والسعودية والإمارات؟", accepted: ["الخليج العربي"] },
  { kind: "text", display: "ما اسم أول قمر صناعي عربي للاتصالات؟", accepted: ["عربسات"] },
  { kind: "text", display: "في أي دولة أُسست منظمة عربسات؟", accepted: ["السعودية"] },
  { kind: "text", display: "ما اسم أول جامعة عربية حديثة؟", accepted: ["جامعة القاهرة"] },
  { kind: "text", display: "ما اسم أقدم جامعة في العالم لا تزال تعمل؟", accepted: ["جامعة القرويين"] },
  { kind: "text", display: "في أي دولة تقع جامعة القرويين؟", accepted: ["المغرب"] },
  { kind: "text", display: "ما اسم أول مكتبة عامة في التاريخ الإسلامي؟", accepted: ["بيت الحكمة"] },
  { kind: "text", display: "في أي مدينة أُنشئ بيت الحكمة؟", accepted: ["بغداد"] },
  { kind: "text", display: "من هو العالم المسلم الملقب بأبي الجبر؟", accepted: ["الخوارزمي"] },
  { kind: "text", display: "من هو العالم المسلم الذي اشتهر بالطب ووضع \"القانون في الطب\"؟", accepted: ["ابن سينا"] },
  { kind: "text", display: "من هو العالم المسلم الذي اكتشف الدورة الدموية الرئوية؟", accepted: ["ابن النفيس"] },
  { kind: "text", display: "من هو عالم مسلم اشتهر بعلم البصريات؟", accepted: ["ابن الهيثم"] },
  { kind: "text", display: "من هو الرحالة المسلم الشهير الذي طاف العالم الإسلامي؟", accepted: ["ابن بطوطة"] },
  { kind: "text", display: "من هو المؤرخ المسلم صاحب كتاب \"المقدمة\" وعلم الاجتماع؟", accepted: ["ابن خلدون"] },
  { kind: "text", display: "من هو الفيلسوف المسلم الملقب بالشارح الأكبر لأرسطو؟", accepted: ["ابن رشد"] },
  { kind: "text", display: "من هو عالم الكيمياء المسلم الملقب بأبي الكيمياء؟", accepted: ["جابر بن حيان"] },
  { kind: "text", display: "من هو عالم الفلك المسلم الذي حسب محيط الأرض بدقة؟", accepted: ["البيروني"] },
  { kind: "text", display: "ما اسم الآلة الموسيقية العربية ذات الأوتار الشهيرة؟", accepted: ["العود"] },
  { kind: "text", display: "ما اسم الآلة الإيقاعية العربية المصنوعة من الجلد؟", accepted: ["الطبلة"] },
  { kind: "text", display: "ما اسم الرقصة الشعبية الخليجية بالعصي؟", accepted: ["العرضة"] },
  { kind: "text", display: "ما اسم الرقصة الشعبية المصرية بالعصا؟", accepted: ["رقصة التحطيب"] },
  { kind: "text", display: "ما اسم فن الرقص الإسباني التقليدي؟", accepted: ["الفلامنكو"] },
  { kind: "text", display: "ما اسم الرقصة الأرجنتينية الشهيرة عالمياً؟", accepted: ["التانغو"] },
  { kind: "text", display: "ما اسم الرقص الشعبي الحديث الذي انتشر من كوريا؟", accepted: ["الكيبوب"] },
  { kind: "text", display: "ما اسم أول فيلم رسوم متحركة كامل بالألوان؟", accepted: ["بياض الثلج والأقزام السبعة"] },
  { kind: "text", display: "ما اسم استوديو الرسوم المتحركة الأشهر عالمياً المملوك لديزني؟", accepted: ["بيكسار"] },
  { kind: "text", display: "ما اسم أول فيلم من إنتاج بيكسار؟", accepted: ["حياة حشرة؟ لا، توي ستوري"] },
  { kind: "text", display: "من مخرج فيلم \"الأسد الملك\" الأصلي؟", accepted: ["روجر أليرز وروب مينكوف"] },
  { kind: "text", display: "ما اسم شركة الرسوم المتحركة اليابانية الشهيرة \"استوديو غيبلي\" ومؤسسها؟", accepted: ["هاياو ميازاكي"] },
  { kind: "text", display: "من مؤسس شركة مارفل للقصص المصورة؟", accepted: ["ستان لي"] },
  { kind: "text", display: "ما اسم الشخصية الخارقة الأشهر لشركة DC التي ترتدي رداءً وتطير؟", accepted: ["سوبرمان"] },
  { kind: "text", display: "ما اسم بطل الرسوم المصورة الملقب بالرجل الوطواط؟", accepted: ["باتمان"] },
  { kind: "text", display: "من هو مبتكر شخصية ميكي ماوس؟", accepted: ["والت ديزني"] },
  { kind: "text", display: "ما اسم أول متنزه ديزني في العالم؟", accepted: ["ديزني لاند كاليفورنيا"] },
  { kind: "text", display: "في أي عام افتتح أول متنزه ديزني؟", accepted: ["1955"] },
  { kind: "text", display: "ما اسم أول عملة رقمية مشفرة في العالم؟", accepted: ["بيتكوين"] },
  { kind: "text", display: "من هو المؤسس المجهول لعملة البيتكوين؟", accepted: ["ساتوشي ناكاموتو"] },
  { kind: "text", display: "ما اسم التقنية التي تعتمد عليها العملات الرقمية؟", accepted: ["البلوك تشين"] },
  { kind: "text", display: "ما اسم أول متصفح إنترنت في العالم؟", accepted: ["وورلد وايد ويب"] },
  { kind: "text", display: "من مخترع الفأرة الحاسوبية؟", accepted: ["دوغلاس إنجلبارت"] },
  { kind: "text", display: "من مؤسس شركة IBM؟", accepted: ["توماس واتسون"] },
  { kind: "text", display: "ما اسم أول لعبة إلكترونية محمولة شهيرة؟", accepted: ["غيم بوي"] },
  { kind: "text", display: "من هي الشركة المصنعة لجهاز بلايستيشن؟", accepted: ["سوني"] },
  { kind: "text", display: "من هي الشركة المصنعة لجهاز إكس بوكس؟", accepted: ["مايكروسوفت"] },
  { kind: "text", display: "ما اسم أشهر لعبة فيديو تحتوي على شخصية سباك إيطالي؟", accepted: ["ماريو"] },
  { kind: "text", display: "ما اسم الشركة المطورة للعبة ماينكرافت؟", accepted: ["موجانغ"] },
  { kind: "text", display: "ما اسم أول دولة عربية انضمت للأمم المتحدة؟", accepted: ["مصر", "السعودية", "العراق"] },
  { kind: "text", display: "كم عدد الدول الأعضاء في جامعة الدول العربية؟", accepted: ["22"] },
  { kind: "text", display: "في أي عام تأسست جامعة الدول العربية؟", accepted: ["1945"] },
  { kind: "text", display: "أين يقع المقر الرئيسي لجامعة الدول العربية؟", accepted: ["القاهرة"] },
  { kind: "text", display: "ما اسم أول أمين عام لجامعة الدول العربية؟", accepted: ["عبد الرحمن عزام"] },
  { kind: "text", display: "كم عدد دول مجلس التعاون الخليجي؟", accepted: ["6", "ستة", "سته"] },
  { kind: "text", display: "في أي عام تأسس مجلس التعاون الخليجي؟", accepted: ["1981"] },
  { kind: "text", display: "أين يقع المقر الرئيسي لمجلس التعاون الخليجي؟", accepted: ["الرياض"] },
  { kind: "text", display: "ما اسم العملة الموحدة المقترحة لدول الخليج؟", accepted: ["الخليجي"] },
  { kind: "text", display: "كم عدد الدول الأعضاء في منظمة الأمم المتحدة تقريباً؟", accepted: ["193"] },
  { kind: "text", display: "أين يقع المقر الرئيسي للأمم المتحدة؟", accepted: ["نيويورك"] },
  { kind: "text", display: "من هو أول أمين عام للأمم المتحدة؟", accepted: ["تريغفي لي"] },
  { kind: "text", display: "كم عدد الدول دائمة العضوية في مجلس الأمن؟", accepted: ["5", "خمسة", "خمسه"] },
  { kind: "text", display: "ما اسم المنظمة العالمية المسؤولة عن الصحة؟", accepted: ["منظمة الصحة العالمية"] },
  { kind: "text", display: "ما اسم المنظمة العالمية المسؤولة عن التعليم والثقافة؟", accepted: ["اليونسكو"] },
  { kind: "text", display: "ما اسم صندوق الأمم المتحدة لرعاية الطفولة؟", accepted: ["اليونيسف"] },
  { kind: "text", display: "ما اسم المنظمة العالمية للتجارة اختصاراً؟", accepted: ["WTO"] },
  { kind: "text", display: "ما اسم منظمة الدول المصدرة للنفط اختصاراً؟", accepted: ["أوبك"] },
  { kind: "text", display: "أين يقع المقر الرئيسي لمنظمة أوبك؟", accepted: ["فيينا"] },
  { kind: "text", display: "كم عدد الدول المؤسسة لمنظمة أوبك؟", accepted: ["5", "خمسة", "خمسه"] },
  { kind: "text", display: "ما اسم أكبر حقل نفطي في العالم؟", accepted: ["حقل الغوار"] },
  { kind: "text", display: "في أي دولة يقع حقل الغوار النفطي؟", accepted: ["السعودية"] },
  { kind: "text", display: "ما هو المعدن الذي يستخرج منه الألمنيوم؟", accepted: ["البوكسيت"] },
  { kind: "text", display: "ما هو العنصر الكيميائي الذي رمزه Au؟", accepted: ["الذهب"] },
  { kind: "text", display: "ما هو العنصر الكيميائي الذي رمزه Ag؟", accepted: ["الفضة"] },
  { kind: "text", display: "ما هو العنصر الكيميائي الذي رمزه O؟", accepted: ["الأكسجين"] },
  { kind: "text", display: "ما هو العنصر الكيميائي الذي رمزه H؟", accepted: ["الهيدروجين"] },
  { kind: "text", display: "ما هو العنصر الكيميائي الذي رمزه C؟", accepted: ["الكربون"] },
  { kind: "text", display: "ما هو العنصر الكيميائي الذي رمزه Na؟", accepted: ["الصوديوم"] },
  { kind: "text", display: "ما هو العنصر الكيميائي الذي رمزه K؟", accepted: ["البوتاسيوم"] },
  { kind: "text", display: "ما هو العنصر الكيميائي الذي رمزه Cu؟", accepted: ["النحاس"] },
  { kind: "text", display: "ما هو العنصر الكيميائي الذي رمزه Pb؟", accepted: ["الرصاص"] },
  { kind: "text", display: "ما هو العنصر الكيميائي الذي رمزه Zn؟", accepted: ["الزنك"] },
  { kind: "text", display: "كم عدد العناصر المعروفة في الجدول الدوري تقريباً؟", accepted: ["118"] },
  { kind: "text", display: "من صاحب نظرية الجاذبية \"التفاحة\"؟", accepted: ["إسحاق نيوتن", "اسحاق نيوتن"] },
  { kind: "text", display: "ما هي معادلة النسبية الأشهر لأينشتاين؟", accepted: ["E=mc2", "الطاقة تساوي الكتلة في مربع سرعة الضوء"] },
  { kind: "text", display: "ما اسم الجسيم دون الذري الذي يحمل شحنة سالبة؟", accepted: ["الإلكترون"] },
  { kind: "text", display: "ما اسم الجسيم الذي يحمل شحنة موجبة داخل النواة؟", accepted: ["البروتون"] },
  { kind: "text", display: "ما اسم الجسيم المتعادل الشحنة داخل النواة؟", accepted: ["النيوترون"] },
  { kind: "text", display: "ما اسم أصغر وحدة بناء للمادة؟", accepted: ["الذرة"] },
  { kind: "text", display: "من هو مكتشف النيوترون؟", accepted: ["جيمس تشادويك"] },
  { kind: "text", display: "من هو مكتشف الإلكترون؟", accepted: ["جوزيف جون طومسون"] },
  { kind: "text", display: "ما اسم نظرية داروين حول أصل الأنواع؟", accepted: ["نظرية التطور"] },
  { kind: "text", display: "ما اسم العملية التي تصنع بها النباتات غذاءها؟", accepted: ["التمثيل الضوئي"] },
  { kind: "text", display: "ما اسم العملية التي يتنفس بها الإنسان الأكسجين؟", accepted: ["التنفس"] },
  { kind: "text", display: "ما اسم المادة الوراثية الموجودة في خلايا الكائنات الحية؟", accepted: ["الحمض النووي", "DNA"] },
  { kind: "text", display: "من هما مكتشفا التركيب الحلزوني المزدوج للحمض النووي؟", accepted: ["واتسون وكريك"] },
  { kind: "text", display: "ما اسم عملية انقسام الخلية لإنتاج خليتين متطابقتين؟", accepted: ["الانقسام المتساوي"] },
  { kind: "text", display: "ما اسم أول نوع من المضادات الحيوية اكتشف؟", accepted: ["البنسلين"] },
  { kind: "text", display: "من مخترع أول لقاح في التاريخ؟", accepted: ["إدوارد جينر"] },
  { kind: "text", display: "ضد أي مرض كان أول لقاح؟", accepted: ["الجدري"] },
  { kind: "text", display: "ما اسم المرض الذي تم استئصاله عالمياً بفضل اللقاحات؟", accepted: ["الجدري"] },
  { kind: "text", display: "من هو مكتشف فصائل الدم؟", accepted: ["كارل لاندشتاينر"] },
  { kind: "text", display: "كم عدد فصائل الدم الرئيسية؟", accepted: ["4", "أربعة", "اربعه"] },
  { kind: "text", display: "ما اسم فصيلة الدم التي تعتبر \"المتبرع الشامل\"؟", accepted: ["O سالب"] },
  { kind: "text", display: "ما اسم فصيلة الدم التي تعتبر \"المستقبل الشامل\"؟", accepted: ["AB موجب"] },
  { kind: "text", display: "ما هي درجة حرارة جسم الإنسان الطبيعية تقريباً؟", accepted: ["37 درجة مئوية"] },
  { kind: "text", display: "كم مرة ينبض قلب الإنسان في الدقيقة تقريباً وقت الراحة؟", accepted: ["60 إلى 100 نبضة"] },
  { kind: "text", display: "كم عدد ساعات النوم الموصى بها للبالغين يومياً؟", accepted: ["7 إلى 9 ساعات"] },
  { kind: "text", display: "ما اسم الغدة الموجودة في الدماغ وتنظم النوم؟", accepted: ["الغدة الصنوبرية"] },
  { kind: "text", display: "ما اسم الهرمون المسؤول عن الشعور بالسعادة؟", accepted: ["السيروتونين"] },
  { kind: "text", display: "ما اسم الجزء من الدماغ المسؤول عن التوازن؟", accepted: ["المخيخ"] },
  { kind: "text", display: "كم عدد فصوص المخ البشري؟", accepted: ["4", "أربعة", "اربعه"] },
  { kind: "text", display: "ما اسم الخلايا العصبية في الجسم؟", accepted: ["العصبونات"] },
  { kind: "text", display: "ما اسم أول عملية زراعة قلب ناجحة؟", accepted: ["أجراها كريستيان برنارد"] },
  { kind: "text", display: "من هو الجراح الذي أجرى أول عملية زراعة قلب؟", accepted: ["كريستيان برنارد"] },
  { kind: "text", display: "ما اسم أول طفل أنبوب في العالم؟", accepted: ["لويز براون"] },
  { kind: "text", display: "في أي عام ولد أول طفل أنبوب؟", accepted: ["1978"] },
  { kind: "text", display: "ما اسم اللقاح الذي طور بسرعة قياسية لفيروس كورونا؟", accepted: ["لقاحات متعددة مثل فايزر وموديرنا"] },
  { kind: "text", display: "ما اسم الفيروس المسبب لجائحة كوفيد 19؟", accepted: ["كورونا", "سارس كوف 2"] },
  { kind: "text", display: "في أي عام أعلنت منظمة الصحة العالمية جائحة كوفيد 19؟", accepted: ["2020"] },
  { kind: "text", display: "ما اسم أول دولة أعلنت ظهور فيروس كورونا؟", accepted: ["الصين"] },
  { kind: "text", display: "ما اسم أول لقاح موافق عليه لفيروس كورونا؟", accepted: ["فايزر بيونتك"] },
  { kind: "text", display: "ما هو الاسم العلمي للإنسان الحديث؟", accepted: ["هومو سابيينس"] },
  { kind: "text", display: "ما اسم أقدم نوع بشري معروف تقريباً؟", accepted: ["هومو هابيليس"] },
  { kind: "text", display: "أين اكتُشفت أقدم بقايا بشرية معروفة تقريباً؟", accepted: ["أفريقيا"] },
  { kind: "text", display: "ما اسم العصر الذي انقرضت فيه الديناصورات؟", accepted: ["العصر الطباشيري"] },
  { kind: "text", display: "ما هو السبب الرئيسي المرجح لانقراض الديناصورات؟", accepted: ["اصطدام نيزك"] },
  { kind: "text", display: "ما اسم أكبر ديناصور آكل للحوم معروف؟", accepted: ["التيرانوصور ركس"] },
  { kind: "text", display: "ما اسم أكبر ديناصور آكل للأعشاب معروف تقريباً؟", accepted: ["الأرجنتينوصور"] },
  { kind: "text", display: "ما اسم العلم الذي يدرس الديناصورات والحفريات؟", accepted: ["علم الحفريات"] },
  { kind: "text", display: "ما اسم أقدم حيوان بحري ما زال حياً منذ ملايين السنين تقريباً؟", accepted: ["سرطان حدوة الحصان"] },
  { kind: "text", display: "ما اسم أطول كائن حي معروف في المحيطات (ليس حوتاً)؟", accepted: ["قنديل البحر السوطي"] },
  { kind: "text", display: "ما اسم أكبر سمكة في العالم؟", accepted: ["قرش الحوت"] },
  { kind: "text", display: "هل قرش الحوت خطير على الإنسان عادة؟", accepted: ["لا، يتغذى على العوالق"] },
  { kind: "text", display: "ما اسم أذكى الحيوانات البحرية المعروفة؟", accepted: ["الدلفين"] },
  { kind: "text", display: "ما اسم أكبر قرد في العالم؟", accepted: ["الغوريلا"] },
  { kind: "text", display: "ما هو أقرب حيوان وراثياً للإنسان؟", accepted: ["الشمبانزي"] },
  { kind: "text", display: "ما نسبة تطابق الحمض النووي بين الإنسان والشمبانزي تقريباً؟", accepted: ["98%", "حوالي 98 بالمئة"] },
  { kind: "text", display: "ما اسم أطول عمر مسجل لحيوان بري (السلحفاة)؟", accepted: ["أكثر من 100 سنة"] },
  { kind: "text", display: "ما اسم الحيوان الملقب بملك الغابة؟", accepted: ["الأسد"] },
  { kind: "text", display: "ما هي المنطقة التي تعيش فيها معظم الأسود البرية اليوم؟", accepted: ["أفريقيا"] },
  { kind: "text", display: "ما اسم صوت الأسد؟", accepted: ["الزئير"] },
  { kind: "text", display: "ما اسم صوت الحصان؟", accepted: ["الصهيل"] },
  { kind: "text", display: "ما اسم صوت الذئب؟", accepted: ["العواء"] },
  { kind: "text", display: "ما اسم صوت الثعبان؟", accepted: ["الفحيح"] },
  { kind: "text", display: "ما اسم صوت الجمل؟", accepted: ["الرغاء"] },
  { kind: "text", display: "ما اسم صوت الحمار؟", accepted: ["النهيق"] },
  { kind: "text", display: "ما اسم صوت البقرة؟", accepted: ["الخوار"] },
  { kind: "text", display: "ما اسم صوت الخروف؟", accepted: ["الثغاء"] },
  { kind: "text", display: "ما اسم صوت الديك؟", accepted: ["الصياح"] },
  { kind: "text", display: "ما اسم صوت الكلب؟", accepted: ["النباح"] },
  { kind: "text", display: "ما اسم صوت القط؟", accepted: ["المواء"] },
  { kind: "text", display: "ما اسم أنثى الأسد؟", accepted: ["اللبؤة"] },
  { kind: "text", display: "ما اسم صغير الكلب؟", accepted: ["الجرو"] },
  { kind: "text", display: "ما اسم صغير القط؟", accepted: ["الهر الصغير", "القط الصغير"] },
  { kind: "text", display: "ما اسم صغير الحصان؟", accepted: ["المهر"] },
  { kind: "text", display: "ما اسم صغير الجمل؟", accepted: ["الحوار"] },
  { kind: "text", display: "ما اسم صغير الأسد؟", accepted: ["الشبل"] },
  { kind: "text", display: "ما اسم صغير البقرة؟", accepted: ["العجل"] },
  { kind: "text", display: "ما اسم صغير الضفدع؟", accepted: ["الشرغوف"] },
  { kind: "text", display: "ما اسم منزل النحل؟", accepted: ["الخلية"] },
  { kind: "text", display: "ما اسم منزل الطيور؟", accepted: ["العش"] },
  { kind: "text", display: "ما اسم منزل النمل؟", accepted: ["القرية", "عش النمل"] },
  { kind: "text", display: "ما اسم منزل الأرانب؟", accepted: ["الجحر"] },
  { kind: "text", display: "ما اسم منزل الأسد؟", accepted: ["العرين"] },
  { kind: "text", display: "ما هو الحيوان الذي يبني السدود؟", accepted: ["القندس"] },
  { kind: "text", display: "ما هو الحيوان الذي يستطيع النوم لفترات طويلة في الشتاء (السبات)؟", accepted: ["الدب"] },
  { kind: "text", display: "ما اسم الظاهرة التي ينام فيها بعض الحيوانات طوال الشتاء؟", accepted: ["السبات الشتوي"] },
  { kind: "text", display: "ما اسم الحيوان الذي يمتلك أطول رقبة؟", accepted: ["الزرافة"] },
  { kind: "text", display: "كم عدد فقرات رقبة الزرافة؟", accepted: ["7", "سبع", "سبعة"] },
  { kind: "text", display: "ما هو الحيوان البري الأثقل وزناً؟", accepted: ["الفيل الأفريقي"] },
  { kind: "text", display: "كم يزن الفيل الأفريقي البالغ تقريباً؟", accepted: ["6 أطنان تقريباً"] },
  { kind: "text", display: "ما هو الحيوان الذي له بصمة أنف فريدة مثل بصمة الإصبع؟", accepted: ["الكلب"] },
  { kind: "text", display: "ما هو الحيوان الذي يمكنه الدوران برأسه بشكل شبه كامل؟", accepted: ["البومة"] },
  { kind: "text", display: "كم درجة يمكن للبومة أن تدير رأسها؟", accepted: ["270 درجة"] },
  { kind: "text", display: "ما هو الحيوان المائي الذي يستخدم الأدوات؟", accepted: ["ثعلب الماء", "قرش"] },
  { kind: "text", display: "ما هو الطائر الوطني لأمريكا؟", accepted: ["النسر الأصلع"] },
  { kind: "text", display: "ما هو الحيوان الوطني للصين؟", accepted: ["الباندا العملاقة"] },
  { kind: "text", display: "ما هو الحيوان الرمزي لأستراليا؟", accepted: ["الكنغر"] },
  { kind: "text", display: "ما اسم الطائر الذي يقلد أصوات أخرى؟", accepted: ["الببغاء"] },
  { kind: "text", display: "ما اسم أكبر بيضة بين الطيور؟", accepted: ["بيضة النعامة"] },
  { kind: "text", display: "ما هو أسرع طائر طيران أفقياً (وليس انقضاضاً)؟", accepted: ["الشاهين الأسود"] },
  { kind: "text", display: "ما هي مساحة السعودية تقريباً بالكيلومتر المربع؟", accepted: ["2.15 مليون كم2"] },
  { kind: "text", display: "ما هي مساحة مصر تقريباً؟", accepted: ["حوالي مليون كم2"] },
  { kind: "text", display: "كم عدد المحافظات في مصر؟", accepted: ["27"] },
  { kind: "text", display: "كم عدد المناطق الإدارية في السعودية؟", accepted: ["13"] },
  { kind: "text", display: "ما اسم أطول نهر في السعودية (وادي)؟", accepted: ["وادي حنيفة"] },
  { kind: "text", display: "ما اسم أكبر مدينة ساحلية في السعودية على البحر الأحمر؟", accepted: ["جدة"] },
  { kind: "text", display: "ما اسم أكبر مدينة سعودية على الخليج العربي؟", accepted: ["الدمام"] },
  { kind: "text", display: "ما اسم عاصمة السعودية الاقتصادية غير الرسمية أحياناً؟", accepted: ["جدة"] },
  { kind: "text", display: "ما اسم أقدم مدينة مأهولة في التاريخ؟", accepted: ["أريحا"] },
  { kind: "text", display: "أين تقع مدينة أريحا؟", accepted: ["فلسطين"] },
  { kind: "text", display: "ما اسم أول مدينة في العالم يُقدر عدد سكانها بمليون نسمة؟", accepted: ["روما القديمة"] },
  { kind: "text", display: "ما اسم أكبر مدينة في العالم من حيث عدد السكان اليوم تقريباً؟", accepted: ["طوكيو"] },
  { kind: "text", display: "ما اسم أكثر الدول اكتظاظاً بالسكان في العالم؟", accepted: ["الهند"] },
  { kind: "text", display: "ما اسم أكبر دولة في العالم من حيث المساحة؟", accepted: ["روسيا"] },
  { kind: "text", display: "ما اسم ثاني أكبر دولة في العالم من حيث المساحة؟", accepted: ["كندا"] },
  { kind: "text", display: "ما اسم أصغر دولة في العالم من حيث المساحة؟", accepted: ["الفاتيكان"] },
  { kind: "text", display: "كم عدد الدول التي تحيط بروسيا تقريباً؟", accepted: ["14"] },
  { kind: "text", display: "ما اسم أطول حدود دولية في العالم؟", accepted: ["الحدود بين كندا وأمريكا"] },
  { kind: "text", display: "ما اسم القارة التي لا يوجد بها سكان أصليون دائمون؟", accepted: ["القارة القطبية الجنوبية"] },
  { kind: "text", display: "كم عدد قارات العالم المعتمدة عادة؟", accepted: ["7", "سبع", "سبعة"] },
  { kind: "text", display: "ما اسم أصغر قارة من حيث المساحة؟", accepted: ["أستراليا"] },
  { kind: "text", display: "ما اسم القارة التي تقع فيها معظم الدول العربية؟", accepted: ["أفريقيا وآسيا"] },
  { kind: "text", display: "ما هو أطول شهر في السنة الميلادية بعدد الأيام؟", accepted: ["يناير", "مارس", "مايو", "يوليو", "أغسطس", "أكتوبر", "ديسمبر"] },
  { kind: "text", display: "ما هو أقصر شهر في السنة الميلادية؟", accepted: ["فبراير"] },
  { kind: "text", display: "كم عدد أيام شهر فبراير في السنة الكبيسة؟", accepted: ["29"] },
  { kind: "text", display: "كل كم سنة تأتي السنة الكبيسة؟", accepted: ["4", "أربع سنوات"] },
  { kind: "text", display: "كم عدد أيام الأسبوع؟", accepted: ["7", "سبع", "سبعة"] },
  { kind: "text", display: "ما هو أول يوم في الأسبوع حسب التقويم الهجري؟", accepted: ["الأحد"] },
  { kind: "text", display: "ما اسم التقويم المستخدم في تحديد شهر رمضان؟", accepted: ["التقويم الهجري القمري"] },
  { kind: "text", display: "كم عدد أشهر السنة الهجرية؟", accepted: ["12", "اثنا عشر"] },
  { kind: "text", display: "ما اسم أول شهر في السنة الهجرية؟", accepted: ["محرم"] },
  { kind: "text", display: "ما اسم آخر شهر في السنة الهجرية؟", accepted: ["ذو الحجة"] },
  { kind: "text", display: "ما اسم الأشهر الحرم في الإسلام؟", accepted: ["محرم ورجب وذو القعدة وذو الحجة"] },
  { kind: "text", display: "كم عدد الأشهر الحرم؟", accepted: ["4", "أربعة", "اربعه"] },
  { kind: "text", display: "من هو الخليفة الذي وضع بداية التقويم الهجري؟", accepted: ["عمر بن الخطاب"] },
  { kind: "text", display: "ما هو الحدث الذي بدأ منه التقويم الهجري؟", accepted: ["هجرة الرسول من مكة للمدينة"] },
  { kind: "text", display: "ما اسم غزوة أحد وفي أي سنة هجرية وقعت؟", accepted: ["السنة الثالثة للهجرة"] },
  { kind: "text", display: "من هو الصحابي الملقب بأسد الله؟", accepted: ["حمزة بن عبد المطلب"] },
  { kind: "text", display: "من هو الصحابي الملقب بسيف الله المسلول؟", accepted: ["خالد بن الوليد"] },
  { kind: "text", display: "من هو الصحابي الذي كان كاتباً للوحي وجمع القرآن؟", accepted: ["زيد بن ثابت"] },
  { kind: "text", display: "من هو الخليفة الذي جمع القرآن الكريم في مصحف واحد أول مرة؟", accepted: ["أبو بكر الصديق"] },
  { kind: "text", display: "من هو الخليفة الذي وحد المصاحف على قراءة واحدة؟", accepted: ["عثمان بن عفان"] },
  { kind: "text", display: "ما اسم المصحف الموحد الذي أرسله عثمان بن عفان للأمصار؟", accepted: ["مصحف عثمان"] },
  { kind: "text", display: "من هي أول امرأة أسلمت؟", accepted: ["خديجة بنت خويلد"] },
  { kind: "text", display: "من هي زوجة الرسول الملقبة بأم المؤمنين وابنة أبي بكر؟", accepted: ["عائشة بنت أبي بكر"] },
  { kind: "text", display: "من هو عم الرسول الذي كفله بعد وفاة جده؟", accepted: ["أبو طالب"] },
  { kind: "text", display: "من هو جد الرسول الذي كفله في صغره؟", accepted: ["عبد المطلب"] },
  { kind: "text", display: "كم كان عمر الرسول عند البعثة؟", accepted: ["40", "أربعون سنة"] },
  { kind: "text", display: "كم سنة استمرت الدعوة الإسلامية في مكة قبل الهجرة؟", accepted: ["13", "ثلاث عشرة سنة"] },
  { kind: "text", display: "كم سنة عاش الرسول في المدينة بعد الهجرة؟", accepted: ["10", "عشر سنوات"] },
  { kind: "text", display: "في أي سنة توفي الرسول صلى الله عليه وسلم؟", accepted: ["11 هجري", "632 ميلادي"] },
  { kind: "text", display: "من هو أول من استشهد في الإسلام؟", accepted: ["ياسر بن عامر", "سمية بنت خياط"] },
  { kind: "text", display: "ما اسم الجبل الذي نزل فيه الوحي على الرسول أول مرة؟", accepted: ["جبل النور"] },
  { kind: "text", display: "ما اسم الغار الذي كان يتعبد فيه الرسول؟", accepted: ["غار حراء"] },
  { kind: "text", display: "ما اسم الغار الذي اختبأ فيه الرسول وأبو بكر أثناء الهجرة؟", accepted: ["غار ثور"] },
  { kind: "text", display: "من هو الصحابي الذي رافق الرسول في الهجرة؟", accepted: ["أبو بكر الصديق"] },
  { kind: "text", display: "كم عدد أبواب الجنة المذكورة في الأحاديث؟", accepted: ["8", "ثمانية", "ثمانيه"] },
  { kind: "text", display: "كم عدد أبواب النار المذكورة في الأحاديث؟", accepted: ["7", "سبعة", "سبعه"] },
  { kind: "text", display: "ما اسم الكتاب المقدس عند المسيحيين؟", accepted: ["الإنجيل", "الكتاب المقدس"] },
  { kind: "text", display: "ما اسم الكتاب المقدس عند اليهود؟", accepted: ["التوراة"] },
  { kind: "text", display: "ما اسم المدينة المقدسة عند الديانات السماوية الثلاث؟", accepted: ["القدس"] },
  { kind: "text", display: "ما اسم أول مسجد قبلة للمسلمين قبل الكعبة؟", accepted: ["المسجد الأقصى"] },
  { kind: "text", display: "كم عدد الأنبياء أولي العزم؟", accepted: ["5", "خمسة", "خمسه"] },
  { kind: "text", display: "من هم أولو العزم من الرسل؟", accepted: ["نوح وإبراهيم وموسى وعيسى ومحمد"] },
  { kind: "text", display: "ما اسم النبي الذي بنى السفينة لنجاة قومه من الطوفان؟", accepted: ["نوح"] },
  { kind: "text", display: "ما اسم النبي الذي كلمه الله مباشرة على جبل الطور؟", accepted: ["موسى"] },
  { kind: "text", display: "ما اسم النبي الذي أُعطي معجزة إحياء الموتى بإذن الله؟", accepted: ["عيسى"] },
  { kind: "text", display: "ما اسم النبي الذي كان نجاراً وبنى الكعبة مع ابنه؟", accepted: ["إبراهيم وإسماعيل"] },
  { kind: "text", display: "من هو ابن النبي إبراهيم الذي أُمر بذبحه في الرؤيا؟", accepted: ["إسماعيل"] },
  { kind: "text", display: "ما اسم أول امرأة عربية تصعد للفضاء؟", accepted: ["ريانة برناوي"] },
  { kind: "text", display: "ما اسم أول رائد فضاء إماراتي؟", accepted: ["هزاع المنصوري"] },
  { kind: "text", display: "ما اسم أول قمر صناعي إماراتي؟", accepted: ["ذو الفقار"] },
  { kind: "text", display: "ما اسم مسبار الإمارات لاستكشاف المريخ؟", accepted: ["مسبار الأمل"] },
  { kind: "text", display: "في أي عام وصل مسبار الأمل الإماراتي للمريخ؟", accepted: ["2021"] },
  { kind: "text", display: "ما اسم أول مطار في الوطن العربي؟", accepted: ["يختلف حسب المصدر"] },
  { kind: "text", display: "ما اسم أكبر مطار في العالم من حيث المساحة؟", accepted: ["مطار الملك خالد الدولي"] },
  { kind: "text", display: "ما اسم أكثر مطار ازدحاماً في العالم من حيث عدد الركاب عادة؟", accepted: ["مطار أتلانتا"] },
  { kind: "text", display: "ما اسم أطول رحلة طيران تجارية مباشرة في العالم تقريباً؟", accepted: ["سنغافورة إلى نيويورك"] },
  { kind: "text", display: "ما اسم أول طائرة ركاب نفاثة تجارية؟", accepted: ["دي هافيلاند كوميت"] },
  { kind: "text", display: "ما اسم أكبر طائرة ركاب في العالم؟", accepted: ["إيرباص A380"] },
  { kind: "text", display: "من الشركة المصنعة لطائرة A380؟", accepted: ["إيرباص"] },
  { kind: "text", display: "ما اسم أشهر طائرة حربية شبح أمريكية؟", accepted: ["إف 22"] },
  { kind: "text", display: "ما اسم أول رحلة تجارية عبر المحيط الأطلسي؟", accepted: ["يختلف حسب المصدر"] },
  { kind: "text", display: "من أول من طار بمنطاد هواء ساخن؟", accepted: ["الأخوان مونتغولفييه"] },
  { kind: "text", display: "ما اسم أول سفينة فضاء تحمل بشراً حول القمر؟", accepted: ["أبولو 8"] },
  { kind: "text", display: "ما اسم أول محطة فضائية في التاريخ؟", accepted: ["ساليوت 1"] },
  { kind: "text", display: "من أطلق أول محطة فضائية؟", accepted: ["الاتحاد السوفيتي"] },
  { kind: "text", display: "ما اسم المحطة الفضائية الحالية المأهولة بشكل دائم؟", accepted: ["محطة الفضاء الدولية"] },
  { kind: "text", display: "كم عدد الدول المشاركة في محطة الفضاء الدولية تقريباً؟", accepted: ["5 وكالات رئيسية"] },
  { kind: "text", display: "ما اسم أول شركة خاصة أرسلت بشراً للفضاء؟", accepted: ["سبيس إكس"] },
  { kind: "text", display: "ما اسم صاروخ سبيس إكس القابل لإعادة الاستخدام الأشهر؟", accepted: ["فالكون 9"] },
  { kind: "text", display: "ما اسم كبسولة سبيس إكس المخصصة لنقل رواد الفضاء؟", accepted: ["دراغون"] },
  { kind: "text", display: "من هو مؤسس شركة بلو أوريجن؟", accepted: ["جيف بيزوس"] },
  { kind: "text", display: "من هو مؤسس شركة فيرجن غالاكتيك؟", accepted: ["ريتشارد برانسون"] },
  { kind: "text", display: "ما اسم أول دولة عربية تطلق قمراً صناعياً؟", accepted: ["السعودية"] },
  { kind: "text", display: "ما اسم برنامج الفضاء السعودي الحديث؟", accepted: ["الهيئة السعودية للفضاء"] },
  { kind: "text", display: "ما اسم أول قمر صناعي سعودي؟", accepted: ["سعودي سات 1"] },
  { kind: "text", display: "ما اسم مدينة الملك عبدالله للطاقة الذرية والمتجددة اختصاراً؟", accepted: ["كاكِست"] },
  { kind: "text", display: "ما اسم مشروع نيوم في السعودية؟", accepted: ["مدينة مستقبلية بالسعودية"] },
  { kind: "text", display: "ما اسم العملة المستخدمة في اليابان؟", accepted: ["الين"] },
  { kind: "text", display: "ما اسم العملة المستخدمة في كوريا الجنوبية؟", accepted: ["الوون"] },
  { kind: "text", display: "ما اسم العملة المستخدمة في الهند؟", accepted: ["الروبية"] },
  { kind: "text", display: "ما اسم العملة المستخدمة في تايلاند؟", accepted: ["الباهت"] },
  { kind: "text", display: "ما اسم العملة المستخدمة في إندونيسيا؟", accepted: ["الروبية الإندونيسية"] },
  { kind: "text", display: "ما اسم العملة المستخدمة في المكسيك؟", accepted: ["البيزو"] },
  { kind: "text", display: "ما اسم العملة المستخدمة في البرازيل؟", accepted: ["الريال البرازيلي"] },
  { kind: "text", display: "ما اسم العملة المستخدمة في جنوب أفريقيا؟", accepted: ["الراند"] },
  { kind: "text", display: "ما اسم العملة المستخدمة في نيجيريا؟", accepted: ["النايرا"] },
  { kind: "text", display: "ما اسم العملة المستخدمة في مصر؟", accepted: ["الجنيه المصري"] },
  { kind: "text", display: "ما اسم العملة المستخدمة في الأردن؟", accepted: ["الدينار الأردني"] },
  { kind: "text", display: "ما اسم العملة المستخدمة في العراق؟", accepted: ["الدينار العراقي"] },
  { kind: "text", display: "ما اسم العملة المستخدمة في المغرب؟", accepted: ["الدرهم المغربي"] },
  { kind: "text", display: "ما اسم العملة المستخدمة في الجزائر؟", accepted: ["الدينار الجزائري"] },
  { kind: "text", display: "ما اسم العملة المستخدمة في تونس؟", accepted: ["الدينار التونسي"] },
  { kind: "text", display: "ما اسم العملة المستخدمة في لبنان؟", accepted: ["الليرة اللبنانية"] },
  { kind: "text", display: "ما اسم العملة المستخدمة في سوريا؟", accepted: ["الليرة السورية"] },
  { kind: "text", display: "ما اسم العملة المستخدمة في اليمن؟", accepted: ["الريال اليمني"] },
  { kind: "text", display: "ما اسم العملة المستخدمة في عُمان؟", accepted: ["الريال العُماني"] },
  { kind: "text", display: "ما اسم العملة المستخدمة في السودان؟", accepted: ["الجنيه السوداني"] },
  { kind: "text", display: "من مخترع لعبة كرة القدم الحديثة (وضع القوانين)؟", accepted: ["الإنجليز"] },
  { kind: "text", display: "في أي دولة نشأت لعبة كرة السلة؟", accepted: ["أمريكا"] },
  { kind: "text", display: "من مخترع لعبة كرة السلة؟", accepted: ["جيمس نايسميث"] },
  { kind: "text", display: "في أي دولة نشأت رياضة البيسبول؟", accepted: ["أمريكا"] },
  { kind: "text", display: "في أي دولة نشأت رياضة الرغبي؟", accepted: ["إنجلترا"] },
  { kind: "text", display: "في أي دولة نشأت رياضة الكريكيت؟", accepted: ["إنجلترا"] },
  { kind: "text", display: "في أي دولة نشأت رياضة الجودو؟", accepted: ["اليابان"] },
  { kind: "text", display: "في أي دولة نشأت رياضة الكاراتيه؟", accepted: ["اليابان"] },
  { kind: "text", display: "في أي دولة نشأت رياضة التايكوندو؟", accepted: ["كوريا الجنوبية"] },
  { kind: "text", display: "في أي دولة نشأت رياضة الملاكمة التايلاندية؟", accepted: ["تايلاند"] },
  { kind: "text", display: "في أي دولة نشأت رياضة السومو؟", accepted: ["اليابان"] },
  { kind: "text", display: "ما اسم أشهر سباق للفورمولا 1 في السعودية؟", accepted: ["جائزة السعودية الكبرى"] },
  { kind: "text", display: "في أي مدينة سعودية يقام سباق الفورمولا 1؟", accepted: ["جدة"] },
  { kind: "text", display: "من هو أكثر سائق تتويجاً بلقب الفورمولا 1 (بالتساوي)؟", accepted: ["لويس هاميلتون ومايكل شوماخر"] },
  { kind: "text", display: "ما اسم أشهر حلبة سباقات في موناكو؟", accepted: ["حلبة موناكو"] },
  { kind: "text", display: "كم عدد جولات موسم الفورمولا 1 تقريباً؟", accepted: ["يزيد عن 20 جولة"] },
  { kind: "text", display: "ما اسم أول بطل عالم في الفورمولا 1؟", accepted: ["جيوسيبي فارينا"] },
  { kind: "text", display: "ما اسم أصغر بطل عالم في الفورمولا 1؟", accepted: ["سيباستيان فيتل"] },
  { kind: "text", display: "ما اسم النادي السعودي الملقب بالزعيم؟", accepted: ["الهلال"] },
  { kind: "text", display: "ما اسم النادي السعودي الملقب بالعميد؟", accepted: ["الاتحاد"] },
  { kind: "text", display: "ما اسم النادي السعودي الملقب بالعميق؟", accepted: ["النصر"] },
  { kind: "text", display: "من هو اللاعب البرتغالي الذي انضم لنادي النصر السعودي؟", accepted: ["كريستيانو رونالدو"] },
  { kind: "text", display: "ما اسم دوري كرة القدم السعودي؟", accepted: ["دوري روشن السعودي"] },
  { kind: "text", display: "كم مرة فاز الهلال بدوري أبطال آسيا؟", accepted: ["4 مرات تقريباً"] },
  { kind: "text", display: "ما اسم أول بطولة كأس خليجي أقيمت؟", accepted: ["خليجي 1"] },
  { kind: "text", display: "أين أقيمت أول بطولة خليجية؟", accepted: ["البحرين"] },
  { kind: "text", display: "ما اسم المنتخب الأكثر تتويجاً بكأس الخليج؟", accepted: ["السعودية"] },
  { kind: "text", display: "من هو أول لاعب عربي يفوز بالكرة الذهبية؟", accepted: ["لم يفز أي لاعب عربي بها حتى الآن"] },
  { kind: "text", display: "ما اسم أول مسجد بني خارج الجزيرة العربية؟", accepted: ["مسجد عمرو بن العاص"] },
  { kind: "text", display: "أين يقع مسجد عمرو بن العاص؟", accepted: ["مصر"] },
  { kind: "text", display: "ما اسم أقدم مسجد في المغرب العربي؟", accepted: ["جامع عقبة بن نافع"] },
  { kind: "text", display: "ما اسم أكبر مسجد في أوروبا؟", accepted: ["يختلف حسب التصنيف"] },
  { kind: "text", display: "ما اسم أكبر مسجد في إندونيسيا؟", accepted: ["مسجد الاستقلال"] },
  { kind: "text", display: "ما اسم أكبر مسجد في ماليزيا؟", accepted: ["المسجد الوطني"] },
  { kind: "text", display: "ما اسم المسجد الذي بناه صلاح الدين الأيوبي في القاهرة؟", accepted: ["يختلف حسب المصدر"] },
  { kind: "text", display: "ما اسم قلعة صلاح الدين الشهيرة في القاهرة؟", accepted: ["قلعة صلاح الدين"] },
  { kind: "text", display: "ما اسم الحي القديم الشهير في دمشق؟", accepted: ["البلدة القديمة"] },
  { kind: "text", display: "ما اسم السوق القديم الشهير في حلب؟", accepted: ["سوق المدينة"] },
  { kind: "text", display: "ما اسم القصر الملكي الشهير في مراكش؟", accepted: ["قصر الباهية"] },
  { kind: "text", display: "ما اسم أشهر حي تاريخي في فاس بالمغرب؟", accepted: ["فاس البالي"] },
  { kind: "text", display: "ما اسم أشهر سوق تقليدي في مراكش؟", accepted: ["جامع الفنا"] },
  { kind: "text", display: "ما اسم أشهر شارع تجاري في دبي؟", accepted: ["شارع الشيخ زايد"] },
  { kind: "text", display: "ما اسم الجزيرة الاصطناعية الشهيرة في دبي على شكل نخلة؟", accepted: ["نخلة جميرا"] },
  { kind: "text", display: "ما اسم أشهر فندق شراعي الشكل في دبي؟", accepted: ["برج العرب"] },
  { kind: "text", display: "ما اسم أكبر مركز تسوق في العالم تقريباً؟", accepted: ["يختلف حسب التصنيف"] },
  { kind: "text", display: "ما اسم أكبر حديقة مائية في الشرق الأوسط تقريباً؟", accepted: ["يختلف حسب الموقع"] },
  { kind: "text", display: "ما اسم أول ناطحة سحاب في العالم؟", accepted: ["مبنى التأمين المنزلي بشيكاغو"] },
  { kind: "text", display: "ما اسم أطول برج سكني في العالم تقريباً؟", accepted: ["برج خليفة يضم أيضاً وحدات سكنية"] },
  { kind: "text", display: "كم طابقاً يضم برج خليفة تقريباً؟", accepted: ["163"] },
  { kind: "text", display: "كم يبلغ ارتفاع برج خليفة تقريباً؟", accepted: ["828 متر"] }
];
